# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""SLA and bootstrap coverage for Intel B60 planner profiling data."""

from pathlib import Path
from unittest.mock import Mock

import pytest
import yaml

from dynamo.planner.config.defaults import SubComponentType
from dynamo.planner.config.planner_config import PlannerConfig
from dynamo.planner.core.budget import _initialize_gpu_counts
from dynamo.planner.errors import DeploymentValidationError
from dynamo.planner.monitoring.perf_metrics import _convert_profiling_data_to_fpms

pytestmark = [
    pytest.mark.gpu_0,
    pytest.mark.pre_merge,
    pytest.mark.unit,
    pytest.mark.planner,
]

B60_PROFILE_DIR = Path(__file__).parent.parent / "data/profiling_results/B60_TP1P_TP1D"


def test_b60_disagg_fixture_matches_xpu_dra_contract():
    """Keep the fixture aligned with the XPU config generated by PR 7794."""
    with (B60_PROFILE_DIR / "disagg.yaml").open() as stream:
        resource_claim, deployment = list(yaml.safe_load_all(stream))

    assert resource_claim["apiVersion"] == "resource.k8s.io/v1"
    assert resource_claim["kind"] == "ResourceClaimTemplate"
    request = resource_claim["spec"]["spec"]["devices"]["requests"][0]
    assert request["exactly"] == {
        "deviceClassName": "gpu.intel.com",
        "count": 1,
    }

    template_name = resource_claim["metadata"]["name"]
    services = deployment["spec"]["services"]
    for worker_name in ("VllmPrefillWorker", "VllmDecodeWorker"):
        pod_spec = services[worker_name]["extraPodSpec"]
        assert pod_spec["resourceClaims"] == [
            {
                "name": "gpu",
                "resourceClaimTemplateName": template_name,
            }
        ]
        container = pod_spec["mainContainer"]
        assert {entry["name"]: entry["value"] for entry in container["env"]}[
            "VLLM_TARGET_DEVICE"
        ] == "xpu"
        assert container["resources"]["claims"] == [{"name": "gpu"}]


@pytest.mark.parametrize(
    "component",
    [SubComponentType.PREFILL, SubComponentType.DECODE],
)
def test_b60_profile_converts_to_forward_pass_metrics(component):
    fpms = _convert_profiling_data_to_fpms(str(B60_PROFILE_DIR), component)

    assert len(fpms) >= 5
    assert all(fpm.wall_time > 0 for fpm in fpms)


def test_xpu_kubernetes_mode_reads_gpu_counts_from_deployment():
    config = PlannerConfig.model_construct(
        prefill_engine_num_gpu=None,
        decode_engine_num_gpu=None,
    )
    connector = Mock()
    connector.get_gpu_counts.return_value = (1, 1)

    _initialize_gpu_counts(config, connector, require_prefill=True, require_decode=True)

    assert config.prefill_engine_num_gpu == 1
    assert config.decode_engine_num_gpu == 1


def test_xpu_virtual_mode_preserves_configured_gpu_counts():
    config = PlannerConfig.model_construct(
        prefill_engine_num_gpu=2,
        decode_engine_num_gpu=4,
    )
    connector = Mock(spec=[])

    _initialize_gpu_counts(config, connector, require_prefill=True, require_decode=True)

    assert config.prefill_engine_num_gpu == 2
    assert config.decode_engine_num_gpu == 4


def test_xpu_virtual_mode_requires_gpu_counts():
    config = PlannerConfig.model_construct(
        prefill_engine_num_gpu=None,
        decode_engine_num_gpu=None,
    )

    with pytest.raises(DeploymentValidationError) as exc_info:
        _initialize_gpu_counts(
            config, Mock(spec=[]), require_prefill=True, require_decode=True
        )

    assert len(exc_info.value.errors) == 2
