// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Generated by .github/scripts/build_install_selector.py — do not edit.

export const INSTALL_DATA = {
  "vllm": {
    "label": "vLLM",
    "image": "vllm",
    "extra": "vllm",
    "wheel": true,
    "stable": [
      {
        "backend_version": "v0.20.1",
        "dynamo": "1.2.1",
        "also": [
          "1.2.0"
        ],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.1",
          "wheel": "uv pip install \"ai-dynamo[vllm]==1.2.1\""
        }
      },
      {
        "backend_version": "v0.19.0",
        "dynamo": "1.1.1",
        "also": [],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.1.1",
          "wheel": "uv pip install \"ai-dynamo[vllm]==1.1.1\""
        }
      }
    ],
    "nightly": [
      {
        "backend_version": "v0.23.0",
        "latest": true,
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/vllm-runtime-nightly:latest",
          "wheel": "uv pip install --pre --extra-index-url https://pypi.nvidia.com/ \"ai-dynamo[vllm]\""
        }
      }
    ]
  },
  "sglang": {
    "label": "SGLang",
    "image": "sglang",
    "extra": "sglang",
    "wheel": true,
    "stable": [
      {
        "backend_version": "v0.5.11",
        "dynamo": "1.2.1",
        "also": [
          "1.2.0"
        ],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.2.1",
          "wheel": "uv pip install --prerelease=allow \"ai-dynamo[sglang]==1.2.1\""
        }
      },
      {
        "backend_version": "v0.5.10.post1",
        "dynamo": "1.1.1",
        "also": [],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.1.1",
          "wheel": "uv pip install --prerelease=allow \"ai-dynamo[sglang]==1.1.1\""
        }
      }
    ],
    "nightly": [
      {
        "backend_version": "v0.5.12.post1",
        "latest": true,
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/sglang-runtime-nightly:latest",
          "wheel": "uv pip install --pre --extra-index-url https://pypi.nvidia.com/ \"ai-dynamo[sglang]\""
        }
      }
    ]
  },
  "tensorrtllm": {
    "label": "TensorRT-LLM",
    "image": "tensorrtllm",
    "extra": "trtllm",
    "wheel": false,
    "stable": [
      {
        "backend_version": "1.3.0rc14",
        "dynamo": "1.2.1",
        "also": [
          "1.2.0"
        ],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:1.2.1"
        }
      },
      {
        "backend_version": "1.3.0rc11",
        "dynamo": "1.1.1",
        "also": [],
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:1.1.1"
        }
      }
    ],
    "nightly": [
      {
        "backend_version": "1.3.0rc18",
        "latest": true,
        "commands": {
          "container": "docker run --gpus all --network host --rm -it nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime-nightly:latest"
        }
      }
    ]
  }
};

export default INSTALL_DATA;
