/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * ReleaseSupportMatrix — human-facing release compatibility log for the
 * Compatibility reference page. Renders one panel that lists every stable
 * release and patch, grouped by minor line, with CUDA major (12 vs 13) as
 * the dominant visual anchor rather than a number buried mid-row.
 *
 * Every row is derived from CUDA_HISTORY and RELEASES in releases.data.ts;
 * nothing is transcribed or duplicated here. The Compatibility page's
 * <llms-only> twin (generated by scripts/gen_llms_tables.py) carries the
 * same rows as a flat markdown table so agent-facing exports never lose
 * the matrix; this component is deliberately the human-only rendering.
 *
 * CSS is injected via dangerouslySetInnerHTML, not as a <style> text child:
 * a text child is escaped on render, which turns any `>` child combinator
 * into &gt; and silently drops the rule (see #12402).
 *
 * Server component (no "use client"); shares the .dynref-* base vocabulary
 * from ReferenceStyles.tsx (panels, eyebrow, chips, badges, muted text,
 * mono, dark-mode variables) and carries only its own .dynref-rsm-* layout
 * rules. Minor lines use native <details>/<summary> for progressive
 * disclosure, so no client JS is required.
 */

import {
  RELEASES,
  CUDA_HISTORY,
  CUDA_NOTES,
  type CudaRow,
  type Release,
} from "./releases.data";

const RSM_CSS = `
.dynref-rsm-legend {
    display: inline-flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 6px 12px;
    font-size: 12px;
    color: var(--pst-color-text-muted);
}

.dynref-rsm-legend-caption {
    letter-spacing: 0.04em;
    text-transform: uppercase;
    font-weight: 700;
}

.dynref-rsm-line {
    margin: 12px 0 0;
    padding: 0;
    border: 1px solid var(--border, var(--grayscale-a5));
    border-radius: 10px;
    background: var(--pst-color-surface);
}

.dark .dynref-rsm-line {
    background: #161616;
    border-color: #2b2b2b;
}

.dynref-rsm-line[open] { padding-bottom: 12px; }

.dynref-rsm-line-summary {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 8px 14px;
    padding: 10px 14px;
    cursor: pointer;
    list-style: none;
    color: var(--pst-color-text-base);
    font-size: 14px;
    border-radius: 10px;
}

.dynref-rsm-line-summary::-webkit-details-marker { display: none; }

.dynref-rsm-line-summary::before {
    content: "▸";
    display: inline-block;
    width: 12px;
    color: var(--pst-color-text-muted);
    font-size: 12px;
    transition: transform 0.15s ease;
}

.dynref-rsm-line[open] > .dynref-rsm-line-summary::before {
    transform: rotate(90deg);
}

.dynref-rsm-line-summary:hover { background: rgba(118, 185, 0, 0.06); }
.dark .dynref-rsm-line-summary:hover { background: rgba(118, 185, 0, 0.10); }

.dynref-rsm-line-summary:focus-visible {
    outline: 2px solid var(--nv-color-green, #76B900);
    outline-offset: -2px;
}

.dynref-rsm-line-title {
    font-weight: 700;
    letter-spacing: 0.01em;
}

.dynref-rsm-line-meta {
    color: var(--pst-color-text-muted);
    font-size: 12.5px;
}

.dynref-rsm-line-cudas {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    margin-left: auto;
}

.dynref-rsm-release {
    margin: 8px 14px 0;
    padding: 12px 14px;
    border: 1px solid var(--border, var(--grayscale-a5));
    border-radius: 10px;
    background: var(--pst-color-surface);
}

.dark .dynref-rsm-release {
    background: #1c1c1c;
    border-color: #2e2e2e;
}

.dynref-rsm-release-header {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px 12px;
    margin-bottom: 12px;
}

.dynref-rsm-release-version {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    color: var(--pst-color-text-base);
    font-size: 15px;
    font-weight: 700;
}

.dynref-rsm-release-meta {
    color: var(--pst-color-text-muted);
    font-size: 12.5px;
}

.dynref-rsm-release-ucx {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    margin-left: auto;
    color: var(--pst-color-text-muted);
    font-size: 12.5px;
}

.dynref-rsm-cuda-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 12px;
}

.dynref-rsm-cuda-block {
    padding: 12px 14px;
    border: 1px solid var(--border, var(--grayscale-a5));
    border-radius: 10px;
    background: rgba(147, 51, 234, 0.03);
}

.dark .dynref-rsm-cuda-block {
    background: rgba(168, 85, 247, 0.05);
    border-color: #333;
}

.dynref-rsm-cuda-header {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px 10px;
    margin-bottom: 10px;
    padding-bottom: 8px;
    border-bottom: 1px dashed var(--border, var(--grayscale-a5));
}

.dark .dynref-rsm-cuda-header { border-bottom-color: #333; }

.dynref-rsm-cuda-driver {
    color: var(--pst-color-text-muted);
    font-size: 12px;
}

.dynref-rsm-backend-list {
    display: grid;
    gap: 8px;
}

.dynref-rsm-backend-row {
    display: grid;
    grid-template-columns: minmax(0, 1.05fr) minmax(0, 0.85fr) minmax(0, 0.75fr) minmax(0, 0.85fr) minmax(0, 0.75fr);
    align-items: baseline;
    gap: 4px 12px;
    padding: 6px 0;
    border-top: 1px solid rgba(147, 51, 234, 0.08);
}

.dark .dynref-rsm-backend-row { border-top-color: rgba(168, 85, 247, 0.14); }

.dynref-rsm-backend-row:first-child { border-top: 0; padding-top: 2px; }

.dynref-rsm-backend-name {
    color: var(--pst-color-text-base);
    font-weight: 600;
    font-size: 13.5px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.dynref-rsm-backend-cell {
    display: inline-flex;
    align-items: baseline;
    gap: 4px;
    color: var(--pst-color-text-base);
    font-size: 13px;
    min-width: 0;
}

.dynref-rsm-cell-label {
    color: var(--pst-color-text-muted);
    font-size: 11.5px;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    font-weight: 700;
}

.dynref-rsm-cell-value {
    font-variant-numeric: tabular-nums;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.dynref-rsm-backend-note {
    grid-column: 1 / -1;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    margin-top: 2px;
}

.dynref-rsm-notes {
    margin: 12px 14px 0;
    padding: 0;
    list-style: none;
    color: var(--pst-color-text-muted);
    font-size: 12px;
}

.dynref-rsm-notes li {
    margin: 4px 0;
    padding-left: 12px;
    position: relative;
}

.dynref-rsm-notes li::before {
    content: "·";
    position: absolute;
    left: 0;
    top: -2px;
    font-size: 16px;
}

@media (max-width: 640px) {
    .dynref-rsm-backend-row {
        grid-template-columns: 1fr 1fr;
    }
    .dynref-rsm-line-cudas { margin-left: 0; }
    .dynref-rsm-release-ucx { margin-left: 0; }
}
`;

// Only stable and patch releases carry CUDA_HISTORY rows and belong in the
// support matrix. Platform previews and model-specific builds are excluded;
// CUDA_NOTES calls out the ones whose toolkit support differs, and the
// machine-readable releases page carries the full inventory.
const SUPPORT_KINDS: ReadonlySet<Release["kind"]> = new Set(["stable", "patch"]);

// CUDA majors the matrix knows how to render, in display order. A toolkit
// whose leading integer sits outside this set fails the render rather than
// silently skipping the row -- the same fail-closed discipline the parser
// uses when releases.data.ts grows a construct it has not been taught yet.
const CUDA_MAJORS = ["12", "13"] as const;
type CudaMajor = (typeof CUDA_MAJORS)[number];

interface BackendCells {
  engineKey: "sglang" | "trtllm" | "vllm";
  nixlKey: "nixlSglang" | "nixlTrtllm" | "nixlVllm";
}

const BACKEND_PIN_KEYS: Record<CudaRow["backend"], BackendCells> = {
  SGLang: { engineKey: "sglang", nixlKey: "nixlSglang" },
  "TensorRT-LLM": { engineKey: "trtllm", nixlKey: "nixlTrtllm" },
  vLLM: { engineKey: "vllm", nixlKey: "nixlVllm" },
};

function cudaMajor(toolkit: string): CudaMajor {
  const major = toolkit.split(".", 1)[0];
  if (major === "12" || major === "13") return major;
  throw new Error(
    `ReleaseSupportMatrix: CUDA toolkit "${toolkit}" is outside the known ` +
      `majors ${CUDA_MAJORS.join(" / ")}; extend the component`,
  );
}

interface BackendLine {
  backend: CudaRow["backend"];
  engine?: string;
  toolkit: string;
  minDriver: string;
  nixl?: string;
  note?: string;
}

interface MajorBlock {
  major: CudaMajor;
  lines: BackendLine[];
  drivers: string[]; // unique, order-preserving
}

interface ReleaseBlock {
  release: Release;
  version: string; // bare (no leading v)
  blocks: MajorBlock[]; // only majors that ship rows for this release
  postTrains: string[]; // bare versions inheriting this release's CUDA support
}

interface MinorGroup {
  minor: string; // e.g. "1.2.x"
  releases: ReleaseBlock[];
  majors: CudaMajor[]; // unique across all releases in the line, ordered
  releaseCount: number; // every stable/patch in the line, post trains included
}

function bareVersion(version: string): string {
  return version.startsWith("v") ? version.slice(1) : version;
}

function minorLine(version: string): string {
  const [major, minor] = version.split(".");
  if (!major || !minor) {
    throw new Error(`ReleaseSupportMatrix: cannot minor-group version ${version}`);
  }
  return `${major}.${minor}.x`;
}

/* '0.7.0.post1' -> '0.7.0'; anything else unchanged. Post trains republish
 * images or wheels off an existing release and carry no CUDA_HISTORY row --
 * CUDA_NOTES states they have the same CUDA support as their base. They are
 * therefore listed on their base's card rather than given one of their own. */
function postTrainBase(version: string): string {
  const cut = version.indexOf(".post");
  return cut === -1 ? version : version.slice(0, cut);
}

function supportedReleases(): string[] {
  return RELEASES.filter((rel) => SUPPORT_KINDS.has(rel.kind)).map((rel) =>
    bareVersion(rel.version),
  );
}

function releaseIndex(): Map<string, Release> {
  const idx = new Map<string, Release>();
  for (const rel of RELEASES) {
    if (SUPPORT_KINDS.has(rel.kind)) idx.set(bareVersion(rel.version), rel);
  }
  return idx;
}

function pushDriver(bucket: MajorBlock, driver: string): void {
  if (!bucket.drivers.includes(driver)) bucket.drivers.push(driver);
}

function buildMajorBlock(
  release: Release,
  rows: CudaRow[],
  major: CudaMajor,
): MajorBlock {
  const pins = release.pins ?? {};
  const block: MajorBlock = { major, lines: [], drivers: [] };
  for (const row of rows) {
    if (cudaMajor(row.toolkit) !== major) continue;
    const keys = BACKEND_PIN_KEYS[row.backend];
    block.lines.push({
      backend: row.backend,
      engine: keys ? pins[keys.engineKey] : undefined,
      toolkit: row.toolkit,
      minDriver: row.minDriver,
      nixl: keys ? pins[keys.nixlKey] : undefined,
      note: row.note,
    });
    pushDriver(block, row.minDriver);
  }
  return block;
}

function buildReleaseBlock(
  version: string,
  release: Release,
  rows: CudaRow[],
  postTrains: string[],
): ReleaseBlock {
  const blocks: MajorBlock[] = [];
  for (const major of CUDA_MAJORS) {
    const block = buildMajorBlock(release, rows, major);
    if (block.lines.length > 0) blocks.push(block);
  }
  return { release, version, blocks, postTrains };
}

function groupByMinorLine(): MinorGroup[] {
  const releases = releaseIndex();
  const supported = supportedReleases();
  const groups = new Map<string, MinorGroup>();
  const seenVersions = new Set<string>();
  for (const row of CUDA_HISTORY) {
    const version = row.version;
    const release = releases.get(version);
    if (!release || seenVersions.has(version)) continue;
    seenVersions.add(version);
    const line = minorLine(version);
    const versionRows = CUDA_HISTORY.filter((r) => r.version === version);
    const postTrains = supported.filter(
      (v) => v !== version && postTrainBase(v) === version,
    );
    const block = buildReleaseBlock(version, release, versionRows, postTrains);
    const group = groups.get(line) ?? {
      minor: line,
      releases: [],
      majors: [],
      // Counted from RELEASES, not from the cards: a post train shares its
      // base's card, so counting cards would report 0.8.x as two releases
      // when the line actually shipped five.
      releaseCount: supported.filter((v) => minorLine(v) === line).length,
    };
    group.releases.push(block);
    for (const b of block.blocks) {
      if (!group.majors.includes(b.major)) group.majors.push(b.major);
    }
    groups.set(line, group);
  }
  return Array.from(groups.values());
}

function driverSummary(block: MajorBlock): string {
  return block.drivers.join(" or ");
}

function kindBadge(kind: Release["kind"]): { className: string; label: string } {
  if (kind === "stable") return { className: "dynref-badge--green", label: "stable" };
  if (kind === "patch") return { className: "dynref-badge--gray", label: "patch" };
  // The support matrix only lists stable/patch (SUPPORT_KINDS gate), so any
  // other kind reaching this function is a data bug; render it neutrally
  // rather than throwing so the page still loads.
  return { className: "dynref-badge--gray", label: kind };
}

function CudaChip({ major }: { major: CudaMajor }) {
  return <span className="dynref-chip dynref-chip--cuda">CUDA {major}</span>;
}

function BackendRow({ line }: { line: BackendLine }) {
  return (
    <div className="dynref-rsm-backend-row">
      <span className="dynref-rsm-backend-name">{line.backend}</span>
      <span className="dynref-rsm-backend-cell">
        <span className="dynref-rsm-cell-label">Engine</span>
        <span className="dynref-rsm-cell-value dynref-mono">{line.engine ?? "—"}</span>
      </span>
      <span className="dynref-rsm-backend-cell">
        <span className="dynref-rsm-cell-label">Toolkit</span>
        <span className="dynref-rsm-cell-value dynref-mono">{line.toolkit}</span>
      </span>
      {/* Per-backend, not per-block: within one CUDA major the backends can
          sit on different toolkits and therefore different driver floors
          (v0.7.1 pairs SGLang/12.8 with 570.xx+ and vLLM/12.9 with 575.xx+).
          The block header summarises both, so the floor that applies to a
          reader's backend has to be readable on its own row. */}
      <span className="dynref-rsm-backend-cell">
        <span className="dynref-rsm-cell-label">Driver</span>
        <span className="dynref-rsm-cell-value dynref-mono">{line.minDriver}</span>
      </span>
      <span className="dynref-rsm-backend-cell">
        <span className="dynref-rsm-cell-label">NIXL</span>
        <span className="dynref-rsm-cell-value dynref-mono">{line.nixl ?? "—"}</span>
      </span>
      {line.note && (
        <span className="dynref-rsm-backend-note">
          <span className="dynref-badge dynref-badge--wip">{line.note}</span>
        </span>
      )}
    </div>
  );
}

function CudaMajorBlock({ block }: { block: MajorBlock }) {
  return (
    <div className="dynref-rsm-cuda-block">
      <div className="dynref-rsm-cuda-header">
        <CudaChip major={block.major} />
        <span className="dynref-rsm-cuda-driver">
          Driver <span className="dynref-mono">{driverSummary(block)}</span>
        </span>
      </div>
      <div className="dynref-rsm-backend-list">
        {block.lines.map((line) => (
          <BackendRow key={`${line.backend}-${line.toolkit}`} line={line} />
        ))}
      </div>
    </div>
  );
}

function ReleaseCard({ block }: { block: ReleaseBlock }) {
  const badge = kindBadge(block.release.kind);
  const ucx = block.release.ucx;
  return (
    <article className="dynref-rsm-release">
      <header className="dynref-rsm-release-header">
        <span className="dynref-rsm-release-version">
          v{block.version}
          <span className={`dynref-badge ${badge.className}`}>{badge.label}</span>
        </span>
        {block.release.date && (
          <span className="dynref-rsm-release-meta">{block.release.date}</span>
        )}
        {block.postTrains.length > 0 && (
          <span className="dynref-rsm-release-meta">
            Post trains{" "}
            <span className="dynref-mono">v{block.postTrains.join(", v")}</span>{" "}
            share this CUDA support
          </span>
        )}
        <span className="dynref-rsm-release-ucx">
          <span className="dynref-rsm-cell-label">UCX</span>
          {ucx ? (
            <span className="dynref-mono">{ucx}</span>
          ) : (
            <span className="dynref-rsm-cuda-driver">not specified</span>
          )}
        </span>
      </header>
      <div className="dynref-rsm-cuda-grid">
        {block.blocks.map((b) => (
          <CudaMajorBlock key={b.major} block={b} />
        ))}
      </div>
    </article>
  );
}

function MinorLineSummary({ group }: { group: MinorGroup }) {
  const releaseCount = group.releaseCount;
  return (
    <summary className="dynref-rsm-line-summary">
      <span className="dynref-rsm-line-title">{group.minor}</span>
      <span className="dynref-rsm-line-meta">
        {releaseCount} release{releaseCount === 1 ? "" : "s"}
      </span>
      <span className="dynref-rsm-line-cudas">
        {group.majors.map((major) => (
          <CudaChip key={major} major={major} />
        ))}
      </span>
    </summary>
  );
}

export function ReleaseSupportMatrix() {
  const groups = groupByMinorLine();
  if (groups.length === 0) {
    throw new Error(
      "ReleaseSupportMatrix: no CUDA_HISTORY row matched a stable/patch " +
        "release entry -- the matrix would render empty",
    );
  }
  const isNewest = (index: number) => index === 0;
  return (
    <div className="dynref-panel">
      <style dangerouslySetInnerHTML={{ __html: RSM_CSS }} />
      <div className="dynref-panel-header">
        <span className="dynref-h">Release support log</span>
        <div className="dynref-rsm-legend">
          <span className="dynref-rsm-legend-caption">Legend</span>
          <CudaChip major="12" />
          <CudaChip major="13" />
          <span className="dynref-badge dynref-badge--wip">Experimental</span>
        </div>
      </div>
      {groups.map((group, i) => (
        <details className="dynref-rsm-line" key={group.minor} open={isNewest(i)}>
          <MinorLineSummary group={group} />
          {group.releases.map((block) => (
            <ReleaseCard key={block.version} block={block} />
          ))}
        </details>
      ))}
      <ul className="dynref-rsm-notes">
        {CUDA_NOTES.map((note) => (
          <li key={note}>{note}</li>
        ))}
      </ul>
    </div>
  );
}
