package criu

import (
	"fmt"
	"net/netip"
	"os"
	"sort"
	"strings"

	"github.com/go-logr/logr"

	"github.com/ai-dynamo/dynamo/deploy/snapshot/internal/types"
)

const (
	// InetRemapEnvVar points the CRIU INET remap plugin at the restore-time IP map.
	InetRemapEnvVar = "SNAPSHOT_CRIU_INET_REMAP_FILE"

	maxInetRemapEntries = 256
)

type inetRemapEntry struct {
	source netip.Addr
	target netip.Addr
}

// ConfigureInetRemap writes the CRIU plugin manifest for pod IP changes.
func ConfigureInetRemap(
	m *types.CheckpointManifest,
	targetPodIP string,
	explicitRemap string,
	log logr.Logger,
) error {
	if err := os.Unsetenv(InetRemapEnvVar); err != nil {
		return fmt.Errorf("failed to clear %s: %w", InetRemapEnvVar, err)
	}

	explicit := strings.TrimSpace(explicitRemap) != ""
	if !m.CRIUDump.CRIU.TcpEstablished && !explicit {
		log.V(1).Info("Skipping CRIU INET socket remap: tcpEstablished is disabled")
		return nil
	}

	entries, err := buildInetRemapEntries(m.K8s.PodIP, targetPodIP, explicitRemap)
	if err != nil {
		return err
	}
	if !m.CRIUDump.CRIU.TcpEstablished {
		log.V(1).Info("Skipping validated explicit CRIU INET socket remap: tcpEstablished is disabled",
			"mapping_count", len(entries),
		)
		return nil
	}
	if len(entries) == 0 {
		log.V(1).Info("Skipping CRIU INET socket remap",
			"source_pod_ip_present", strings.TrimSpace(m.K8s.PodIP) != "",
			"target_pod_ip_present", strings.TrimSpace(targetPodIP) != "",
		)
		return nil
	}
	if strings.TrimSpace(m.CRIUDump.CRIU.LibDir) == "" && strings.TrimSpace(os.Getenv("CRIU_LIBS_DIR")) == "" {
		return fmt.Errorf("CRIU INET socket remap requires criu.libDir or CRIU_LIBS_DIR so CRIU can load the Snapshot CRIU plugin")
	}

	remapDir := strings.TrimSpace(m.CRIUDump.CRIU.WorkDir)
	if remapDir == "" {
		remapDir = os.TempDir()
	}
	if err := os.MkdirAll(remapDir, 0755); err != nil {
		return fmt.Errorf("failed to create CRIU INET remap directory: %w", err)
	}

	remapFile, err := os.CreateTemp(remapDir, "snapshot-inet-remap-*.map")
	if err != nil {
		return fmt.Errorf("failed to create CRIU INET remap file: %w", err)
	}
	remapPath := remapFile.Name()
	var content strings.Builder
	content.WriteString("# generated by Dynamo Snapshot\n")
	for _, entry := range entries {
		fmt.Fprintf(&content, "%s %s\n", entry.source, entry.target)
	}
	if _, err := remapFile.WriteString(content.String()); err != nil {
		_ = remapFile.Close()
		_ = os.Remove(remapPath)
		return fmt.Errorf("failed to write CRIU INET remap file: %w", err)
	}
	if err := remapFile.Close(); err != nil {
		_ = os.Remove(remapPath)
		return fmt.Errorf("failed to close CRIU INET remap file: %w", err)
	}
	if err := os.Setenv(InetRemapEnvVar, remapPath); err != nil {
		return fmt.Errorf("failed to set %s: %w", InetRemapEnvVar, err)
	}

	if explicit {
		log.Info("Configured explicit distributed CRIU INET socket remap",
			"mapping_count", len(entries),
			"remap_file", remapPath,
		)
		return nil
	}
	log.Info("Configured CRIU INET socket remap",
		"source_pod_ip", entries[0].source,
		"target_pod_ip", entries[0].target,
		"remap_file", remapPath,
	)
	return nil
}

func buildInetRemapEntries(sourcePodIP, targetPodIP, explicitRemap string) ([]inetRemapEntry, error) {
	sourcePodIP = strings.TrimSpace(sourcePodIP)
	targetPodIP = strings.TrimSpace(targetPodIP)
	if strings.TrimSpace(explicitRemap) == "" {
		if sourcePodIP == "" || targetPodIP == "" {
			return nil, nil
		}
		source, err := netip.ParseAddr(sourcePodIP)
		if err != nil {
			return nil, fmt.Errorf("invalid source pod IP %q in checkpoint manifest: %w", sourcePodIP, err)
		}
		target, err := netip.ParseAddr(targetPodIP)
		if err != nil {
			return nil, fmt.Errorf("invalid target pod IP %q: %w", targetPodIP, err)
		}
		if source == target {
			return nil, nil
		}
		if !source.Is4() || !target.Is4() {
			return nil, fmt.Errorf(
				"CRIU INET socket remap only supports IPv4 pod IPs today: source=%q target=%q",
				sourcePodIP,
				targetPodIP,
			)
		}
		return []inetRemapEntry{{source: source, target: target}}, nil
	}

	source, err := parseNativeIPv4(sourcePodIP, "source pod IP in checkpoint manifest")
	if err != nil {
		return nil, err
	}
	target, err := parseNativeIPv4(targetPodIP, "target pod IP")
	if err != nil {
		return nil, err
	}

	lines := strings.Split(explicitRemap, "\n")
	entries := make([]inetRemapEntry, 0, len(lines))
	sources := make(map[netip.Addr]struct{}, len(lines))
	targets := make(map[netip.Addr]struct{}, len(lines))
	for index, line := range lines {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if len(fields) != 2 {
			return nil, fmt.Errorf("invalid explicit CRIU INET remap line %d: expected exactly two fields", index+1)
		}
		entrySource, err := parseNativeIPv4(fields[0], fmt.Sprintf("source address on explicit CRIU INET remap line %d", index+1))
		if err != nil {
			return nil, err
		}
		entryTarget, err := parseNativeIPv4(fields[1], fmt.Sprintf("target address on explicit CRIU INET remap line %d", index+1))
		if err != nil {
			return nil, err
		}
		if _, duplicate := sources[entrySource]; duplicate {
			return nil, fmt.Errorf("duplicate source address %q in explicit CRIU INET remap", entrySource)
		}
		if _, duplicate := targets[entryTarget]; duplicate {
			return nil, fmt.Errorf("duplicate target address %q in explicit CRIU INET remap", entryTarget)
		}
		sources[entrySource] = struct{}{}
		targets[entryTarget] = struct{}{}
		entries = append(entries, inetRemapEntry{source: entrySource, target: entryTarget})
		if len(entries) > maxInetRemapEntries {
			return nil, fmt.Errorf("explicit CRIU INET remap has too many mappings: max %d", maxInetRemapEntries)
		}
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("explicit CRIU INET remap is empty")
	}

	var currentTarget netip.Addr
	for _, entry := range entries {
		if entry.source == source {
			currentTarget = entry.target
			break
		}
	}
	if !currentTarget.IsValid() {
		return nil, fmt.Errorf("explicit CRIU INET remap is missing current source pod IP %q", source)
	}
	if currentTarget != target {
		return nil, fmt.Errorf(
			"explicit CRIU INET remap maps current source pod IP %q to %q, not this restore pod IP %q",
			source,
			currentTarget,
			target,
		)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].source.Compare(entries[j].source) < 0
	})
	return entries, nil
}

func parseNativeIPv4(value, field string) (netip.Addr, error) {
	addr, err := netip.ParseAddr(value)
	if err != nil {
		return netip.Addr{}, fmt.Errorf("invalid %s %q: %w", field, value, err)
	}
	if !addr.Is4() {
		return netip.Addr{}, fmt.Errorf("CRIU INET socket remap only supports native IPv4: invalid %s %q", field, value)
	}
	return addr, nil
}
