package criu

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-logr/logr/testr"

	"github.com/ai-dynamo/dynamo/deploy/snapshot/internal/types"
)

func TestConfigureInetRemapWritesMapping(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	t.Setenv(InetRemapEnvVar, "")
	if err := ConfigureInetRemap(m, "10.1.4.21", "", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}

	remapPath := os.Getenv(InetRemapEnvVar)
	if filepath.Dir(remapPath) != workDir {
		t.Fatalf("%s = %q, want file in %q", InetRemapEnvVar, remapPath, workDir)
	}
	if !strings.HasPrefix(filepath.Base(remapPath), "snapshot-inet-remap-") {
		t.Fatalf("%s = %q, want snapshot-inet-remap-* filename", InetRemapEnvVar, remapPath)
	}
	content, err := os.ReadFile(remapPath)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if got, want := string(content), "# generated by Dynamo Snapshot\n10.0.0.11 10.1.4.21\n"; got != want {
		t.Fatalf("remap content = %q, want %q", got, want)
	}
}

func TestConfigureInetRemapBlankExplicitMappingUsesLegacyFallback(t *testing.T) {
	workDir := t.TempDir()
	m := testInetRemapManifest(workDir, "10.0.0.11")

	if err := ConfigureInetRemap(m, "10.1.4.21", " \n\t", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}

	content, err := os.ReadFile(os.Getenv(InetRemapEnvVar))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	want := "# generated by Dynamo Snapshot\n10.0.0.11 10.1.4.21\n"
	if got := string(content); got != want {
		t.Fatalf("remap content = %q, want %q", got, want)
	}
}

func TestConfigureInetRemapWritesExplicitDistributedMapping(t *testing.T) {
	workDir := t.TempDir()
	m := testInetRemapManifest(workDir, "10.0.0.11")

	explicit := " 10.0.0.12\t10.1.4.22 \n\n10.0.0.11 10.1.4.21"
	if err := ConfigureInetRemap(m, "10.1.4.21", explicit, testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}

	content, err := os.ReadFile(os.Getenv(InetRemapEnvVar))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	want := "# generated by Dynamo Snapshot\n10.0.0.11 10.1.4.21\n10.0.0.12 10.1.4.22\n"
	if got := string(content); got != want {
		t.Fatalf("remap content = %q, want %q", got, want)
	}
}

func TestConfigureInetRemapUsesUniqueFiles(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	if err := ConfigureInetRemap(m, "10.1.4.21", "", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap first call: %v", err)
	}
	first := os.Getenv(InetRemapEnvVar)
	if err := ConfigureInetRemap(m, "10.1.4.22", "", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap second call: %v", err)
	}
	second := os.Getenv(InetRemapEnvVar)
	if first == second {
		t.Fatalf("expected unique remap files, both calls used %q", first)
	}
}

func TestConfigureInetRemapSkipsUnchangedIP(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	t.Setenv(InetRemapEnvVar, "stale")
	if err := ConfigureInetRemap(m, "10.0.0.11", "", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}
	if got := os.Getenv(InetRemapEnvVar); got != "" {
		t.Fatalf("%s = %q, want unset", InetRemapEnvVar, got)
	}
	entries, err := os.ReadDir(workDir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	if len(entries) != 0 {
		t.Fatalf("remap file should not exist, entries: %v", entries)
	}
}

func TestConfigureInetRemapRejectsIPv6(t *testing.T) {
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        t.TempDir(),
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "fd00::1",
		},
	}

	err := ConfigureInetRemap(m, "fd00::2", "", testr.New(t))
	if err == nil {
		t.Fatal("expected IPv6 remap to fail")
	}
	if !strings.Contains(err.Error(), "only supports IPv4") {
		t.Fatalf("expected IPv4-only error, got: %v", err)
	}
}

func TestConfigureInetRemapRejectsInvalidExplicitMappings(t *testing.T) {
	tests := []struct {
		name        string
		targetPodIP string
		explicit    string
		wantError   string
	}{
		{
			name:        "one field",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11",
			wantError:   "expected exactly two fields",
		},
		{
			name:        "three fields",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11 10.1.4.21 extra",
			wantError:   "expected exactly two fields",
		},
		{
			name:        "invalid address",
			targetPodIP: "10.1.4.21",
			explicit:    "not-an-ip 10.1.4.21",
			wantError:   "invalid source address",
		},
		{
			name:        "IPv6",
			targetPodIP: "10.1.4.21",
			explicit:    "fd00::1 10.1.4.21",
			wantError:   "only supports native IPv4",
		},
		{
			name:        "target IPv6",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11 fd00::2",
			wantError:   "only supports native IPv4",
		},
		{
			name:        "IPv4-mapped IPv6",
			targetPodIP: "10.1.4.21",
			explicit:    "::ffff:10.0.0.11 10.1.4.21",
			wantError:   "only supports native IPv4",
		},
		{
			name:        "duplicate source",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11 10.1.4.21\n10.0.0.11 10.1.4.22",
			wantError:   "duplicate source address",
		},
		{
			name:        "duplicate target",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11 10.1.4.21\n10.0.0.12 10.1.4.21",
			wantError:   "duplicate target address",
		},
		{
			name:        "missing current source",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.12 10.1.4.22",
			wantError:   "missing current source pod IP",
		},
		{
			name:        "mismatched current target",
			targetPodIP: "10.1.4.21",
			explicit:    "10.0.0.11 10.1.4.22",
			wantError:   "not this restore pod IP",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			m := testInetRemapManifest(t.TempDir(), "10.0.0.11")
			t.Setenv(InetRemapEnvVar, "stale")
			err := ConfigureInetRemap(m, tc.targetPodIP, tc.explicit, testr.New(t))
			if err == nil {
				t.Fatal("expected explicit remap to fail")
			}
			if !strings.Contains(err.Error(), tc.wantError) {
				t.Fatalf("error = %q, want substring %q", err, tc.wantError)
			}
			if got := os.Getenv(InetRemapEnvVar); got != "" {
				t.Fatalf("%s = %q, want unset after validation failure", InetRemapEnvVar, got)
			}
		})
	}
}

func TestConfigureInetRemapSkipsWhenTcpEstablishedDisabled(t *testing.T) {
	m := &types.CheckpointManifest{
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	if err := ConfigureInetRemap(m, "10.1.4.21", "", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}
	if got := os.Getenv(InetRemapEnvVar); got != "" {
		t.Fatalf("%s = %q, want unset", InetRemapEnvVar, got)
	}
}

func TestConfigureInetRemapValidatesExplicitMappingWhenTcpEstablishedDisabled(t *testing.T) {
	m := &types.CheckpointManifest{
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	err := ConfigureInetRemap(m, "10.1.4.21", "malformed", testr.New(t))
	if err == nil || !strings.Contains(err.Error(), "expected exactly two fields") {
		t.Fatalf("expected malformed explicit remap error, got: %v", err)
	}
	if got := os.Getenv(InetRemapEnvVar); got != "" {
		t.Fatalf("%s = %q, want unset", InetRemapEnvVar, got)
	}
}

func testInetRemapManifest(workDir, podIP string) *types.CheckpointManifest {
	return &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: podIP,
		},
	}
}
