# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
Attribution generator for Python/Rust/Go.

Reads the resolver JSON output and emits attribution files that match the
current Dynamo formats.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

SPDX_HEADER = [
    "<!--",
    "SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
    "SPDX-License-Identifier: Apache-2.0",
]

ATTRIBUTIONS_INTRO = [
    "# Third-Party Software Attributions",
    "",
    "This project uses the following third-party libraries. Each library is open-source and licensed under the terms indicated below.",
    "",
    "This file is automatically generated. Please do not edit it directly.",
    "",
]

PYTHON_HEADER = [*SPDX_HEADER, "-->", "", *ATTRIBUTIONS_INTRO]

RUST_HEADER = [*SPDX_HEADER, "-->", "", *ATTRIBUTIONS_INTRO]

GO_HEADER = [
    *SPDX_HEADER,
    "",
    'Licensed under the Apache License, Version 2.0 (the "License");',
    "you may not use this file except in compliance with the License.",
    "You may obtain a copy of the License at",
    "",
    "https://www.apache.org/licenses/LICENSE-2.0",
    "",
    "Unless required by applicable law or agreed to in writing, software",
    'distributed under the License is distributed on an "AS IS" BASIS,',
    "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
    "See the License for the specific language governing permissions and",
    "limitations under the License.",
    "-->",
    "",
    *ATTRIBUTIONS_INTRO,
    "## Dependencies",
    "",
]


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _stringify(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _infer_ecosystem(pkg: dict[str, Any]) -> str:
    ecosystem = _stringify(pkg.get("ecosystem")).strip().lower()
    if ecosystem:
        return ecosystem
    purl = _stringify(pkg.get("purl"))
    if purl.startswith("pkg:"):
        purl_body = purl[4:]
        eco = purl_body.split("/", 1)[0]
        return eco.lower()
    return "unknown"


def _name_from_purl(purl: str) -> tuple[str, str]:
    if not purl.startswith("pkg:"):
        return "", ""
    purl_body = purl[4:]
    purl_body = purl_body.split("?")[0].split("#")[0]
    if "@" in purl_body:
        path_part, version = purl_body.split("@", 1)
    else:
        path_part, version = purl_body, ""
    if "/" in path_part:
        name = path_part.split("/", 1)[1]
    else:
        name = ""
    return name, version


def _package_name(pkg: dict[str, Any]) -> str:
    name = _stringify(pkg.get("name")).strip()
    if name:
        return name
    purl = _stringify(pkg.get("purl"))
    parsed_name, _ = _name_from_purl(purl)
    return parsed_name or "UNKNOWN"


def _package_version(pkg: dict[str, Any]) -> str:
    version = _stringify(pkg.get("version")).strip()
    if version:
        return version
    purl = _stringify(pkg.get("purl"))
    _, parsed_version = _name_from_purl(purl)
    return parsed_version or "UNKNOWN"


def _license_identifier(pkg: dict[str, Any]) -> str:
    for key in (
        "license_expression",
        "license_spdx",
        "license_verified",
        "license_sbom",
        "license_from_sbom",
        "license",
    ):
        value = _stringify(pkg.get(key)).strip()
        if value:
            return value
    return "Unknown"


def _license_text_from_id(
    license_text_id: str, license_texts: dict[str, str]
) -> str | None:
    if not license_text_id:
        return None
    return license_texts.get(license_text_id)


def _license_entry_label(entry: dict[str, Any]) -> str:
    return (
        _stringify(entry.get("license_url")).strip()
        or _stringify(entry.get("license_file")).strip()
        or _stringify(entry.get("license_text_id")).strip()
        or _stringify(entry.get("license_spdx")).strip()
        or _stringify(entry.get("license_expression")).strip()
    )


def _license_entry_text(entry: dict[str, Any], license_texts: dict[str, str]) -> str:
    text = _stringify(entry.get("license_text")).strip("\n")
    if text:
        return text
    text_id = _stringify(entry.get("license_text_id")).strip()
    return _stringify(_license_text_from_id(text_id, license_texts)).strip("\n")


def _license_entries_from_list(
    license_list: list[Any],
    license_texts: dict[str, str],
) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for item in license_list:
        if not isinstance(item, dict):
            continue
        label = _license_entry_label(item)
        text = _license_entry_text(item, license_texts)
        if text:
            entries.append({"label": label, "text": text})
    return entries


def _resolve_license_text_values(
    license_text_values: list[Any],
    license_text_ids: list[Any],
    license_texts: dict[str, str],
) -> list[str]:
    if license_text_values:
        return [text for text in license_text_values if _stringify(text).strip()]
    resolved_values: list[str] = []
    for text_id in license_text_ids:
        resolved = _license_text_from_id(_stringify(text_id), license_texts)
        if resolved:
            resolved_values.append(resolved)
    return resolved_values


def _license_entry_text_at_index(license_text_values: list[Any], idx: int) -> str:
    if idx >= len(license_text_values):
        return ""
    return _stringify(license_text_values[idx]).strip("\n")


def _license_entry_label_at_index(
    license_urls: list[Any],
    license_text_ids: list[Any],
    idx: int,
) -> str:
    if idx < len(license_urls):
        return _stringify(license_urls[idx]).strip()
    if idx < len(license_text_ids):
        return _stringify(license_text_ids[idx]).strip()
    return ""


def _license_entries_from_fields(
    pkg: dict[str, Any],
    license_texts: dict[str, str],
) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    license_urls = [
        u for u in _as_list(pkg.get("license_urls")) if _stringify(u).strip()
    ]
    license_text_ids = [
        i for i in _as_list(pkg.get("license_text_id")) if _stringify(i).strip()
    ]
    license_text_values = _resolve_license_text_values(
        _as_list(pkg.get("license_text")),
        license_text_ids,
        license_texts,
    )

    max_len = max(len(license_urls), len(license_text_ids), len(license_text_values))
    for idx in range(max_len):
        text = _license_entry_text_at_index(license_text_values, idx)
        if not text:
            continue
        label = _license_entry_label_at_index(license_urls, license_text_ids, idx)
        entries.append({"label": label, "text": text})

    return entries


def _build_license_entries(
    pkg: dict[str, Any],
    license_texts: dict[str, str],
) -> list[dict[str, str]]:
    license_list = pkg.get("licenses")
    if isinstance(license_list, list):
        return _license_entries_from_list(license_list, license_texts)

    return _license_entries_from_fields(pkg, license_texts)


def _license_label_from_url(url: str) -> str:
    if not url:
        return ""
    parsed = urlparse(url)
    if not parsed.netloc:
        return url
    path = parsed.path.strip("/")
    segments = path.split("/")
    if "raw.githubusercontent.com" in parsed.netloc and len(segments) >= 4:
        return "/".join(segments[3:])
    if (
        "github.com" in parsed.netloc
        and len(segments) >= 5
        and segments[2] in {"blob", "raw"}
    ):
        return "/".join(segments[4:])
    return segments[-1] if segments[-1] else url


def _python_license_label(entry: dict[str, str], default_label: str) -> str:
    label = _stringify(entry.get("label")).strip()
    if label.startswith("http"):
        derived = _license_label_from_url(label)
        return derived or default_label
    if label:
        return label
    return default_label


def _add_urls_from_list(url_map: dict[str, str], urls_value: list[Any]) -> None:
    for item in urls_value:
        if not isinstance(item, dict):
            continue
        label = _stringify(item.get("label") or item.get("name")).strip()
        url = _stringify(item.get("url")).strip()
        if label and url:
            url_map[label] = url


def _add_urls_from_dict(url_map: dict[str, str], urls_value: dict[str, Any]) -> None:
    for label, url in urls_value.items():
        label = _stringify(label).strip()
        url = _stringify(url).strip()
        if label and url:
            url_map[label] = url


def _add_project_urls(url_map: dict[str, str], project_urls: dict[str, Any]) -> None:
    for label, url in project_urls.items():
        label = _stringify(label).strip()
        url = _stringify(url).strip()
        if label and url:
            url_map.setdefault(label, url)


def _add_homepage_and_repo(
    url_map: dict[str, str], homepage: str, repository: str
) -> None:
    if homepage:
        url_map.setdefault("Homepage", homepage)
    if repository:
        if not any(key in url_map for key in ("Repository", "Source", "Source Code")):
            url_map["Source"] = repository


def _collect_url_entries(pkg: dict[str, Any]) -> list[tuple[str, str]]:
    url_map: dict[str, str] = {}
    urls_value = pkg.get("urls")
    if isinstance(urls_value, list):
        _add_urls_from_list(url_map, urls_value)
    elif isinstance(urls_value, dict):
        _add_urls_from_dict(url_map, urls_value)

    project_urls = pkg.get("project_urls")
    if isinstance(project_urls, dict):
        _add_project_urls(url_map, project_urls)

    homepage = _stringify(pkg.get("homepage")).strip()
    repository = _stringify(pkg.get("repository")).strip()
    _add_homepage_and_repo(url_map, homepage, repository)

    return sorted(url_map.items(), key=lambda item: item[0].lower())


def _write_file(path: Path, lines: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines).rstrip() + "\n"
    path.write_text(content, encoding="utf-8")


def _append_code_block(lines: list[str], text: str) -> None:
    lines.append("```")
    for line in text.splitlines():
        lines.append(line)
    lines.append("```")


def _generate_python(
    packages: list[dict[str, Any]], license_texts: dict[str, str]
) -> list[str]:
    lines = list(PYTHON_HEADER)
    for pkg in sorted(
        packages, key=lambda p: (_package_name(p).lower(), _package_version(p))
    ):
        name = _package_name(pkg)
        version = _package_version(pkg)
        license_id = _license_identifier(pkg)
        license_entries = _build_license_entries(pkg, license_texts)
        url_entries = _collect_url_entries(pkg)

        lines.append(f"## {name} ({version})")
        lines.append("")
        lines.append("### Licenses")
        lines.append(f"License: `{license_id}`")
        lines.append("")

        if license_entries:
            for entry in license_entries:
                label = _python_license_label(entry, "LICENSE")
                lines.append(f"  - `{label}`:")
                _append_code_block(lines, entry["text"])
                lines.append("")

        lines.append("### URLs")
        for label, url in url_entries:
            lines.append(f"  - `{label}`: {url}")
        lines.append("")
        lines.append("")

    return lines


def _generate_rust(
    packages: list[dict[str, Any]], license_texts: dict[str, str]
) -> list[str]:
    lines = list(RUST_HEADER)
    for pkg in sorted(
        packages, key=lambda p: (_package_name(p).lower(), _package_version(p))
    ):
        name = _package_name(pkg)
        version = _package_version(pkg)
        repository = _stringify(
            pkg.get("repository") or pkg.get("homepage") or "None"
        ).strip()
        license_id = _license_identifier(pkg)
        license_entries = _build_license_entries(pkg, license_texts)

        lines.append(f"## {name} - {version}")
        lines.append(f"**Repository URL**: {repository}")
        lines.append(f"**License Type(s)**: {license_id}")

        if license_entries:
            for entry in license_entries:
                label = _stringify(entry.get("label")).strip() or license_id
                lines.append(f"### License: {label}")
                _append_code_block(lines, entry["text"])
                lines.append("")
        else:
            lines.append("")

    return lines


def _generate_go(
    packages: list[dict[str, Any]], license_texts: dict[str, str]
) -> list[str]:
    lines = list(GO_HEADER)
    for pkg in sorted(packages, key=lambda p: _package_name(p).lower()):
        name = _package_name(pkg)
        license_id = _license_identifier(pkg)
        license_entries = _build_license_entries(pkg, license_texts)
        license_text = "\n\n".join(
            entry["text"].rstrip() for entry in license_entries if entry.get("text")
        )
        if not license_text:
            logger.warning("Missing license text for Go module %s", name)

        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"License Identifier: {license_id}")
        lines.append("License Text:")
        _append_code_block(lines, license_text)
        lines.append("")

    return lines
