//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/ai-dynamo/dynamo/deploy/operator/api/v1beta1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configv1alpha1 "sigs.k8s.io/gateway-api-inference-extension/apix/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DynamoCheckpointIdentity)(nil), (*v1beta1.DynamoCheckpointIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoCheckpointIdentity_To_v1beta1_DynamoCheckpointIdentity(a.(*DynamoCheckpointIdentity), b.(*v1beta1.DynamoCheckpointIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoCheckpointIdentity)(nil), (*DynamoCheckpointIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoCheckpointIdentity_To_v1alpha1_DynamoCheckpointIdentity(a.(*v1beta1.DynamoCheckpointIdentity), b.(*DynamoCheckpointIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoComponentDeploymentList)(nil), (*v1beta1.DynamoComponentDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoComponentDeploymentList_To_v1beta1_DynamoComponentDeploymentList(a.(*DynamoComponentDeploymentList), b.(*v1beta1.DynamoComponentDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoComponentDeploymentList)(nil), (*DynamoComponentDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoComponentDeploymentList_To_v1alpha1_DynamoComponentDeploymentList(a.(*v1beta1.DynamoComponentDeploymentList), b.(*DynamoComponentDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoComponentDeploymentSpec)(nil), (*v1beta1.DynamoComponentDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec(a.(*DynamoComponentDeploymentSpec), b.(*v1beta1.DynamoComponentDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoComponentDeploymentSpec)(nil), (*DynamoComponentDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec(a.(*v1beta1.DynamoComponentDeploymentSpec), b.(*DynamoComponentDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentExperimentalSpec)(nil), (*v1beta1.DynamoGraphDeploymentExperimentalSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentExperimentalSpec_To_v1beta1_DynamoGraphDeploymentExperimentalSpec(a.(*DynamoGraphDeploymentExperimentalSpec), b.(*v1beta1.DynamoGraphDeploymentExperimentalSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentExperimentalSpec)(nil), (*DynamoGraphDeploymentExperimentalSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentExperimentalSpec_To_v1alpha1_DynamoGraphDeploymentExperimentalSpec(a.(*v1beta1.DynamoGraphDeploymentExperimentalSpec), b.(*DynamoGraphDeploymentExperimentalSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentList)(nil), (*v1beta1.DynamoGraphDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentList_To_v1beta1_DynamoGraphDeploymentList(a.(*DynamoGraphDeploymentList), b.(*v1beta1.DynamoGraphDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentList)(nil), (*DynamoGraphDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentList_To_v1alpha1_DynamoGraphDeploymentList(a.(*v1beta1.DynamoGraphDeploymentList), b.(*DynamoGraphDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentRequestList)(nil), (*v1beta1.DynamoGraphDeploymentRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentRequestList_To_v1beta1_DynamoGraphDeploymentRequestList(a.(*DynamoGraphDeploymentRequestList), b.(*v1beta1.DynamoGraphDeploymentRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentRequestList)(nil), (*DynamoGraphDeploymentRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentRequestList_To_v1alpha1_DynamoGraphDeploymentRequestList(a.(*v1beta1.DynamoGraphDeploymentRequestList), b.(*DynamoGraphDeploymentRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentScalingAdapter)(nil), (*v1beta1.DynamoGraphDeploymentScalingAdapter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter(a.(*DynamoGraphDeploymentScalingAdapter), b.(*v1beta1.DynamoGraphDeploymentScalingAdapter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentScalingAdapter)(nil), (*DynamoGraphDeploymentScalingAdapter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter(a.(*v1beta1.DynamoGraphDeploymentScalingAdapter), b.(*DynamoGraphDeploymentScalingAdapter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentScalingAdapterList)(nil), (*v1beta1.DynamoGraphDeploymentScalingAdapterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterList_To_v1beta1_DynamoGraphDeploymentScalingAdapterList(a.(*DynamoGraphDeploymentScalingAdapterList), b.(*v1beta1.DynamoGraphDeploymentScalingAdapterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentScalingAdapterList)(nil), (*DynamoGraphDeploymentScalingAdapterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentScalingAdapterList_To_v1alpha1_DynamoGraphDeploymentScalingAdapterList(a.(*v1beta1.DynamoGraphDeploymentScalingAdapterList), b.(*DynamoGraphDeploymentScalingAdapterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentScalingAdapterSpec)(nil), (*v1beta1.DynamoGraphDeploymentScalingAdapterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec(a.(*DynamoGraphDeploymentScalingAdapterSpec), b.(*v1beta1.DynamoGraphDeploymentScalingAdapterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentScalingAdapterSpec)(nil), (*DynamoGraphDeploymentScalingAdapterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec(a.(*v1beta1.DynamoGraphDeploymentScalingAdapterSpec), b.(*DynamoGraphDeploymentScalingAdapterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamoGraphDeploymentScalingAdapterStatus)(nil), (*v1beta1.DynamoGraphDeploymentScalingAdapterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus(a.(*DynamoGraphDeploymentScalingAdapterStatus), b.(*v1beta1.DynamoGraphDeploymentScalingAdapterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DynamoGraphDeploymentScalingAdapterStatus)(nil), (*DynamoGraphDeploymentScalingAdapterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus(a.(*v1beta1.DynamoGraphDeploymentScalingAdapterStatus), b.(*DynamoGraphDeploymentScalingAdapterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EPPConfig)(nil), (*v1beta1.EPPConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EPPConfig_To_v1beta1_EPPConfig(a.(*EPPConfig), b.(*v1beta1.EPPConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EPPConfig)(nil), (*EPPConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EPPConfig_To_v1alpha1_EPPConfig(a.(*v1beta1.EPPConfig), b.(*EPPConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GMSClientPodSpec)(nil), (*v1beta1.GMSClientPodSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GMSClientPodSpec_To_v1beta1_GMSClientPodSpec(a.(*GMSClientPodSpec), b.(*v1beta1.GMSClientPodSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.GMSClientPodSpec)(nil), (*GMSClientPodSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GMSClientPodSpec_To_v1alpha1_GMSClientPodSpec(a.(*v1beta1.GMSClientPodSpec), b.(*GMSClientPodSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KvTransferPolicy)(nil), (*v1beta1.KvTransferPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KvTransferPolicy_To_v1beta1_KvTransferPolicy(a.(*KvTransferPolicy), b.(*v1beta1.KvTransferPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.KvTransferPolicy)(nil), (*KvTransferPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KvTransferPolicy_To_v1alpha1_KvTransferPolicy(a.(*v1beta1.KvTransferPolicy), b.(*KvTransferPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ModelReference)(nil), (*v1beta1.ModelReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ModelReference_To_v1beta1_ModelReference(a.(*ModelReference), b.(*v1beta1.ModelReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ModelReference)(nil), (*ModelReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ModelReference_To_v1alpha1_ModelReference(a.(*v1beta1.ModelReference), b.(*ModelReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MultinodeSpec)(nil), (*v1beta1.MultinodeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MultinodeSpec_To_v1beta1_MultinodeSpec(a.(*MultinodeSpec), b.(*v1beta1.MultinodeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MultinodeSpec)(nil), (*MultinodeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MultinodeSpec_To_v1alpha1_MultinodeSpec(a.(*v1beta1.MultinodeSpec), b.(*MultinodeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Restart)(nil), (*v1beta1.Restart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Restart_To_v1beta1_Restart(a.(*Restart), b.(*v1beta1.Restart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Restart)(nil), (*Restart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Restart_To_v1alpha1_Restart(a.(*v1beta1.Restart), b.(*Restart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RestartStatus)(nil), (*v1beta1.RestartStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RestartStatus_To_v1beta1_RestartStatus(a.(*RestartStatus), b.(*v1beta1.RestartStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RestartStatus)(nil), (*RestartStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RestartStatus_To_v1alpha1_RestartStatus(a.(*v1beta1.RestartStatus), b.(*RestartStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RestartStrategy)(nil), (*v1beta1.RestartStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RestartStrategy_To_v1beta1_RestartStrategy(a.(*RestartStrategy), b.(*v1beta1.RestartStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RestartStrategy)(nil), (*RestartStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RestartStrategy_To_v1alpha1_RestartStrategy(a.(*v1beta1.RestartStrategy), b.(*RestartStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TopologyConstraint)(nil), (*v1beta1.TopologyConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TopologyConstraint_To_v1beta1_TopologyConstraint(a.(*TopologyConstraint), b.(*v1beta1.TopologyConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TopologyConstraint)(nil), (*TopologyConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TopologyConstraint_To_v1alpha1_TopologyConstraint(a.(*v1beta1.TopologyConstraint), b.(*TopologyConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoComponentDeploymentSharedSpec)(nil), (*v1beta1.DynamoComponentDeploymentSharedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoComponentDeploymentSharedSpec_To_v1beta1_DynamoComponentDeploymentSharedSpec(a.(*DynamoComponentDeploymentSharedSpec), b.(*v1beta1.DynamoComponentDeploymentSharedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoComponentDeploymentStatus)(nil), (*v1beta1.DynamoComponentDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoComponentDeploymentStatus_To_v1beta1_DynamoComponentDeploymentStatus(a.(*DynamoComponentDeploymentStatus), b.(*v1beta1.DynamoComponentDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoComponentDeployment)(nil), (*v1beta1.DynamoComponentDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoComponentDeployment_To_v1beta1_DynamoComponentDeployment(a.(*DynamoComponentDeployment), b.(*v1beta1.DynamoComponentDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentRequestSpec)(nil), (*v1beta1.DynamoGraphDeploymentRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentRequestSpec_To_v1beta1_DynamoGraphDeploymentRequestSpec(a.(*DynamoGraphDeploymentRequestSpec), b.(*v1beta1.DynamoGraphDeploymentRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentRequestStatus)(nil), (*v1beta1.DynamoGraphDeploymentRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentRequestStatus_To_v1beta1_DynamoGraphDeploymentRequestStatus(a.(*DynamoGraphDeploymentRequestStatus), b.(*v1beta1.DynamoGraphDeploymentRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentRequest)(nil), (*v1beta1.DynamoGraphDeploymentRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentRequest_To_v1beta1_DynamoGraphDeploymentRequest(a.(*DynamoGraphDeploymentRequest), b.(*v1beta1.DynamoGraphDeploymentRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentServiceRef)(nil), (*v1beta1.DynamoGraphDeploymentComponentRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentServiceRef_To_v1beta1_DynamoGraphDeploymentComponentRef(a.(*DynamoGraphDeploymentServiceRef), b.(*v1beta1.DynamoGraphDeploymentComponentRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentSpec)(nil), (*v1beta1.DynamoGraphDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentSpec_To_v1beta1_DynamoGraphDeploymentSpec(a.(*DynamoGraphDeploymentSpec), b.(*v1beta1.DynamoGraphDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeploymentStatus)(nil), (*v1beta1.DynamoGraphDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeploymentStatus_To_v1beta1_DynamoGraphDeploymentStatus(a.(*DynamoGraphDeploymentStatus), b.(*v1beta1.DynamoGraphDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DynamoGraphDeployment)(nil), (*v1beta1.DynamoGraphDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamoGraphDeployment_To_v1beta1_DynamoGraphDeployment(a.(*DynamoGraphDeployment), b.(*v1beta1.DynamoGraphDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FailoverSpec)(nil), (*v1beta1.FailoverSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FailoverSpec_To_v1beta1_FailoverSpec(a.(*FailoverSpec), b.(*v1beta1.FailoverSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*GPUMemoryServiceSpec)(nil), (*v1beta1.GPUMemoryServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GPUMemoryServiceSpec_To_v1beta1_GPUMemoryServiceSpec(a.(*GPUMemoryServiceSpec), b.(*v1beta1.GPUMemoryServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RollingUpdateStatus)(nil), (*v1beta1.RollingUpdateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RollingUpdateStatus_To_v1beta1_RollingUpdateStatus(a.(*RollingUpdateStatus), b.(*v1beta1.RollingUpdateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ScalingAdapter)(nil), (*v1beta1.ScalingAdapter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScalingAdapter_To_v1beta1_ScalingAdapter(a.(*ScalingAdapter), b.(*v1beta1.ScalingAdapter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ServiceCheckpointConfig)(nil), (*v1beta1.ComponentCheckpointConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceCheckpointConfig_To_v1beta1_ComponentCheckpointConfig(a.(*ServiceCheckpointConfig), b.(*v1beta1.ComponentCheckpointConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ServiceCheckpointStatus)(nil), (*v1beta1.ComponentCheckpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceCheckpointStatus_To_v1beta1_ComponentCheckpointStatus(a.(*ServiceCheckpointStatus), b.(*v1beta1.ComponentCheckpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ServiceReplicaStatus)(nil), (*v1beta1.ComponentReplicaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceReplicaStatus_To_v1beta1_ComponentReplicaStatus(a.(*ServiceReplicaStatus), b.(*v1beta1.ComponentReplicaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*SpecTopologyConstraint)(nil), (*v1beta1.SpecTopologyConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpecTopologyConstraint_To_v1beta1_SpecTopologyConstraint(a.(*SpecTopologyConstraint), b.(*v1beta1.SpecTopologyConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.ComponentCheckpointConfig)(nil), (*ServiceCheckpointConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ComponentCheckpointConfig_To_v1alpha1_ServiceCheckpointConfig(a.(*v1beta1.ComponentCheckpointConfig), b.(*ServiceCheckpointConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.ComponentCheckpointStatus)(nil), (*ServiceCheckpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ComponentCheckpointStatus_To_v1alpha1_ServiceCheckpointStatus(a.(*v1beta1.ComponentCheckpointStatus), b.(*ServiceCheckpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.ComponentReplicaStatus)(nil), (*ServiceReplicaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ComponentReplicaStatus_To_v1alpha1_ServiceReplicaStatus(a.(*v1beta1.ComponentReplicaStatus), b.(*ServiceReplicaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoComponentDeploymentSharedSpec)(nil), (*DynamoComponentDeploymentSharedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoComponentDeploymentSharedSpec_To_v1alpha1_DynamoComponentDeploymentSharedSpec(a.(*v1beta1.DynamoComponentDeploymentSharedSpec), b.(*DynamoComponentDeploymentSharedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoComponentDeploymentStatus)(nil), (*DynamoComponentDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoComponentDeploymentStatus_To_v1alpha1_DynamoComponentDeploymentStatus(a.(*v1beta1.DynamoComponentDeploymentStatus), b.(*DynamoComponentDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoComponentDeployment)(nil), (*DynamoComponentDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoComponentDeployment_To_v1alpha1_DynamoComponentDeployment(a.(*v1beta1.DynamoComponentDeployment), b.(*DynamoComponentDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentComponentRef)(nil), (*DynamoGraphDeploymentServiceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentComponentRef_To_v1alpha1_DynamoGraphDeploymentServiceRef(a.(*v1beta1.DynamoGraphDeploymentComponentRef), b.(*DynamoGraphDeploymentServiceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentRequestSpec)(nil), (*DynamoGraphDeploymentRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentRequestSpec_To_v1alpha1_DynamoGraphDeploymentRequestSpec(a.(*v1beta1.DynamoGraphDeploymentRequestSpec), b.(*DynamoGraphDeploymentRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentRequestStatus)(nil), (*DynamoGraphDeploymentRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentRequestStatus_To_v1alpha1_DynamoGraphDeploymentRequestStatus(a.(*v1beta1.DynamoGraphDeploymentRequestStatus), b.(*DynamoGraphDeploymentRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentRequest)(nil), (*DynamoGraphDeploymentRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentRequest_To_v1alpha1_DynamoGraphDeploymentRequest(a.(*v1beta1.DynamoGraphDeploymentRequest), b.(*DynamoGraphDeploymentRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentSpec)(nil), (*DynamoGraphDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentSpec_To_v1alpha1_DynamoGraphDeploymentSpec(a.(*v1beta1.DynamoGraphDeploymentSpec), b.(*DynamoGraphDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeploymentStatus)(nil), (*DynamoGraphDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeploymentStatus_To_v1alpha1_DynamoGraphDeploymentStatus(a.(*v1beta1.DynamoGraphDeploymentStatus), b.(*DynamoGraphDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.DynamoGraphDeployment)(nil), (*DynamoGraphDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DynamoGraphDeployment_To_v1alpha1_DynamoGraphDeployment(a.(*v1beta1.DynamoGraphDeployment), b.(*DynamoGraphDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.FailoverSpec)(nil), (*FailoverSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FailoverSpec_To_v1alpha1_FailoverSpec(a.(*v1beta1.FailoverSpec), b.(*FailoverSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.GPUMemoryServiceSpec)(nil), (*GPUMemoryServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GPUMemoryServiceSpec_To_v1alpha1_GPUMemoryServiceSpec(a.(*v1beta1.GPUMemoryServiceSpec), b.(*GPUMemoryServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.RollingUpdateStatus)(nil), (*RollingUpdateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpdateStatus_To_v1alpha1_RollingUpdateStatus(a.(*v1beta1.RollingUpdateStatus), b.(*RollingUpdateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.ScalingAdapter)(nil), (*ScalingAdapter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ScalingAdapter_To_v1alpha1_ScalingAdapter(a.(*v1beta1.ScalingAdapter), b.(*ScalingAdapter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.SpecTopologyConstraint)(nil), (*SpecTopologyConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SpecTopologyConstraint_To_v1alpha1_SpecTopologyConstraint(a.(*v1beta1.SpecTopologyConstraint), b.(*SpecTopologyConstraint), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamoCheckpointIdentity_To_v1beta1_DynamoCheckpointIdentity(in *DynamoCheckpointIdentity, out *v1beta1.DynamoCheckpointIdentity, s conversion.Scope) error {
	out.Model = in.Model
	out.BackendFramework = in.BackendFramework
	out.DynamoVersion = in.DynamoVersion
	out.TensorParallelSize = in.TensorParallelSize
	out.PipelineParallelSize = in.PipelineParallelSize
	out.Dtype = in.Dtype
	out.MaxModelLen = in.MaxModelLen
	out.ExtraParameters = *(*map[string]string)(unsafe.Pointer(&in.ExtraParameters))
	return nil
}

// Convert_v1alpha1_DynamoCheckpointIdentity_To_v1beta1_DynamoCheckpointIdentity is an autogenerated conversion function.
func Convert_v1alpha1_DynamoCheckpointIdentity_To_v1beta1_DynamoCheckpointIdentity(in *DynamoCheckpointIdentity, out *v1beta1.DynamoCheckpointIdentity, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoCheckpointIdentity_To_v1beta1_DynamoCheckpointIdentity(in, out, s)
}

func autoConvert_v1beta1_DynamoCheckpointIdentity_To_v1alpha1_DynamoCheckpointIdentity(in *v1beta1.DynamoCheckpointIdentity, out *DynamoCheckpointIdentity, s conversion.Scope) error {
	out.Model = in.Model
	out.BackendFramework = in.BackendFramework
	out.DynamoVersion = in.DynamoVersion
	out.TensorParallelSize = in.TensorParallelSize
	out.PipelineParallelSize = in.PipelineParallelSize
	out.Dtype = in.Dtype
	out.MaxModelLen = in.MaxModelLen
	out.ExtraParameters = *(*map[string]string)(unsafe.Pointer(&in.ExtraParameters))
	return nil
}

// Convert_v1beta1_DynamoCheckpointIdentity_To_v1alpha1_DynamoCheckpointIdentity is an autogenerated conversion function.
func Convert_v1beta1_DynamoCheckpointIdentity_To_v1alpha1_DynamoCheckpointIdentity(in *v1beta1.DynamoCheckpointIdentity, out *DynamoCheckpointIdentity, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoCheckpointIdentity_To_v1alpha1_DynamoCheckpointIdentity(in, out, s)
}

func autoConvert_v1alpha1_DynamoComponentDeployment_To_v1beta1_DynamoComponentDeployment(in *DynamoComponentDeployment, out *v1beta1.DynamoComponentDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DynamoComponentDeploymentStatus_To_v1beta1_DynamoComponentDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_DynamoComponentDeployment_To_v1alpha1_DynamoComponentDeployment(in *v1beta1.DynamoComponentDeployment, out *DynamoComponentDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DynamoComponentDeploymentStatus_To_v1alpha1_DynamoComponentDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamoComponentDeploymentList_To_v1beta1_DynamoComponentDeploymentList(in *DynamoComponentDeploymentList, out *v1beta1.DynamoComponentDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.DynamoComponentDeployment, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_DynamoComponentDeployment_To_v1beta1_DynamoComponentDeployment(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DynamoComponentDeploymentList_To_v1beta1_DynamoComponentDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_DynamoComponentDeploymentList_To_v1beta1_DynamoComponentDeploymentList(in *DynamoComponentDeploymentList, out *v1beta1.DynamoComponentDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoComponentDeploymentList_To_v1beta1_DynamoComponentDeploymentList(in, out, s)
}

func autoConvert_v1beta1_DynamoComponentDeploymentList_To_v1alpha1_DynamoComponentDeploymentList(in *v1beta1.DynamoComponentDeploymentList, out *DynamoComponentDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoComponentDeployment, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_DynamoComponentDeployment_To_v1alpha1_DynamoComponentDeployment(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_DynamoComponentDeploymentList_To_v1alpha1_DynamoComponentDeploymentList is an autogenerated conversion function.
func Convert_v1beta1_DynamoComponentDeploymentList_To_v1alpha1_DynamoComponentDeploymentList(in *v1beta1.DynamoComponentDeploymentList, out *DynamoComponentDeploymentList, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoComponentDeploymentList_To_v1alpha1_DynamoComponentDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_DynamoComponentDeploymentSharedSpec_To_v1beta1_DynamoComponentDeploymentSharedSpec(in *DynamoComponentDeploymentSharedSpec, out *v1beta1.DynamoComponentDeploymentSharedSpec, s conversion.Scope) error {
	// WARNING: in.Annotations requires manual conversion: does not exist in peer-type
	// WARNING: in.Labels requires manual conversion: does not exist in peer-type
	// WARNING: in.ServiceName requires manual conversion: does not exist in peer-type
	out.ComponentType = v1beta1.ComponentType(in.ComponentType)
	// WARNING: in.SubComponentType requires manual conversion: does not exist in peer-type
	// WARNING: in.DynamoNamespace requires manual conversion: does not exist in peer-type
	out.GlobalDynamoNamespace = in.GlobalDynamoNamespace
	// WARNING: in.Resources requires manual conversion: does not exist in peer-type
	// WARNING: in.Autoscaling requires manual conversion: does not exist in peer-type
	// WARNING: in.Envs requires manual conversion: does not exist in peer-type
	// WARNING: in.EnvFromSecret requires manual conversion: does not exist in peer-type
	// WARNING: in.VolumeMounts requires manual conversion: does not exist in peer-type
	// WARNING: in.Ingress requires manual conversion: does not exist in peer-type
	out.ModelRef = (*v1beta1.ModelReference)(unsafe.Pointer(in.ModelRef))
	// WARNING: in.SharedMemory requires manual conversion: does not exist in peer-type
	// WARNING: in.ExtraPodMetadata requires manual conversion: does not exist in peer-type
	// WARNING: in.ExtraPodSpec requires manual conversion: does not exist in peer-type
	// WARNING: in.LivenessProbe requires manual conversion: does not exist in peer-type
	// WARNING: in.ReadinessProbe requires manual conversion: does not exist in peer-type
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinAvailable = (*int32)(unsafe.Pointer(in.MinAvailable))
	out.Multinode = (*v1beta1.MultinodeSpec)(unsafe.Pointer(in.Multinode))
	if in.ScalingAdapter != nil {
		in, out := &in.ScalingAdapter, &out.ScalingAdapter
		*out = new(v1beta1.ScalingAdapter)
		if err := Convert_v1alpha1_ScalingAdapter_To_v1beta1_ScalingAdapter(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.ScalingAdapter = nil
	}
	out.EPPConfig = (*v1beta1.EPPConfig)(unsafe.Pointer(in.EPPConfig))
	// INFO: in.FrontendSidecar opted out of conversion generation
	// WARNING: in.Checkpoint requires manual conversion: does not exist in peer-type
	out.TopologyConstraint = (*v1beta1.TopologyConstraint)(unsafe.Pointer(in.TopologyConstraint))
	// WARNING: in.GPUMemoryService requires manual conversion: does not exist in peer-type
	// WARNING: in.Failover requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_DynamoComponentDeploymentSharedSpec_To_v1alpha1_DynamoComponentDeploymentSharedSpec(in *v1beta1.DynamoComponentDeploymentSharedSpec, out *DynamoComponentDeploymentSharedSpec, s conversion.Scope) error {
	// WARNING: in.ComponentName requires manual conversion: does not exist in peer-type
	out.ComponentType = string(in.ComponentType)
	out.GlobalDynamoNamespace = in.GlobalDynamoNamespace
	// WARNING: in.PodTemplate requires manual conversion: does not exist in peer-type
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinAvailable = (*int32)(unsafe.Pointer(in.MinAvailable))
	out.Multinode = (*MultinodeSpec)(unsafe.Pointer(in.Multinode))
	// WARNING: in.SharedMemorySize requires manual conversion: does not exist in peer-type
	out.ModelRef = (*ModelReference)(unsafe.Pointer(in.ModelRef))
	if in.ScalingAdapter != nil {
		in, out := &in.ScalingAdapter, &out.ScalingAdapter
		*out = new(ScalingAdapter)
		if err := Convert_v1beta1_ScalingAdapter_To_v1alpha1_ScalingAdapter(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.ScalingAdapter = nil
	}
	out.EPPConfig = (*EPPConfig)(unsafe.Pointer(in.EPPConfig))
	// INFO: in.FrontendSidecar opted out of conversion generation
	// WARNING: in.CompilationCache requires manual conversion: does not exist in peer-type
	out.TopologyConstraint = (*TopologyConstraint)(unsafe.Pointer(in.TopologyConstraint))
	// WARNING: in.Experimental requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec(in *DynamoComponentDeploymentSpec, out *v1beta1.DynamoComponentDeploymentSpec, s conversion.Scope) error {
	out.BackendFramework = in.BackendFramework
	if err := Convert_v1alpha1_DynamoComponentDeploymentSharedSpec_To_v1beta1_DynamoComponentDeploymentSharedSpec(&in.DynamoComponentDeploymentSharedSpec, &out.DynamoComponentDeploymentSharedSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec(in *DynamoComponentDeploymentSpec, out *v1beta1.DynamoComponentDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoComponentDeploymentSpec_To_v1beta1_DynamoComponentDeploymentSpec(in, out, s)
}

func autoConvert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec(in *v1beta1.DynamoComponentDeploymentSpec, out *DynamoComponentDeploymentSpec, s conversion.Scope) error {
	out.BackendFramework = in.BackendFramework
	if err := Convert_v1beta1_DynamoComponentDeploymentSharedSpec_To_v1alpha1_DynamoComponentDeploymentSharedSpec(&in.DynamoComponentDeploymentSharedSpec, &out.DynamoComponentDeploymentSharedSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec is an autogenerated conversion function.
func Convert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec(in *v1beta1.DynamoComponentDeploymentSpec, out *DynamoComponentDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoComponentDeploymentSpec_To_v1alpha1_DynamoComponentDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_DynamoComponentDeploymentStatus_To_v1beta1_DynamoComponentDeploymentStatus(in *DynamoComponentDeploymentStatus, out *v1beta1.DynamoComponentDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.PodSelector requires manual conversion: does not exist in peer-type
	// WARNING: in.Service requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_DynamoComponentDeploymentStatus_To_v1alpha1_DynamoComponentDeploymentStatus(in *v1beta1.DynamoComponentDeploymentStatus, out *DynamoComponentDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.Component requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeployment_To_v1beta1_DynamoGraphDeployment(in *DynamoGraphDeployment, out *v1beta1.DynamoGraphDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DynamoGraphDeploymentSpec_To_v1beta1_DynamoGraphDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DynamoGraphDeploymentStatus_To_v1beta1_DynamoGraphDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeployment_To_v1alpha1_DynamoGraphDeployment(in *v1beta1.DynamoGraphDeployment, out *DynamoGraphDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DynamoGraphDeploymentSpec_To_v1alpha1_DynamoGraphDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DynamoGraphDeploymentStatus_To_v1alpha1_DynamoGraphDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeploymentExperimentalSpec_To_v1beta1_DynamoGraphDeploymentExperimentalSpec(in *DynamoGraphDeploymentExperimentalSpec, out *v1beta1.DynamoGraphDeploymentExperimentalSpec, s conversion.Scope) error {
	out.KvTransferPolicy = (*v1beta1.KvTransferPolicy)(unsafe.Pointer(in.KvTransferPolicy))
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentExperimentalSpec_To_v1beta1_DynamoGraphDeploymentExperimentalSpec is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentExperimentalSpec_To_v1beta1_DynamoGraphDeploymentExperimentalSpec(in *DynamoGraphDeploymentExperimentalSpec, out *v1beta1.DynamoGraphDeploymentExperimentalSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentExperimentalSpec_To_v1beta1_DynamoGraphDeploymentExperimentalSpec(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentExperimentalSpec_To_v1alpha1_DynamoGraphDeploymentExperimentalSpec(in *v1beta1.DynamoGraphDeploymentExperimentalSpec, out *DynamoGraphDeploymentExperimentalSpec, s conversion.Scope) error {
	out.KvTransferPolicy = (*KvTransferPolicy)(unsafe.Pointer(in.KvTransferPolicy))
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentExperimentalSpec_To_v1alpha1_DynamoGraphDeploymentExperimentalSpec is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentExperimentalSpec_To_v1alpha1_DynamoGraphDeploymentExperimentalSpec(in *v1beta1.DynamoGraphDeploymentExperimentalSpec, out *DynamoGraphDeploymentExperimentalSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentExperimentalSpec_To_v1alpha1_DynamoGraphDeploymentExperimentalSpec(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentList_To_v1beta1_DynamoGraphDeploymentList(in *DynamoGraphDeploymentList, out *v1beta1.DynamoGraphDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.DynamoGraphDeployment, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_DynamoGraphDeployment_To_v1beta1_DynamoGraphDeployment(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentList_To_v1beta1_DynamoGraphDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentList_To_v1beta1_DynamoGraphDeploymentList(in *DynamoGraphDeploymentList, out *v1beta1.DynamoGraphDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentList_To_v1beta1_DynamoGraphDeploymentList(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentList_To_v1alpha1_DynamoGraphDeploymentList(in *v1beta1.DynamoGraphDeploymentList, out *DynamoGraphDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeployment, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_DynamoGraphDeployment_To_v1alpha1_DynamoGraphDeployment(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentList_To_v1alpha1_DynamoGraphDeploymentList is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentList_To_v1alpha1_DynamoGraphDeploymentList(in *v1beta1.DynamoGraphDeploymentList, out *DynamoGraphDeploymentList, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentList_To_v1alpha1_DynamoGraphDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentRequest_To_v1beta1_DynamoGraphDeploymentRequest(in *DynamoGraphDeploymentRequest, out *v1beta1.DynamoGraphDeploymentRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DynamoGraphDeploymentRequestSpec_To_v1beta1_DynamoGraphDeploymentRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DynamoGraphDeploymentRequestStatus_To_v1beta1_DynamoGraphDeploymentRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeploymentRequest_To_v1alpha1_DynamoGraphDeploymentRequest(in *v1beta1.DynamoGraphDeploymentRequest, out *DynamoGraphDeploymentRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DynamoGraphDeploymentRequestSpec_To_v1alpha1_DynamoGraphDeploymentRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DynamoGraphDeploymentRequestStatus_To_v1alpha1_DynamoGraphDeploymentRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeploymentRequestList_To_v1beta1_DynamoGraphDeploymentRequestList(in *DynamoGraphDeploymentRequestList, out *v1beta1.DynamoGraphDeploymentRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.DynamoGraphDeploymentRequest, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_DynamoGraphDeploymentRequest_To_v1beta1_DynamoGraphDeploymentRequest(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentRequestList_To_v1beta1_DynamoGraphDeploymentRequestList is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentRequestList_To_v1beta1_DynamoGraphDeploymentRequestList(in *DynamoGraphDeploymentRequestList, out *v1beta1.DynamoGraphDeploymentRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentRequestList_To_v1beta1_DynamoGraphDeploymentRequestList(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentRequestList_To_v1alpha1_DynamoGraphDeploymentRequestList(in *v1beta1.DynamoGraphDeploymentRequestList, out *DynamoGraphDeploymentRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeploymentRequest, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_DynamoGraphDeploymentRequest_To_v1alpha1_DynamoGraphDeploymentRequest(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentRequestList_To_v1alpha1_DynamoGraphDeploymentRequestList is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentRequestList_To_v1alpha1_DynamoGraphDeploymentRequestList(in *v1beta1.DynamoGraphDeploymentRequestList, out *DynamoGraphDeploymentRequestList, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentRequestList_To_v1alpha1_DynamoGraphDeploymentRequestList(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentRequestSpec_To_v1beta1_DynamoGraphDeploymentRequestSpec(in *DynamoGraphDeploymentRequestSpec, out *v1beta1.DynamoGraphDeploymentRequestSpec, s conversion.Scope) error {
	out.Model = in.Model
	out.Backend = v1beta1.BackendType(in.Backend)
	// WARNING: in.UseMocker requires manual conversion: does not exist in peer-type
	// WARNING: in.ProfilingConfig requires manual conversion: does not exist in peer-type
	// WARNING: in.EnableGPUDiscovery requires manual conversion: does not exist in peer-type
	if err := v1.Convert_bool_To_Pointer_bool(&in.AutoApply, &out.AutoApply, s); err != nil {
		return err
	}
	// WARNING: in.DeploymentOverrides requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeploymentRequestSpec_To_v1alpha1_DynamoGraphDeploymentRequestSpec(in *v1beta1.DynamoGraphDeploymentRequestSpec, out *DynamoGraphDeploymentRequestSpec, s conversion.Scope) error {
	out.Model = in.Model
	out.Backend = string(in.Backend)
	// WARNING: in.Image requires manual conversion: does not exist in peer-type
	// WARNING: in.ModelCache requires manual conversion: does not exist in peer-type
	// WARNING: in.Hardware requires manual conversion: does not exist in peer-type
	// WARNING: in.Workload requires manual conversion: does not exist in peer-type
	// WARNING: in.SLA requires manual conversion: does not exist in peer-type
	// WARNING: in.Overrides requires manual conversion: does not exist in peer-type
	// WARNING: in.Features requires manual conversion: does not exist in peer-type
	// WARNING: in.SearchStrategy requires manual conversion: does not exist in peer-type
	if err := v1.Convert_Pointer_bool_To_bool(&in.AutoApply, &out.AutoApply, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeploymentRequestStatus_To_v1beta1_DynamoGraphDeploymentRequestStatus(in *DynamoGraphDeploymentRequestStatus, out *v1beta1.DynamoGraphDeploymentRequestStatus, s conversion.Scope) error {
	// WARNING: in.State requires manual conversion: does not exist in peer-type
	// WARNING: in.Backend requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.ProfilingResults requires manual conversion: inconvertible types (string vs *github.com/ai-dynamo/dynamo/deploy/operator/api/v1beta1.ProfilingResultsStatus)
	// WARNING: in.GeneratedDeployment requires manual conversion: does not exist in peer-type
	// WARNING: in.Deployment requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeploymentRequestStatus_To_v1alpha1_DynamoGraphDeploymentRequestStatus(in *v1beta1.DynamoGraphDeploymentRequestStatus, out *DynamoGraphDeploymentRequestStatus, s conversion.Scope) error {
	// WARNING: in.Phase requires manual conversion: does not exist in peer-type
	// WARNING: in.ProfilingPhase requires manual conversion: does not exist in peer-type
	// WARNING: in.DGDName requires manual conversion: does not exist in peer-type
	// WARNING: in.ProfilingJobName requires manual conversion: does not exist in peer-type
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.ProfilingResults requires manual conversion: inconvertible types (*github.com/ai-dynamo/dynamo/deploy/operator/api/v1beta1.ProfilingResultsStatus vs string)
	// WARNING: in.DeploymentInfo requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter(in *DynamoGraphDeploymentScalingAdapter, out *v1beta1.DynamoGraphDeploymentScalingAdapter, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter(in *DynamoGraphDeploymentScalingAdapter, out *v1beta1.DynamoGraphDeploymentScalingAdapter, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter(in *v1beta1.DynamoGraphDeploymentScalingAdapter, out *DynamoGraphDeploymentScalingAdapter, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter(in *v1beta1.DynamoGraphDeploymentScalingAdapter, out *DynamoGraphDeploymentScalingAdapter, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterList_To_v1beta1_DynamoGraphDeploymentScalingAdapterList(in *DynamoGraphDeploymentScalingAdapterList, out *v1beta1.DynamoGraphDeploymentScalingAdapterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.DynamoGraphDeploymentScalingAdapter, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_DynamoGraphDeploymentScalingAdapter_To_v1beta1_DynamoGraphDeploymentScalingAdapter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterList_To_v1beta1_DynamoGraphDeploymentScalingAdapterList is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterList_To_v1beta1_DynamoGraphDeploymentScalingAdapterList(in *DynamoGraphDeploymentScalingAdapterList, out *v1beta1.DynamoGraphDeploymentScalingAdapterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterList_To_v1beta1_DynamoGraphDeploymentScalingAdapterList(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterList_To_v1alpha1_DynamoGraphDeploymentScalingAdapterList(in *v1beta1.DynamoGraphDeploymentScalingAdapterList, out *DynamoGraphDeploymentScalingAdapterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeploymentScalingAdapter, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_DynamoGraphDeploymentScalingAdapter_To_v1alpha1_DynamoGraphDeploymentScalingAdapter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentScalingAdapterList_To_v1alpha1_DynamoGraphDeploymentScalingAdapterList is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentScalingAdapterList_To_v1alpha1_DynamoGraphDeploymentScalingAdapterList(in *v1beta1.DynamoGraphDeploymentScalingAdapterList, out *DynamoGraphDeploymentScalingAdapterList, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterList_To_v1alpha1_DynamoGraphDeploymentScalingAdapterList(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec(in *DynamoGraphDeploymentScalingAdapterSpec, out *v1beta1.DynamoGraphDeploymentScalingAdapterSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	if err := Convert_v1alpha1_DynamoGraphDeploymentServiceRef_To_v1beta1_DynamoGraphDeploymentComponentRef(&in.DGDRef, &out.DGDRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec(in *DynamoGraphDeploymentScalingAdapterSpec, out *v1beta1.DynamoGraphDeploymentScalingAdapterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec_To_v1beta1_DynamoGraphDeploymentScalingAdapterSpec(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec(in *v1beta1.DynamoGraphDeploymentScalingAdapterSpec, out *DynamoGraphDeploymentScalingAdapterSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	if err := Convert_v1beta1_DynamoGraphDeploymentComponentRef_To_v1alpha1_DynamoGraphDeploymentServiceRef(&in.DGDRef, &out.DGDRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec(in *v1beta1.DynamoGraphDeploymentScalingAdapterSpec, out *DynamoGraphDeploymentScalingAdapterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterSpec_To_v1alpha1_DynamoGraphDeploymentScalingAdapterSpec(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus(in *DynamoGraphDeploymentScalingAdapterStatus, out *v1beta1.DynamoGraphDeploymentScalingAdapterStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = in.Selector
	out.LastScaleTime = (*v1.Time)(unsafe.Pointer(in.LastScaleTime))
	return nil
}

// Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus is an autogenerated conversion function.
func Convert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus(in *DynamoGraphDeploymentScalingAdapterStatus, out *v1beta1.DynamoGraphDeploymentScalingAdapterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus_To_v1beta1_DynamoGraphDeploymentScalingAdapterStatus(in, out, s)
}

func autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus(in *v1beta1.DynamoGraphDeploymentScalingAdapterStatus, out *DynamoGraphDeploymentScalingAdapterStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = in.Selector
	out.LastScaleTime = (*v1.Time)(unsafe.Pointer(in.LastScaleTime))
	return nil
}

// Convert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus is an autogenerated conversion function.
func Convert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus(in *v1beta1.DynamoGraphDeploymentScalingAdapterStatus, out *DynamoGraphDeploymentScalingAdapterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DynamoGraphDeploymentScalingAdapterStatus_To_v1alpha1_DynamoGraphDeploymentScalingAdapterStatus(in, out, s)
}

func autoConvert_v1alpha1_DynamoGraphDeploymentSpec_To_v1beta1_DynamoGraphDeploymentSpec(in *DynamoGraphDeploymentSpec, out *v1beta1.DynamoGraphDeploymentSpec, s conversion.Scope) error {
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.PriorityClassName = in.PriorityClassName
	// WARNING: in.PVCs requires manual conversion: does not exist in peer-type
	// WARNING: in.Services requires manual conversion: does not exist in peer-type
	// WARNING: in.Envs requires manual conversion: does not exist in peer-type
	out.BackendFramework = in.BackendFramework
	out.Restart = (*v1beta1.Restart)(unsafe.Pointer(in.Restart))
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(v1beta1.SpecTopologyConstraint)
		if err := Convert_v1alpha1_SpecTopologyConstraint_To_v1beta1_SpecTopologyConstraint(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TopologyConstraint = nil
	}
	out.Experimental = (*v1beta1.DynamoGraphDeploymentExperimentalSpec)(unsafe.Pointer(in.Experimental))
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeploymentSpec_To_v1alpha1_DynamoGraphDeploymentSpec(in *v1beta1.DynamoGraphDeploymentSpec, out *DynamoGraphDeploymentSpec, s conversion.Scope) error {
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.PriorityClassName = in.PriorityClassName
	// WARNING: in.Components requires manual conversion: does not exist in peer-type
	// WARNING: in.Env requires manual conversion: does not exist in peer-type
	out.BackendFramework = in.BackendFramework
	out.Restart = (*Restart)(unsafe.Pointer(in.Restart))
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(SpecTopologyConstraint)
		if err := Convert_v1beta1_SpecTopologyConstraint_To_v1alpha1_SpecTopologyConstraint(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TopologyConstraint = nil
	}
	out.Experimental = (*DynamoGraphDeploymentExperimentalSpec)(unsafe.Pointer(in.Experimental))
	return nil
}

func autoConvert_v1alpha1_DynamoGraphDeploymentStatus_To_v1beta1_DynamoGraphDeploymentStatus(in *DynamoGraphDeploymentStatus, out *v1beta1.DynamoGraphDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.State = v1beta1.DGDState(in.State)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.Services requires manual conversion: does not exist in peer-type
	out.Restart = (*v1beta1.RestartStatus)(unsafe.Pointer(in.Restart))
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make(map[string]v1beta1.ComponentCheckpointStatus, len(*in))
		for key, val := range *in {
			newVal := new(v1beta1.ComponentCheckpointStatus)
			if err := Convert_v1alpha1_ServiceCheckpointStatus_To_v1beta1_ComponentCheckpointStatus(&val, newVal, s); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.Checkpoints = nil
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(v1beta1.RollingUpdateStatus)
		if err := Convert_v1alpha1_RollingUpdateStatus_To_v1beta1_RollingUpdateStatus(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.RollingUpdate = nil
	}
	return nil
}

func autoConvert_v1beta1_DynamoGraphDeploymentStatus_To_v1alpha1_DynamoGraphDeploymentStatus(in *v1beta1.DynamoGraphDeploymentStatus, out *DynamoGraphDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.State = DGDState(in.State)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.Components requires manual conversion: does not exist in peer-type
	out.Restart = (*RestartStatus)(unsafe.Pointer(in.Restart))
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make(map[string]ServiceCheckpointStatus, len(*in))
		for key, val := range *in {
			newVal := new(ServiceCheckpointStatus)
			if err := Convert_v1beta1_ComponentCheckpointStatus_To_v1alpha1_ServiceCheckpointStatus(&val, newVal, s); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.Checkpoints = nil
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateStatus)
		if err := Convert_v1beta1_RollingUpdateStatus_To_v1alpha1_RollingUpdateStatus(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.RollingUpdate = nil
	}
	return nil
}

func autoConvert_v1alpha1_EPPConfig_To_v1beta1_EPPConfig(in *EPPConfig, out *v1beta1.EPPConfig, s conversion.Scope) error {
	out.ConfigMapRef = (*corev1.ConfigMapKeySelector)(unsafe.Pointer(in.ConfigMapRef))
	out.Config = (*configv1alpha1.EndpointPickerConfig)(unsafe.Pointer(in.Config))
	return nil
}

// Convert_v1alpha1_EPPConfig_To_v1beta1_EPPConfig is an autogenerated conversion function.
func Convert_v1alpha1_EPPConfig_To_v1beta1_EPPConfig(in *EPPConfig, out *v1beta1.EPPConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_EPPConfig_To_v1beta1_EPPConfig(in, out, s)
}

func autoConvert_v1beta1_EPPConfig_To_v1alpha1_EPPConfig(in *v1beta1.EPPConfig, out *EPPConfig, s conversion.Scope) error {
	out.ConfigMapRef = (*corev1.ConfigMapKeySelector)(unsafe.Pointer(in.ConfigMapRef))
	out.Config = (*configv1alpha1.EndpointPickerConfig)(unsafe.Pointer(in.Config))
	return nil
}

// Convert_v1beta1_EPPConfig_To_v1alpha1_EPPConfig is an autogenerated conversion function.
func Convert_v1beta1_EPPConfig_To_v1alpha1_EPPConfig(in *v1beta1.EPPConfig, out *EPPConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_EPPConfig_To_v1alpha1_EPPConfig(in, out, s)
}

func autoConvert_v1alpha1_FailoverSpec_To_v1beta1_FailoverSpec(in *FailoverSpec, out *v1beta1.FailoverSpec, s conversion.Scope) error {
	// WARNING: in.Enabled requires manual conversion: does not exist in peer-type
	out.Mode = v1beta1.GPUMemoryServiceMode(in.Mode)
	out.NumShadows = in.NumShadows
	return nil
}

func autoConvert_v1beta1_FailoverSpec_To_v1alpha1_FailoverSpec(in *v1beta1.FailoverSpec, out *FailoverSpec, s conversion.Scope) error {
	out.Mode = GPUMemoryServiceMode(in.Mode)
	out.NumShadows = in.NumShadows
	return nil
}

func autoConvert_v1alpha1_GMSClientPodSpec_To_v1beta1_GMSClientPodSpec(in *GMSClientPodSpec, out *v1beta1.GMSClientPodSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.PodTemplate = in.PodTemplate
	return nil
}

// Convert_v1alpha1_GMSClientPodSpec_To_v1beta1_GMSClientPodSpec is an autogenerated conversion function.
func Convert_v1alpha1_GMSClientPodSpec_To_v1beta1_GMSClientPodSpec(in *GMSClientPodSpec, out *v1beta1.GMSClientPodSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_GMSClientPodSpec_To_v1beta1_GMSClientPodSpec(in, out, s)
}

func autoConvert_v1beta1_GMSClientPodSpec_To_v1alpha1_GMSClientPodSpec(in *v1beta1.GMSClientPodSpec, out *GMSClientPodSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.PodTemplate = in.PodTemplate
	return nil
}

// Convert_v1beta1_GMSClientPodSpec_To_v1alpha1_GMSClientPodSpec is an autogenerated conversion function.
func Convert_v1beta1_GMSClientPodSpec_To_v1alpha1_GMSClientPodSpec(in *v1beta1.GMSClientPodSpec, out *GMSClientPodSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_GMSClientPodSpec_To_v1alpha1_GMSClientPodSpec(in, out, s)
}

func autoConvert_v1alpha1_GPUMemoryServiceSpec_To_v1beta1_GPUMemoryServiceSpec(in *GPUMemoryServiceSpec, out *v1beta1.GPUMemoryServiceSpec, s conversion.Scope) error {
	// WARNING: in.Enabled requires manual conversion: does not exist in peer-type
	out.Mode = v1beta1.GPUMemoryServiceMode(in.Mode)
	out.DeviceClassName = in.DeviceClassName
	out.ExtraClientContainers = *(*[]string)(unsafe.Pointer(&in.ExtraClientContainers))
	out.ExtraClientPods = *(*[]v1beta1.GMSClientPodSpec)(unsafe.Pointer(&in.ExtraClientPods))
	return nil
}

func autoConvert_v1beta1_GPUMemoryServiceSpec_To_v1alpha1_GPUMemoryServiceSpec(in *v1beta1.GPUMemoryServiceSpec, out *GPUMemoryServiceSpec, s conversion.Scope) error {
	out.Mode = GPUMemoryServiceMode(in.Mode)
	out.DeviceClassName = in.DeviceClassName
	out.ExtraClientContainers = *(*[]string)(unsafe.Pointer(&in.ExtraClientContainers))
	out.ExtraClientPods = *(*[]GMSClientPodSpec)(unsafe.Pointer(&in.ExtraClientPods))
	return nil
}

func autoConvert_v1alpha1_KvTransferPolicy_To_v1beta1_KvTransferPolicy(in *KvTransferPolicy, out *v1beta1.KvTransferPolicy, s conversion.Scope) error {
	out.ClusterTopologyName = in.ClusterTopologyName
	out.LabelKey = in.LabelKey
	out.Domain = v1beta1.TopologyDomain(in.Domain)
	out.Enforcement = v1beta1.KvTransferEnforcement(in.Enforcement)
	out.PreferredWeight = (*float32)(unsafe.Pointer(in.PreferredWeight))
	return nil
}

// Convert_v1alpha1_KvTransferPolicy_To_v1beta1_KvTransferPolicy is an autogenerated conversion function.
func Convert_v1alpha1_KvTransferPolicy_To_v1beta1_KvTransferPolicy(in *KvTransferPolicy, out *v1beta1.KvTransferPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KvTransferPolicy_To_v1beta1_KvTransferPolicy(in, out, s)
}

func autoConvert_v1beta1_KvTransferPolicy_To_v1alpha1_KvTransferPolicy(in *v1beta1.KvTransferPolicy, out *KvTransferPolicy, s conversion.Scope) error {
	out.ClusterTopologyName = in.ClusterTopologyName
	out.LabelKey = in.LabelKey
	out.Domain = TopologyDomain(in.Domain)
	out.Enforcement = KvTransferEnforcement(in.Enforcement)
	out.PreferredWeight = (*float32)(unsafe.Pointer(in.PreferredWeight))
	return nil
}

// Convert_v1beta1_KvTransferPolicy_To_v1alpha1_KvTransferPolicy is an autogenerated conversion function.
func Convert_v1beta1_KvTransferPolicy_To_v1alpha1_KvTransferPolicy(in *v1beta1.KvTransferPolicy, out *KvTransferPolicy, s conversion.Scope) error {
	return autoConvert_v1beta1_KvTransferPolicy_To_v1alpha1_KvTransferPolicy(in, out, s)
}

func autoConvert_v1alpha1_ModelReference_To_v1beta1_ModelReference(in *ModelReference, out *v1beta1.ModelReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Revision = in.Revision
	return nil
}

// Convert_v1alpha1_ModelReference_To_v1beta1_ModelReference is an autogenerated conversion function.
func Convert_v1alpha1_ModelReference_To_v1beta1_ModelReference(in *ModelReference, out *v1beta1.ModelReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ModelReference_To_v1beta1_ModelReference(in, out, s)
}

func autoConvert_v1beta1_ModelReference_To_v1alpha1_ModelReference(in *v1beta1.ModelReference, out *ModelReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Revision = in.Revision
	return nil
}

// Convert_v1beta1_ModelReference_To_v1alpha1_ModelReference is an autogenerated conversion function.
func Convert_v1beta1_ModelReference_To_v1alpha1_ModelReference(in *v1beta1.ModelReference, out *ModelReference, s conversion.Scope) error {
	return autoConvert_v1beta1_ModelReference_To_v1alpha1_ModelReference(in, out, s)
}

func autoConvert_v1alpha1_MultinodeSpec_To_v1beta1_MultinodeSpec(in *MultinodeSpec, out *v1beta1.MultinodeSpec, s conversion.Scope) error {
	out.NodeCount = in.NodeCount
	return nil
}

// Convert_v1alpha1_MultinodeSpec_To_v1beta1_MultinodeSpec is an autogenerated conversion function.
func Convert_v1alpha1_MultinodeSpec_To_v1beta1_MultinodeSpec(in *MultinodeSpec, out *v1beta1.MultinodeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MultinodeSpec_To_v1beta1_MultinodeSpec(in, out, s)
}

func autoConvert_v1beta1_MultinodeSpec_To_v1alpha1_MultinodeSpec(in *v1beta1.MultinodeSpec, out *MultinodeSpec, s conversion.Scope) error {
	out.NodeCount = in.NodeCount
	return nil
}

// Convert_v1beta1_MultinodeSpec_To_v1alpha1_MultinodeSpec is an autogenerated conversion function.
func Convert_v1beta1_MultinodeSpec_To_v1alpha1_MultinodeSpec(in *v1beta1.MultinodeSpec, out *MultinodeSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MultinodeSpec_To_v1alpha1_MultinodeSpec(in, out, s)
}

func autoConvert_v1alpha1_Restart_To_v1beta1_Restart(in *Restart, out *v1beta1.Restart, s conversion.Scope) error {
	out.ID = in.ID
	out.Strategy = (*v1beta1.RestartStrategy)(unsafe.Pointer(in.Strategy))
	return nil
}

// Convert_v1alpha1_Restart_To_v1beta1_Restart is an autogenerated conversion function.
func Convert_v1alpha1_Restart_To_v1beta1_Restart(in *Restart, out *v1beta1.Restart, s conversion.Scope) error {
	return autoConvert_v1alpha1_Restart_To_v1beta1_Restart(in, out, s)
}

func autoConvert_v1beta1_Restart_To_v1alpha1_Restart(in *v1beta1.Restart, out *Restart, s conversion.Scope) error {
	out.ID = in.ID
	out.Strategy = (*RestartStrategy)(unsafe.Pointer(in.Strategy))
	return nil
}

// Convert_v1beta1_Restart_To_v1alpha1_Restart is an autogenerated conversion function.
func Convert_v1beta1_Restart_To_v1alpha1_Restart(in *v1beta1.Restart, out *Restart, s conversion.Scope) error {
	return autoConvert_v1beta1_Restart_To_v1alpha1_Restart(in, out, s)
}

func autoConvert_v1alpha1_RestartStatus_To_v1beta1_RestartStatus(in *RestartStatus, out *v1beta1.RestartStatus, s conversion.Scope) error {
	out.ObservedID = in.ObservedID
	out.Phase = v1beta1.RestartPhase(in.Phase)
	out.InProgress = *(*[]string)(unsafe.Pointer(&in.InProgress))
	return nil
}

// Convert_v1alpha1_RestartStatus_To_v1beta1_RestartStatus is an autogenerated conversion function.
func Convert_v1alpha1_RestartStatus_To_v1beta1_RestartStatus(in *RestartStatus, out *v1beta1.RestartStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RestartStatus_To_v1beta1_RestartStatus(in, out, s)
}

func autoConvert_v1beta1_RestartStatus_To_v1alpha1_RestartStatus(in *v1beta1.RestartStatus, out *RestartStatus, s conversion.Scope) error {
	out.ObservedID = in.ObservedID
	out.Phase = RestartPhase(in.Phase)
	out.InProgress = *(*[]string)(unsafe.Pointer(&in.InProgress))
	return nil
}

// Convert_v1beta1_RestartStatus_To_v1alpha1_RestartStatus is an autogenerated conversion function.
func Convert_v1beta1_RestartStatus_To_v1alpha1_RestartStatus(in *v1beta1.RestartStatus, out *RestartStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RestartStatus_To_v1alpha1_RestartStatus(in, out, s)
}

func autoConvert_v1alpha1_RestartStrategy_To_v1beta1_RestartStrategy(in *RestartStrategy, out *v1beta1.RestartStrategy, s conversion.Scope) error {
	out.Type = v1beta1.RestartStrategyType(in.Type)
	out.Order = *(*[]string)(unsafe.Pointer(&in.Order))
	return nil
}

// Convert_v1alpha1_RestartStrategy_To_v1beta1_RestartStrategy is an autogenerated conversion function.
func Convert_v1alpha1_RestartStrategy_To_v1beta1_RestartStrategy(in *RestartStrategy, out *v1beta1.RestartStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_RestartStrategy_To_v1beta1_RestartStrategy(in, out, s)
}

func autoConvert_v1beta1_RestartStrategy_To_v1alpha1_RestartStrategy(in *v1beta1.RestartStrategy, out *RestartStrategy, s conversion.Scope) error {
	out.Type = RestartStrategyType(in.Type)
	out.Order = *(*[]string)(unsafe.Pointer(&in.Order))
	return nil
}

// Convert_v1beta1_RestartStrategy_To_v1alpha1_RestartStrategy is an autogenerated conversion function.
func Convert_v1beta1_RestartStrategy_To_v1alpha1_RestartStrategy(in *v1beta1.RestartStrategy, out *RestartStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RestartStrategy_To_v1alpha1_RestartStrategy(in, out, s)
}

func autoConvert_v1alpha1_RollingUpdateStatus_To_v1beta1_RollingUpdateStatus(in *RollingUpdateStatus, out *v1beta1.RollingUpdateStatus, s conversion.Scope) error {
	out.Phase = v1beta1.RollingUpdatePhase(in.Phase)
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.EndTime = (*v1.Time)(unsafe.Pointer(in.EndTime))
	// WARNING: in.UpdatedServices requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_RollingUpdateStatus_To_v1alpha1_RollingUpdateStatus(in *v1beta1.RollingUpdateStatus, out *RollingUpdateStatus, s conversion.Scope) error {
	out.Phase = RollingUpdatePhase(in.Phase)
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.EndTime = (*v1.Time)(unsafe.Pointer(in.EndTime))
	// WARNING: in.UpdatedComponents requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_ScalingAdapter_To_v1beta1_ScalingAdapter(in *ScalingAdapter, out *v1beta1.ScalingAdapter, s conversion.Scope) error {
	// WARNING: in.Enabled requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_ScalingAdapter_To_v1alpha1_ScalingAdapter(in *v1beta1.ScalingAdapter, out *ScalingAdapter, s conversion.Scope) error {
	return nil
}

func autoConvert_v1alpha1_SpecTopologyConstraint_To_v1beta1_SpecTopologyConstraint(in *SpecTopologyConstraint, out *v1beta1.SpecTopologyConstraint, s conversion.Scope) error {
	// WARNING: in.TopologyProfile requires manual conversion: does not exist in peer-type
	out.PackDomain = v1beta1.TopologyDomain(in.PackDomain)
	return nil
}

func autoConvert_v1beta1_SpecTopologyConstraint_To_v1alpha1_SpecTopologyConstraint(in *v1beta1.SpecTopologyConstraint, out *SpecTopologyConstraint, s conversion.Scope) error {
	// WARNING: in.ClusterTopologyName requires manual conversion: does not exist in peer-type
	out.PackDomain = TopologyDomain(in.PackDomain)
	return nil
}

func autoConvert_v1alpha1_TopologyConstraint_To_v1beta1_TopologyConstraint(in *TopologyConstraint, out *v1beta1.TopologyConstraint, s conversion.Scope) error {
	out.PackDomain = v1beta1.TopologyDomain(in.PackDomain)
	return nil
}

// Convert_v1alpha1_TopologyConstraint_To_v1beta1_TopologyConstraint is an autogenerated conversion function.
func Convert_v1alpha1_TopologyConstraint_To_v1beta1_TopologyConstraint(in *TopologyConstraint, out *v1beta1.TopologyConstraint, s conversion.Scope) error {
	return autoConvert_v1alpha1_TopologyConstraint_To_v1beta1_TopologyConstraint(in, out, s)
}

func autoConvert_v1beta1_TopologyConstraint_To_v1alpha1_TopologyConstraint(in *v1beta1.TopologyConstraint, out *TopologyConstraint, s conversion.Scope) error {
	out.PackDomain = TopologyDomain(in.PackDomain)
	return nil
}

// Convert_v1beta1_TopologyConstraint_To_v1alpha1_TopologyConstraint is an autogenerated conversion function.
func Convert_v1beta1_TopologyConstraint_To_v1alpha1_TopologyConstraint(in *v1beta1.TopologyConstraint, out *TopologyConstraint, s conversion.Scope) error {
	return autoConvert_v1beta1_TopologyConstraint_To_v1alpha1_TopologyConstraint(in, out, s)
}
