// Code generated by capnpc-go. DO NOT EDIT.

package gbuilddeploymentcapnpv1

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	gbuildcommoncapnpv1 "github.com/ai-dynamo/dynamo/deploy/operator/internal/dynamo/lpx/manifest/common/v1"
	strconv "strconv"
)

// Constants defined in gbuild_deployment.capnp.
const (
	CurrentContractRevision = uint32(1)
)

type Deployment capnp.Struct

// Deployment_TypeID is the unique identifier for the type Deployment.
const Deployment_TypeID = 0xc30c331f5220b165

func NewDeployment(s *capnp.Segment) (Deployment, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return Deployment(st), err
}

func NewRootDeployment(s *capnp.Segment) (Deployment, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return Deployment(st), err
}

func ReadRootDeployment(msg *capnp.Message) (Deployment, error) {
	root, err := msg.Root()
	return Deployment(root.Struct()), err
}

func (s Deployment) String() string {
	str, _ := text.Marshal(0xc30c331f5220b165, capnp.Struct(s))
	return str
}

func (s Deployment) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Deployment) DecodeFromPtr(p capnp.Ptr) Deployment {
	return Deployment(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Deployment) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Deployment) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Deployment) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Deployment) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Deployment) ContractRevision() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Deployment) SetContractRevision(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Deployment) Identity() (BuildIdentity, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return BuildIdentity(p.Struct()), err
}

func (s Deployment) HasIdentity() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Deployment) SetIdentity(v BuildIdentity) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewIdentity sets the identity field to a newly
// allocated BuildIdentity struct, preferring placement in s's segment.
func (s Deployment) NewIdentity() (BuildIdentity, error) {
	ss, err := NewBuildIdentity(capnp.Struct(s).Segment())
	if err != nil {
		return BuildIdentity{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Deployment) Config() (DeploymentInfo, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return DeploymentInfo(p.Struct()), err
}

func (s Deployment) HasConfig() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Deployment) SetConfig(v DeploymentInfo) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewConfig sets the config field to a newly
// allocated DeploymentInfo struct, preferring placement in s's segment.
func (s Deployment) NewConfig() (DeploymentInfo, error) {
	ss, err := NewDeploymentInfo(capnp.Struct(s).Segment())
	if err != nil {
		return DeploymentInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Deployment) Partitions() (PartitionDeployment_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return PartitionDeployment_List(p.List()), err
}

func (s Deployment) HasPartitions() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Deployment) SetPartitions(v PartitionDeployment_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewPartitions sets the partitions field to a newly
// allocated PartitionDeployment_List, preferring placement in s's segment.
func (s Deployment) NewPartitions(n int32) (PartitionDeployment_List, error) {
	l, err := NewPartitionDeployment_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PartitionDeployment_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Deployment) RuntimeAssets() (RuntimeAssets, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return RuntimeAssets(p.Struct()), err
}

func (s Deployment) HasRuntimeAssets() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Deployment) SetRuntimeAssets(v RuntimeAssets) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewRuntimeAssets sets the runtimeAssets field to a newly
// allocated RuntimeAssets struct, preferring placement in s's segment.
func (s Deployment) NewRuntimeAssets() (RuntimeAssets, error) {
	ss, err := NewRuntimeAssets(capnp.Struct(s).Segment())
	if err != nil {
		return RuntimeAssets{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Deployment) PartSelect() (PartSelect, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return PartSelect(p.Struct()), err
}

func (s Deployment) HasPartSelect() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Deployment) SetPartSelect(v PartSelect) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewPartSelect sets the partSelect field to a newly
// allocated PartSelect struct, preferring placement in s's segment.
func (s Deployment) NewPartSelect() (PartSelect, error) {
	ss, err := NewPartSelect(capnp.Struct(s).Segment())
	if err != nil {
		return PartSelect{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Deployment) Execution() (gbuildcommoncapnpv1.ContractFile, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return gbuildcommoncapnpv1.ContractFile(p.Struct()), err
}

func (s Deployment) HasExecution() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Deployment) SetExecution(v gbuildcommoncapnpv1.ContractFile) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewExecution sets the execution field to a newly
// allocated gbuildcommoncapnpv1.ContractFile struct, preferring placement in s's segment.
func (s Deployment) NewExecution() (gbuildcommoncapnpv1.ContractFile, error) {
	ss, err := gbuildcommoncapnpv1.NewContractFile(capnp.Struct(s).Segment())
	if err != nil {
		return gbuildcommoncapnpv1.ContractFile{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Deployment) Checkpoint() (CheckpointReference, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return CheckpointReference(p.Struct()), err
}

func (s Deployment) HasCheckpoint() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Deployment) SetCheckpoint(v CheckpointReference) error {
	return capnp.Struct(s).SetPtr(6, capnp.Struct(v).ToPtr())
}

// NewCheckpoint sets the checkpoint field to a newly
// allocated CheckpointReference struct, preferring placement in s's segment.
func (s Deployment) NewCheckpoint() (CheckpointReference, error) {
	ss, err := NewCheckpointReference(capnp.Struct(s).Segment())
	if err != nil {
		return CheckpointReference{}, err
	}
	err = capnp.Struct(s).SetPtr(6, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Deployment_List is a list of Deployment.
type Deployment_List = capnp.StructList[Deployment]

// NewDeployment creates a new list of Deployment.
func NewDeployment_List(s *capnp.Segment, sz int32) (Deployment_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7}, sz)
	return capnp.StructList[Deployment](l), err
}

// Deployment_Future is a wrapper for a Deployment promised by a client call.
type Deployment_Future struct{ *capnp.Future }

func (f Deployment_Future) Struct() (Deployment, error) {
	p, err := f.Future.Ptr()
	return Deployment(p.Struct()), err
}
func (p Deployment_Future) Identity() BuildIdentity_Future {
	return BuildIdentity_Future{Future: p.Future.Field(0, nil)}
}
func (p Deployment_Future) Config() DeploymentInfo_Future {
	return DeploymentInfo_Future{Future: p.Future.Field(1, nil)}
}
func (p Deployment_Future) RuntimeAssets() RuntimeAssets_Future {
	return RuntimeAssets_Future{Future: p.Future.Field(3, nil)}
}
func (p Deployment_Future) PartSelect() PartSelect_Future {
	return PartSelect_Future{Future: p.Future.Field(4, nil)}
}
func (p Deployment_Future) Execution() gbuildcommoncapnpv1.ContractFile_Future {
	return gbuildcommoncapnpv1.ContractFile_Future{Future: p.Future.Field(5, nil)}
}
func (p Deployment_Future) Checkpoint() CheckpointReference_Future {
	return CheckpointReference_Future{Future: p.Future.Field(6, nil)}
}

type CheckpointReference capnp.Struct

// CheckpointReference_TypeID is the unique identifier for the type CheckpointReference.
const CheckpointReference_TypeID = 0x9f7927e8c4254eb7

func NewCheckpointReference(s *capnp.Segment) (CheckpointReference, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CheckpointReference(st), err
}

func NewRootCheckpointReference(s *capnp.Segment) (CheckpointReference, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CheckpointReference(st), err
}

func ReadRootCheckpointReference(msg *capnp.Message) (CheckpointReference, error) {
	root, err := msg.Root()
	return CheckpointReference(root.Struct()), err
}

func (s CheckpointReference) String() string {
	str, _ := text.Marshal(0x9f7927e8c4254eb7, capnp.Struct(s))
	return str
}

func (s CheckpointReference) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CheckpointReference) DecodeFromPtr(p capnp.Ptr) CheckpointReference {
	return CheckpointReference(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CheckpointReference) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CheckpointReference) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CheckpointReference) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CheckpointReference) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CheckpointReference) Provider() CheckpointProvider {
	return CheckpointProvider(capnp.Struct(s).Uint16(0))
}

func (s CheckpointReference) SetProvider(v CheckpointProvider) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s CheckpointReference) Model() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CheckpointReference) HasModel() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CheckpointReference) ModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CheckpointReference) SetModel(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CheckpointReference) Revision() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CheckpointReference) HasRevision() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CheckpointReference) RevisionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CheckpointReference) SetRevision(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CheckpointReference_List is a list of CheckpointReference.
type CheckpointReference_List = capnp.StructList[CheckpointReference]

// NewCheckpointReference creates a new list of CheckpointReference.
func NewCheckpointReference_List(s *capnp.Segment, sz int32) (CheckpointReference_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[CheckpointReference](l), err
}

// CheckpointReference_Future is a wrapper for a CheckpointReference promised by a client call.
type CheckpointReference_Future struct{ *capnp.Future }

func (f CheckpointReference_Future) Struct() (CheckpointReference, error) {
	p, err := f.Future.Ptr()
	return CheckpointReference(p.Struct()), err
}

type CheckpointProvider uint16

// CheckpointProvider_TypeID is the unique identifier for the type CheckpointProvider.
const CheckpointProvider_TypeID = 0xf1b5dc23024302bd

// Values of CheckpointProvider.
const (
	CheckpointProvider_huggingface CheckpointProvider = 0
)

// String returns the enum's constant name.
func (c CheckpointProvider) String() string {
	switch c {
	case CheckpointProvider_huggingface:
		return "huggingface"

	default:
		return ""
	}
}

// CheckpointProviderFromString returns the enum value with a name,
// or the zero value if there's no such value.
func CheckpointProviderFromString(c string) CheckpointProvider {
	switch c {
	case "huggingface":
		return CheckpointProvider_huggingface

	default:
		return 0
	}
}

type CheckpointProvider_List = capnp.EnumList[CheckpointProvider]

func NewCheckpointProvider_List(s *capnp.Segment, sz int32) (CheckpointProvider_List, error) {
	return capnp.NewEnumList[CheckpointProvider](s, sz)
}

type BuildIdentity capnp.Struct

// BuildIdentity_TypeID is the unique identifier for the type BuildIdentity.
const BuildIdentity_TypeID = 0xd0e7ed3ef51f57f9

func NewBuildIdentity(s *capnp.Segment) (BuildIdentity, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BuildIdentity(st), err
}

func NewRootBuildIdentity(s *capnp.Segment) (BuildIdentity, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BuildIdentity(st), err
}

func ReadRootBuildIdentity(msg *capnp.Message) (BuildIdentity, error) {
	root, err := msg.Root()
	return BuildIdentity(root.Struct()), err
}

func (s BuildIdentity) String() string {
	str, _ := text.Marshal(0xd0e7ed3ef51f57f9, capnp.Struct(s))
	return str
}

func (s BuildIdentity) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BuildIdentity) DecodeFromPtr(p capnp.Ptr) BuildIdentity {
	return BuildIdentity(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BuildIdentity) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BuildIdentity) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BuildIdentity) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BuildIdentity) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BuildIdentity) BuildId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BuildIdentity) HasBuildId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BuildIdentity) BuildIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BuildIdentity) SetBuildId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// BuildIdentity_List is a list of BuildIdentity.
type BuildIdentity_List = capnp.StructList[BuildIdentity]

// NewBuildIdentity creates a new list of BuildIdentity.
func NewBuildIdentity_List(s *capnp.Segment, sz int32) (BuildIdentity_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[BuildIdentity](l), err
}

// BuildIdentity_Future is a wrapper for a BuildIdentity promised by a client call.
type BuildIdentity_Future struct{ *capnp.Future }

func (f BuildIdentity_Future) Struct() (BuildIdentity, error) {
	p, err := f.Future.Ptr()
	return BuildIdentity(p.Struct()), err
}

type PartitionDeployment capnp.Struct
type PartitionDeployment_detail PartitionDeployment
type PartitionDeployment_detail_Which uint16

const (
	PartitionDeployment_detail_Which_lpu  PartitionDeployment_detail_Which = 0
	PartitionDeployment_detail_Which_cuda PartitionDeployment_detail_Which = 1
	PartitionDeployment_detail_Which_cpu  PartitionDeployment_detail_Which = 2
)

func (w PartitionDeployment_detail_Which) String() string {
	const s = "lpucudacpu"
	switch w {
	case PartitionDeployment_detail_Which_lpu:
		return s[0:3]
	case PartitionDeployment_detail_Which_cuda:
		return s[3:7]
	case PartitionDeployment_detail_Which_cpu:
		return s[7:10]

	}
	return "PartitionDeployment_detail_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// PartitionDeployment_TypeID is the unique identifier for the type PartitionDeployment.
const PartitionDeployment_TypeID = 0xe7a32b525b91f7a0

func NewPartitionDeployment(s *capnp.Segment) (PartitionDeployment, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return PartitionDeployment(st), err
}

func NewRootPartitionDeployment(s *capnp.Segment) (PartitionDeployment, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return PartitionDeployment(st), err
}

func ReadRootPartitionDeployment(msg *capnp.Message) (PartitionDeployment, error) {
	root, err := msg.Root()
	return PartitionDeployment(root.Struct()), err
}

func (s PartitionDeployment) String() string {
	str, _ := text.Marshal(0xe7a32b525b91f7a0, capnp.Struct(s))
	return str
}

func (s PartitionDeployment) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PartitionDeployment) DecodeFromPtr(p capnp.Ptr) PartitionDeployment {
	return PartitionDeployment(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PartitionDeployment) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PartitionDeployment) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartitionDeployment) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartitionDeployment) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartitionDeployment) Partition() (gbuildcommoncapnpv1.PartitionRef, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return gbuildcommoncapnpv1.PartitionRef(p.Struct()), err
}

func (s PartitionDeployment) HasPartition() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PartitionDeployment) SetPartition(v gbuildcommoncapnpv1.PartitionRef) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPartition sets the partition field to a newly
// allocated gbuildcommoncapnpv1.PartitionRef struct, preferring placement in s's segment.
func (s PartitionDeployment) NewPartition() (gbuildcommoncapnpv1.PartitionRef, error) {
	ss, err := gbuildcommoncapnpv1.NewPartitionRef(capnp.Struct(s).Segment())
	if err != nil {
		return gbuildcommoncapnpv1.PartitionRef{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionDeployment) Detail() PartitionDeployment_detail {
	return PartitionDeployment_detail(s)
}

func (s PartitionDeployment_detail) Which() PartitionDeployment_detail_Which {
	return PartitionDeployment_detail_Which(capnp.Struct(s).Uint16(0))
}
func (s PartitionDeployment_detail) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartitionDeployment_detail) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartitionDeployment_detail) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartitionDeployment_detail) Lpu() (LpuPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != lpu")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return LpuPartitionArtifact(p.Struct()), err
}

func (s PartitionDeployment_detail) HasLpu() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s PartitionDeployment_detail) SetLpu(v LpuPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewLpu sets the lpu field to a newly
// allocated LpuPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionDeployment_detail) NewLpu() (LpuPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewLpuPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return LpuPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionDeployment_detail) Cuda() (CudaPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != cuda")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return CudaPartitionArtifact(p.Struct()), err
}

func (s PartitionDeployment_detail) HasCuda() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s PartitionDeployment_detail) SetCuda(v CudaPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewCuda sets the cuda field to a newly
// allocated CudaPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionDeployment_detail) NewCuda() (CudaPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewCudaPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return CudaPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionDeployment_detail) Cpu() (CpuPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != cpu")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return CpuPartitionArtifact(p.Struct()), err
}

func (s PartitionDeployment_detail) HasCpu() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s PartitionDeployment_detail) SetCpu(v CpuPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewCpu sets the cpu field to a newly
// allocated CpuPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionDeployment_detail) NewCpu() (CpuPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewCpuPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return CpuPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PartitionDeployment_List is a list of PartitionDeployment.
type PartitionDeployment_List = capnp.StructList[PartitionDeployment]

// NewPartitionDeployment creates a new list of PartitionDeployment.
func NewPartitionDeployment_List(s *capnp.Segment, sz int32) (PartitionDeployment_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[PartitionDeployment](l), err
}

// PartitionDeployment_Future is a wrapper for a PartitionDeployment promised by a client call.
type PartitionDeployment_Future struct{ *capnp.Future }

func (f PartitionDeployment_Future) Struct() (PartitionDeployment, error) {
	p, err := f.Future.Ptr()
	return PartitionDeployment(p.Struct()), err
}
func (p PartitionDeployment_Future) Partition() gbuildcommoncapnpv1.PartitionRef_Future {
	return gbuildcommoncapnpv1.PartitionRef_Future{Future: p.Future.Field(0, nil)}
}
func (p PartitionDeployment_Future) Detail() PartitionDeployment_detail_Future {
	return PartitionDeployment_detail_Future{p.Future}
}

// PartitionDeployment_detail_Future is a wrapper for a PartitionDeployment_detail promised by a client call.
type PartitionDeployment_detail_Future struct{ *capnp.Future }

func (f PartitionDeployment_detail_Future) Struct() (PartitionDeployment_detail, error) {
	p, err := f.Future.Ptr()
	return PartitionDeployment_detail(p.Struct()), err
}
func (p PartitionDeployment_detail_Future) Lpu() LpuPartitionArtifact_Future {
	return LpuPartitionArtifact_Future{Future: p.Future.Field(1, nil)}
}
func (p PartitionDeployment_detail_Future) Cuda() CudaPartitionArtifact_Future {
	return CudaPartitionArtifact_Future{Future: p.Future.Field(1, nil)}
}
func (p PartitionDeployment_detail_Future) Cpu() CpuPartitionArtifact_Future {
	return CpuPartitionArtifact_Future{Future: p.Future.Field(1, nil)}
}

type DeploymentInfo capnp.Struct

// DeploymentInfo_TypeID is the unique identifier for the type DeploymentInfo.
const DeploymentInfo_TypeID = 0xfd3ce92fb33e4ab2

func NewDeploymentInfo(s *capnp.Segment) (DeploymentInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return DeploymentInfo(st), err
}

func NewRootDeploymentInfo(s *capnp.Segment) (DeploymentInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return DeploymentInfo(st), err
}

func ReadRootDeploymentInfo(msg *capnp.Message) (DeploymentInfo, error) {
	root, err := msg.Root()
	return DeploymentInfo(root.Struct()), err
}

func (s DeploymentInfo) String() string {
	str, _ := text.Marshal(0xfd3ce92fb33e4ab2, capnp.Struct(s))
	return str
}

func (s DeploymentInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DeploymentInfo) DecodeFromPtr(p capnp.Ptr) DeploymentInfo {
	return DeploymentInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DeploymentInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DeploymentInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DeploymentInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DeploymentInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DeploymentInfo) CompilationMode() CompilationMode {
	return CompilationMode(capnp.Struct(s).Uint16(0))
}

func (s DeploymentInfo) SetCompilationMode(v CompilationMode) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s DeploymentInfo) NumLpuNodes() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s DeploymentInfo) SetNumLpuNodes(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s DeploymentInfo) TotalNumStages() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s DeploymentInfo) SetTotalNumStages(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s DeploymentInfo) Program() (ProgramConfig, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ProgramConfig(p.Struct()), err
}

func (s DeploymentInfo) HasProgram() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DeploymentInfo) SetProgram(v ProgramConfig) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewProgram sets the program field to a newly
// allocated ProgramConfig struct, preferring placement in s's segment.
func (s DeploymentInfo) NewProgram() (ProgramConfig, error) {
	ss, err := NewProgramConfig(capnp.Struct(s).Segment())
	if err != nil {
		return ProgramConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DeploymentInfo) SelectedPropSyncChains() (PropSyncChain_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PropSyncChain_List(p.List()), err
}

func (s DeploymentInfo) HasSelectedPropSyncChains() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DeploymentInfo) SetSelectedPropSyncChains(v PropSyncChain_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewSelectedPropSyncChains sets the selectedPropSyncChains field to a newly
// allocated PropSyncChain_List, preferring placement in s's segment.
func (s DeploymentInfo) NewSelectedPropSyncChains(n int32) (PropSyncChain_List, error) {
	l, err := NewPropSyncChain_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PropSyncChain_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s DeploymentInfo) RuntimeIo() (RuntimeIoConfig, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return RuntimeIoConfig(p.Struct()), err
}

func (s DeploymentInfo) HasRuntimeIo() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s DeploymentInfo) SetRuntimeIo(v RuntimeIoConfig) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewRuntimeIo sets the runtimeIo field to a newly
// allocated RuntimeIoConfig struct, preferring placement in s's segment.
func (s DeploymentInfo) NewRuntimeIo() (RuntimeIoConfig, error) {
	ss, err := NewRuntimeIoConfig(capnp.Struct(s).Segment())
	if err != nil {
		return RuntimeIoConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// DeploymentInfo_List is a list of DeploymentInfo.
type DeploymentInfo_List = capnp.StructList[DeploymentInfo]

// NewDeploymentInfo creates a new list of DeploymentInfo.
func NewDeploymentInfo_List(s *capnp.Segment, sz int32) (DeploymentInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[DeploymentInfo](l), err
}

// DeploymentInfo_Future is a wrapper for a DeploymentInfo promised by a client call.
type DeploymentInfo_Future struct{ *capnp.Future }

func (f DeploymentInfo_Future) Struct() (DeploymentInfo, error) {
	p, err := f.Future.Ptr()
	return DeploymentInfo(p.Struct()), err
}
func (p DeploymentInfo_Future) Program() ProgramConfig_Future {
	return ProgramConfig_Future{Future: p.Future.Field(0, nil)}
}
func (p DeploymentInfo_Future) RuntimeIo() RuntimeIoConfig_Future {
	return RuntimeIoConfig_Future{Future: p.Future.Field(2, nil)}
}

type CompilationMode uint16

// CompilationMode_TypeID is the unique identifier for the type CompilationMode.
const CompilationMode_TypeID = 0xf1daf8c2e796a17e

// Values of CompilationMode.
const (
	CompilationMode_lpuOnly CompilationMode = 0
	CompilationMode_lpx     CompilationMode = 1
)

// String returns the enum's constant name.
func (c CompilationMode) String() string {
	switch c {
	case CompilationMode_lpuOnly:
		return "lpuOnly"
	case CompilationMode_lpx:
		return "lpx"

	default:
		return ""
	}
}

// CompilationModeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func CompilationModeFromString(c string) CompilationMode {
	switch c {
	case "lpuOnly":
		return CompilationMode_lpuOnly
	case "lpx":
		return CompilationMode_lpx

	default:
		return 0
	}
}

type CompilationMode_List = capnp.EnumList[CompilationMode]

func NewCompilationMode_List(s *capnp.Segment, sz int32) (CompilationMode_List, error) {
	return capnp.NewEnumList[CompilationMode](s, sz)
}

type ProgramConfig capnp.Struct

// ProgramConfig_TypeID is the unique identifier for the type ProgramConfig.
const ProgramConfig_TypeID = 0xe13c796825aca58b

func NewProgramConfig(s *capnp.Segment) (ProgramConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ProgramConfig(st), err
}

func NewRootProgramConfig(s *capnp.Segment) (ProgramConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ProgramConfig(st), err
}

func ReadRootProgramConfig(msg *capnp.Message) (ProgramConfig, error) {
	root, err := msg.Root()
	return ProgramConfig(root.Struct()), err
}

func (s ProgramConfig) String() string {
	str, _ := text.Marshal(0xe13c796825aca58b, capnp.Struct(s))
	return str
}

func (s ProgramConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProgramConfig) DecodeFromPtr(p capnp.Ptr) ProgramConfig {
	return ProgramConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProgramConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProgramConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProgramConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProgramConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProgramConfig) ProgramName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProgramConfig) HasProgramName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProgramConfig) ProgramNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProgramConfig) SetProgramName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProgramConfig) PackageName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProgramConfig) HasPackageName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProgramConfig) PackageNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProgramConfig) SetPackageName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ProgramConfig) BatchSize() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ProgramConfig) SetBatchSize(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ProgramConfig) SupportsCpuEmbeddings() bool {
	return capnp.Struct(s).Bit(32)
}

func (s ProgramConfig) SetSupportsCpuEmbeddings(v bool) {
	capnp.Struct(s).SetBit(32, v)
}

func (s ProgramConfig) StandaloneTokenEmbeddings() bool {
	return capnp.Struct(s).Bit(33)
}

func (s ProgramConfig) SetStandaloneTokenEmbeddings(v bool) {
	capnp.Struct(s).SetBit(33, v)
}

// ProgramConfig_List is a list of ProgramConfig.
type ProgramConfig_List = capnp.StructList[ProgramConfig]

// NewProgramConfig creates a new list of ProgramConfig.
func NewProgramConfig_List(s *capnp.Segment, sz int32) (ProgramConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[ProgramConfig](l), err
}

// ProgramConfig_Future is a wrapper for a ProgramConfig promised by a client call.
type ProgramConfig_Future struct{ *capnp.Future }

func (f ProgramConfig_Future) Struct() (ProgramConfig, error) {
	p, err := f.Future.Ptr()
	return ProgramConfig(p.Struct()), err
}

type PropSyncChain capnp.Struct

// PropSyncChain_TypeID is the unique identifier for the type PropSyncChain.
const PropSyncChain_TypeID = 0x8a2b4a1188f3156d

func NewPropSyncChain(s *capnp.Segment) (PropSyncChain, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PropSyncChain(st), err
}

func NewRootPropSyncChain(s *capnp.Segment) (PropSyncChain, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PropSyncChain(st), err
}

func ReadRootPropSyncChain(msg *capnp.Message) (PropSyncChain, error) {
	root, err := msg.Root()
	return PropSyncChain(root.Struct()), err
}

func (s PropSyncChain) String() string {
	str, _ := text.Marshal(0x8a2b4a1188f3156d, capnp.Struct(s))
	return str
}

func (s PropSyncChain) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PropSyncChain) DecodeFromPtr(p capnp.Ptr) PropSyncChain {
	return PropSyncChain(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PropSyncChain) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PropSyncChain) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PropSyncChain) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PropSyncChain) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PropSyncChain) PartitionIds() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.UInt32List(p.List()), err
}

func (s PropSyncChain) HasPartitionIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PropSyncChain) SetPartitionIds(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPartitionIds sets the partitionIds field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s PropSyncChain) NewPartitionIds(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// PropSyncChain_List is a list of PropSyncChain.
type PropSyncChain_List = capnp.StructList[PropSyncChain]

// NewPropSyncChain creates a new list of PropSyncChain.
func NewPropSyncChain_List(s *capnp.Segment, sz int32) (PropSyncChain_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PropSyncChain](l), err
}

// PropSyncChain_Future is a wrapper for a PropSyncChain promised by a client call.
type PropSyncChain_Future struct{ *capnp.Future }

func (f PropSyncChain_Future) Struct() (PropSyncChain, error) {
	p, err := f.Future.Ptr()
	return PropSyncChain(p.Struct()), err
}

type RuntimeIoConfig capnp.Struct

// RuntimeIoConfig_TypeID is the unique identifier for the type RuntimeIoConfig.
const RuntimeIoConfig_TypeID = 0xd2da7d280c347740

func NewRuntimeIoConfig(s *capnp.Segment) (RuntimeIoConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return RuntimeIoConfig(st), err
}

func NewRootRuntimeIoConfig(s *capnp.Segment) (RuntimeIoConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return RuntimeIoConfig(st), err
}

func ReadRootRuntimeIoConfig(msg *capnp.Message) (RuntimeIoConfig, error) {
	root, err := msg.Root()
	return RuntimeIoConfig(root.Struct()), err
}

func (s RuntimeIoConfig) String() string {
	str, _ := text.Marshal(0xd2da7d280c347740, capnp.Struct(s))
	return str
}

func (s RuntimeIoConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RuntimeIoConfig) DecodeFromPtr(p capnp.Ptr) RuntimeIoConfig {
	return RuntimeIoConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RuntimeIoConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RuntimeIoConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RuntimeIoConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RuntimeIoConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RuntimeIoConfig) Protocol() RuntimeIoProtocol {
	return RuntimeIoProtocol(capnp.Struct(s).Uint16(0))
}

func (s RuntimeIoConfig) SetProtocol(v RuntimeIoProtocol) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s RuntimeIoConfig) FpgaMode() FpgaIoMode {
	return FpgaIoMode(capnp.Struct(s).Uint16(2))
}

func (s RuntimeIoConfig) SetFpgaMode(v FpgaIoMode) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s RuntimeIoConfig) IoFpgaCount() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s RuntimeIoConfig) SetIoFpgaCount(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s RuntimeIoConfig) FanoutFactor() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s RuntimeIoConfig) SetFanoutFactor(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// RuntimeIoConfig_List is a list of RuntimeIoConfig.
type RuntimeIoConfig_List = capnp.StructList[RuntimeIoConfig]

// NewRuntimeIoConfig creates a new list of RuntimeIoConfig.
func NewRuntimeIoConfig_List(s *capnp.Segment, sz int32) (RuntimeIoConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[RuntimeIoConfig](l), err
}

// RuntimeIoConfig_Future is a wrapper for a RuntimeIoConfig promised by a client call.
type RuntimeIoConfig_Future struct{ *capnp.Future }

func (f RuntimeIoConfig_Future) Struct() (RuntimeIoConfig, error) {
	p, err := f.Future.Ptr()
	return RuntimeIoConfig(p.Struct()), err
}

type RuntimeIoProtocol uint16

// RuntimeIoProtocol_TypeID is the unique identifier for the type RuntimeIoProtocol.
const RuntimeIoProtocol_TypeID = 0xf82da21791d930d0

// Values of RuntimeIoProtocol.
const (
	RuntimeIoProtocol_host     RuntimeIoProtocol = 0
	RuntimeIoProtocol_fpgaRoce RuntimeIoProtocol = 1
)

// String returns the enum's constant name.
func (c RuntimeIoProtocol) String() string {
	switch c {
	case RuntimeIoProtocol_host:
		return "host"
	case RuntimeIoProtocol_fpgaRoce:
		return "fpgaRoce"

	default:
		return ""
	}
}

// RuntimeIoProtocolFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RuntimeIoProtocolFromString(c string) RuntimeIoProtocol {
	switch c {
	case "host":
		return RuntimeIoProtocol_host
	case "fpgaRoce":
		return RuntimeIoProtocol_fpgaRoce

	default:
		return 0
	}
}

type RuntimeIoProtocol_List = capnp.EnumList[RuntimeIoProtocol]

func NewRuntimeIoProtocol_List(s *capnp.Segment, sz int32) (RuntimeIoProtocol_List, error) {
	return capnp.NewEnumList[RuntimeIoProtocol](s, sz)
}

type FpgaIoMode uint16

// FpgaIoMode_TypeID is the unique identifier for the type FpgaIoMode.
const FpgaIoMode_TypeID = 0x938551662aa7c851

// Values of FpgaIoMode.
const (
	FpgaIoMode_simple FpgaIoMode = 0
	FpgaIoMode_compat FpgaIoMode = 1
	FpgaIoMode_dibDeb FpgaIoMode = 2
)

// String returns the enum's constant name.
func (c FpgaIoMode) String() string {
	switch c {
	case FpgaIoMode_simple:
		return "simple"
	case FpgaIoMode_compat:
		return "compat"
	case FpgaIoMode_dibDeb:
		return "dibDeb"

	default:
		return ""
	}
}

// FpgaIoModeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func FpgaIoModeFromString(c string) FpgaIoMode {
	switch c {
	case "simple":
		return FpgaIoMode_simple
	case "compat":
		return FpgaIoMode_compat
	case "dibDeb":
		return FpgaIoMode_dibDeb

	default:
		return 0
	}
}

type FpgaIoMode_List = capnp.EnumList[FpgaIoMode]

func NewFpgaIoMode_List(s *capnp.Segment, sz int32) (FpgaIoMode_List, error) {
	return capnp.NewEnumList[FpgaIoMode](s, sz)
}

type RuntimeAssets capnp.Struct

// RuntimeAssets_TypeID is the unique identifier for the type RuntimeAssets.
const RuntimeAssets_TypeID = 0xc818738947ac521b

func NewRuntimeAssets(s *capnp.Segment) (RuntimeAssets, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RuntimeAssets(st), err
}

func NewRootRuntimeAssets(s *capnp.Segment) (RuntimeAssets, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RuntimeAssets(st), err
}

func ReadRootRuntimeAssets(msg *capnp.Message) (RuntimeAssets, error) {
	root, err := msg.Root()
	return RuntimeAssets(root.Struct()), err
}

func (s RuntimeAssets) String() string {
	str, _ := text.Marshal(0xc818738947ac521b, capnp.Struct(s))
	return str
}

func (s RuntimeAssets) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RuntimeAssets) DecodeFromPtr(p capnp.Ptr) RuntimeAssets {
	return RuntimeAssets(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RuntimeAssets) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RuntimeAssets) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RuntimeAssets) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RuntimeAssets) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RuntimeAssets) TokenEmbeddingsPath() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RuntimeAssets) HasTokenEmbeddingsPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RuntimeAssets) TokenEmbeddingsPathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RuntimeAssets) SetTokenEmbeddingsPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// RuntimeAssets_List is a list of RuntimeAssets.
type RuntimeAssets_List = capnp.StructList[RuntimeAssets]

// NewRuntimeAssets creates a new list of RuntimeAssets.
func NewRuntimeAssets_List(s *capnp.Segment, sz int32) (RuntimeAssets_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[RuntimeAssets](l), err
}

// RuntimeAssets_Future is a wrapper for a RuntimeAssets promised by a client call.
type RuntimeAssets_Future struct{ *capnp.Future }

func (f RuntimeAssets_Future) Struct() (RuntimeAssets, error) {
	p, err := f.Future.Ptr()
	return RuntimeAssets(p.Struct()), err
}

type LpuPartitionArtifact capnp.Struct

// LpuPartitionArtifact_TypeID is the unique identifier for the type LpuPartitionArtifact.
const LpuPartitionArtifact_TypeID = 0xc7a8c84cbae6ba0e

func NewLpuPartitionArtifact(s *capnp.Segment) (LpuPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return LpuPartitionArtifact(st), err
}

func NewRootLpuPartitionArtifact(s *capnp.Segment) (LpuPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return LpuPartitionArtifact(st), err
}

func ReadRootLpuPartitionArtifact(msg *capnp.Message) (LpuPartitionArtifact, error) {
	root, err := msg.Root()
	return LpuPartitionArtifact(root.Struct()), err
}

func (s LpuPartitionArtifact) String() string {
	str, _ := text.Marshal(0xc7a8c84cbae6ba0e, capnp.Struct(s))
	return str
}

func (s LpuPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LpuPartitionArtifact) DecodeFromPtr(p capnp.Ptr) LpuPartitionArtifact {
	return LpuPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LpuPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LpuPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LpuPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LpuPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LpuPartitionArtifact) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s LpuPartitionArtifact) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LpuPartitionArtifact) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s LpuPartitionArtifact) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s LpuPartitionArtifact) Topology() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s LpuPartitionArtifact) HasTopology() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s LpuPartitionArtifact) TopologyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s LpuPartitionArtifact) SetTopology(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s LpuPartitionArtifact) NumChips() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s LpuPartitionArtifact) SetNumChips(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s LpuPartitionArtifact) TopologyMetadata() (TopologyMetadata, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TopologyMetadata(p.Struct()), err
}

func (s LpuPartitionArtifact) HasTopologyMetadata() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s LpuPartitionArtifact) SetTopologyMetadata(v TopologyMetadata) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewTopologyMetadata sets the topologyMetadata field to a newly
// allocated TopologyMetadata struct, preferring placement in s's segment.
func (s LpuPartitionArtifact) NewTopologyMetadata() (TopologyMetadata, error) {
	ss, err := NewTopologyMetadata(capnp.Struct(s).Segment())
	if err != nil {
		return TopologyMetadata{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s LpuPartitionArtifact) DevicesPerNode() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s LpuPartitionArtifact) SetDevicesPerNode(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s LpuPartitionArtifact) Architecture() LpuArchitecture {
	return LpuArchitecture(capnp.Struct(s).Uint16(8))
}

func (s LpuPartitionArtifact) SetArchitecture(v LpuArchitecture) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

// LpuPartitionArtifact_List is a list of LpuPartitionArtifact.
type LpuPartitionArtifact_List = capnp.StructList[LpuPartitionArtifact]

// NewLpuPartitionArtifact creates a new list of LpuPartitionArtifact.
func NewLpuPartitionArtifact_List(s *capnp.Segment, sz int32) (LpuPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[LpuPartitionArtifact](l), err
}

// LpuPartitionArtifact_Future is a wrapper for a LpuPartitionArtifact promised by a client call.
type LpuPartitionArtifact_Future struct{ *capnp.Future }

func (f LpuPartitionArtifact_Future) Struct() (LpuPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return LpuPartitionArtifact(p.Struct()), err
}
func (p LpuPartitionArtifact_Future) TopologyMetadata() TopologyMetadata_Future {
	return TopologyMetadata_Future{Future: p.Future.Field(2, nil)}
}

type LpuArchitecture uint16

// LpuArchitecture_TypeID is the unique identifier for the type LpuArchitecture.
const LpuArchitecture_TypeID = 0xb2d58c2000d6274d

// Values of LpuArchitecture.
const (
	LpuArchitecture_unspecified LpuArchitecture = 0
	LpuArchitecture_lp20        LpuArchitecture = 1
	LpuArchitecture_lp30        LpuArchitecture = 2
)

// String returns the enum's constant name.
func (c LpuArchitecture) String() string {
	switch c {
	case LpuArchitecture_unspecified:
		return "unspecified"
	case LpuArchitecture_lp20:
		return "lp20"
	case LpuArchitecture_lp30:
		return "lp30"

	default:
		return ""
	}
}

// LpuArchitectureFromString returns the enum value with a name,
// or the zero value if there's no such value.
func LpuArchitectureFromString(c string) LpuArchitecture {
	switch c {
	case "unspecified":
		return LpuArchitecture_unspecified
	case "lp20":
		return LpuArchitecture_lp20
	case "lp30":
		return LpuArchitecture_lp30

	default:
		return 0
	}
}

type LpuArchitecture_List = capnp.EnumList[LpuArchitecture]

func NewLpuArchitecture_List(s *capnp.Segment, sz int32) (LpuArchitecture_List, error) {
	return capnp.NewEnumList[LpuArchitecture](s, sz)
}

type CudaPartitionArtifact capnp.Struct

// CudaPartitionArtifact_TypeID is the unique identifier for the type CudaPartitionArtifact.
const CudaPartitionArtifact_TypeID = 0x9a7000083c582092

func NewCudaPartitionArtifact(s *capnp.Segment) (CudaPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CudaPartitionArtifact(st), err
}

func NewRootCudaPartitionArtifact(s *capnp.Segment) (CudaPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CudaPartitionArtifact(st), err
}

func ReadRootCudaPartitionArtifact(msg *capnp.Message) (CudaPartitionArtifact, error) {
	root, err := msg.Root()
	return CudaPartitionArtifact(root.Struct()), err
}

func (s CudaPartitionArtifact) String() string {
	str, _ := text.Marshal(0x9a7000083c582092, capnp.Struct(s))
	return str
}

func (s CudaPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CudaPartitionArtifact) DecodeFromPtr(p capnp.Ptr) CudaPartitionArtifact {
	return CudaPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CudaPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CudaPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CudaPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CudaPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CudaPartitionArtifact_List is a list of CudaPartitionArtifact.
type CudaPartitionArtifact_List = capnp.StructList[CudaPartitionArtifact]

// NewCudaPartitionArtifact creates a new list of CudaPartitionArtifact.
func NewCudaPartitionArtifact_List(s *capnp.Segment, sz int32) (CudaPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CudaPartitionArtifact](l), err
}

// CudaPartitionArtifact_Future is a wrapper for a CudaPartitionArtifact promised by a client call.
type CudaPartitionArtifact_Future struct{ *capnp.Future }

func (f CudaPartitionArtifact_Future) Struct() (CudaPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return CudaPartitionArtifact(p.Struct()), err
}

type CpuPartitionArtifact capnp.Struct

// CpuPartitionArtifact_TypeID is the unique identifier for the type CpuPartitionArtifact.
const CpuPartitionArtifact_TypeID = 0x96066f26b6b22046

func NewCpuPartitionArtifact(s *capnp.Segment) (CpuPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CpuPartitionArtifact(st), err
}

func NewRootCpuPartitionArtifact(s *capnp.Segment) (CpuPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CpuPartitionArtifact(st), err
}

func ReadRootCpuPartitionArtifact(msg *capnp.Message) (CpuPartitionArtifact, error) {
	root, err := msg.Root()
	return CpuPartitionArtifact(root.Struct()), err
}

func (s CpuPartitionArtifact) String() string {
	str, _ := text.Marshal(0x96066f26b6b22046, capnp.Struct(s))
	return str
}

func (s CpuPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CpuPartitionArtifact) DecodeFromPtr(p capnp.Ptr) CpuPartitionArtifact {
	return CpuPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CpuPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CpuPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CpuPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CpuPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CpuPartitionArtifact_List is a list of CpuPartitionArtifact.
type CpuPartitionArtifact_List = capnp.StructList[CpuPartitionArtifact]

// NewCpuPartitionArtifact creates a new list of CpuPartitionArtifact.
func NewCpuPartitionArtifact_List(s *capnp.Segment, sz int32) (CpuPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CpuPartitionArtifact](l), err
}

// CpuPartitionArtifact_Future is a wrapper for a CpuPartitionArtifact promised by a client call.
type CpuPartitionArtifact_Future struct{ *capnp.Future }

func (f CpuPartitionArtifact_Future) Struct() (CpuPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return CpuPartitionArtifact(p.Struct()), err
}

type PartSelect capnp.Struct

// PartSelect_TypeID is the unique identifier for the type PartSelect.
const PartSelect_TypeID = 0x8d60be198cd5837c

func NewPartSelect(s *capnp.Segment) (PartSelect, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PartSelect(st), err
}

func NewRootPartSelect(s *capnp.Segment) (PartSelect, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PartSelect(st), err
}

func ReadRootPartSelect(msg *capnp.Message) (PartSelect, error) {
	root, err := msg.Root()
	return PartSelect(root.Struct()), err
}

func (s PartSelect) String() string {
	str, _ := text.Marshal(0x8d60be198cd5837c, capnp.Struct(s))
	return str
}

func (s PartSelect) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PartSelect) DecodeFromPtr(p capnp.Ptr) PartSelect {
	return PartSelect(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PartSelect) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PartSelect) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartSelect) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartSelect) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartSelect) Partitions() (gbuildcommoncapnpv1.PartitionRef_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return gbuildcommoncapnpv1.PartitionRef_List(p.List()), err
}

func (s PartSelect) HasPartitions() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PartSelect) SetPartitions(v gbuildcommoncapnpv1.PartitionRef_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPartitions sets the partitions field to a newly
// allocated gbuildcommoncapnpv1.PartitionRef_List, preferring placement in s's segment.
func (s PartSelect) NewPartitions(n int32) (gbuildcommoncapnpv1.PartitionRef_List, error) {
	l, err := gbuildcommoncapnpv1.NewPartitionRef_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return gbuildcommoncapnpv1.PartitionRef_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// PartSelect_List is a list of PartSelect.
type PartSelect_List = capnp.StructList[PartSelect]

// NewPartSelect creates a new list of PartSelect.
func NewPartSelect_List(s *capnp.Segment, sz int32) (PartSelect_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PartSelect](l), err
}

// PartSelect_Future is a wrapper for a PartSelect promised by a client call.
type PartSelect_Future struct{ *capnp.Future }

func (f PartSelect_Future) Struct() (PartSelect, error) {
	p, err := f.Future.Ptr()
	return PartSelect(p.Struct()), err
}

type TopologyMetadata capnp.Struct

// TopologyMetadata_TypeID is the unique identifier for the type TopologyMetadata.
const TopologyMetadata_TypeID = 0x95b5d7af5b73d213

func NewTopologyMetadata(s *capnp.Segment) (TopologyMetadata, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyMetadata(st), err
}

func NewRootTopologyMetadata(s *capnp.Segment) (TopologyMetadata, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyMetadata(st), err
}

func ReadRootTopologyMetadata(msg *capnp.Message) (TopologyMetadata, error) {
	root, err := msg.Root()
	return TopologyMetadata(root.Struct()), err
}

func (s TopologyMetadata) String() string {
	str, _ := text.Marshal(0x95b5d7af5b73d213, capnp.Struct(s))
	return str
}

func (s TopologyMetadata) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TopologyMetadata) DecodeFromPtr(p capnp.Ptr) TopologyMetadata {
	return TopologyMetadata(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TopologyMetadata) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TopologyMetadata) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TopologyMetadata) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TopologyMetadata) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TopologyMetadata) TopologyFamily() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TopologyMetadata) HasTopologyFamily() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TopologyMetadata) TopologyFamilyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TopologyMetadata) SetTopologyFamily(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TopologyMetadata) PartitionShape() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.UInt32List(p.List()), err
}

func (s TopologyMetadata) HasPartitionShape() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TopologyMetadata) SetPartitionShape(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewPartitionShape sets the partitionShape field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s TopologyMetadata) NewPartitionShape(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// TopologyMetadata_List is a list of TopologyMetadata.
type TopologyMetadata_List = capnp.StructList[TopologyMetadata]

// NewTopologyMetadata creates a new list of TopologyMetadata.
func NewTopologyMetadata_List(s *capnp.Segment, sz int32) (TopologyMetadata_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TopologyMetadata](l), err
}

// TopologyMetadata_Future is a wrapper for a TopologyMetadata promised by a client call.
type TopologyMetadata_Future struct{ *capnp.Future }

func (f TopologyMetadata_Future) Struct() (TopologyMetadata, error) {
	p, err := f.Future.Ptr()
	return TopologyMetadata(p.Struct()), err
}

const schema_bc98ba9c8ecc78c8 = "x\xda\x9cXo\x8c\x14g\x19\x7f\x9ey\xf7n\x8f\xe6" +
	"`g:\xb7tO\xa1wE\x11\xbcz\x05z5*" +
	"\xa1]`\x01=\xc2\xd1}wi\xb0\xad\x8d\x9d\x9by" +
	"owdwf\xba3CY\x02%\xd1\x12[\x0a\xc6" +
	"\xaa4h0B-)U\x1a\xfe(\xda\x92b\x04\x8b" +
	"\xa5\x86\x0f\x94\x14\x8d\x04c5Q\xfeD?X\xd3\x80" +
	"&u\xcc;373,G\xd2=\xbe0y\xde\xdf" +
	">\xcf\xfb<\xcf\xef\xf9\xf3\xde\xfc\x97\xd3\x8bS\x0b\xa6" +
	"^\xbb\x13\x84r\x15;:\xbdz\xf6\xdf\xcfH+\xef" +
	"\xde\x06\xd2 z\xa77\x9c\xf9\xd6\xeec\xbb\xde\x80\x0e" +
	"L\x03\x0c)\x99\x0b(o\xce\xa4\x01\xe4f&\x0f\xe8" +
	"m\xfa\xc6\xf9\xed\xbd\xbfz|\xc7D\xe0W3'Q" +
	">\xe5\x83O\xf8`z\xfa\xe5\x811\xba\xf5\xbb \x0d" +
	"\x0a1\x18p\xe8\x03\x8e\x9c*r\xe4\x14\xf1A@O" +
	">g?z\xf0\x0fGw\xb6\xa8\x15\xb8\xda\x99\xe2\xfb" +
	"(\x7f\xc1\x07\x7fV|\x12\xd0[\xd1\x7f\xe4\x17\x9f2" +
	";_\xb8\x11\x9c\xe2\xd8W\xc4\xdb\x05\xf9m1\x0d\xe4" +
	"\xcf\xdf\xe9\xff\xf2\xa2.\xeb\x077c\xf6\x89\x1f\x13\xe4" +
	"S\x1c\xe3\xfdr\xf5\xec7/\xcfi\xfe\x08\xe8 \xde" +
	"dw\xafx\x9b \x9f\xf0\xed\x1e\x17\x0f\x02^\x1b\x99" +
	"\xf3\xfb\xfe\xed\xe7\x8f\xb4:\xf3\x98t\x15\xe5\xa6\xc4q" +
	"\xae\xc4\x9da\x87\xfbK}C\xdd\xbfi\xd5\x9a\xe6Z" +
	"wH'Q\xde'\xf9\x06\xa4\xb7\x10\xd0\x9bv\xec\xef" +
	"\xc7V\x9d\xde\xff\x16\x87'4w\x10\x8e\xd9)\xdf." +
	"\xc8Ge\xfeyX^\xcb\xe1\x1f/\x1d\xf8\xe2\xb3v" +
	"\xee\xf4D\x19\xc8f/\xa0\xbc \xcb\xaf2\x98\xe5\x19" +
	"\xf8\xedS\xdb\xa6\xad\x7fn\xce\xef@\x1aL\xddp\xe9" +
	"\x87\xb2\x03\x82\xecrd\xd9\xca\x12,o\xca\x0a\x08\xe0" +
	"\xfdgm\xdf\x07\x0f\xfc\xf3\xd2\xd9\x89\x94\xd7\xb9\xf2g" +
	"}\xe5[}\xe5\x8b\x9f\xbc\xaf{\xee\xe6\x0b\xe7Z." +
	"\x1e\x049{\x15\xe5\x13>\xf8x\xf6\x12\xa0\xf7\xdc\xbe" +
	"\x03\xb3\xab\xcdE\x7f\x998\xd4\xd3/\xa0||:\xff" +
	"|}z\x1f\xf7r\xcf\xb5\xe7\x1f-\xdd\xfd\xe3K\x13" +
	"\xc2\xaf\xdcq\x9b O\xc9q\xe5\x1d9\xce\x88\xe3B" +
	"A\xf8\xc4\xc5\xa3\xff\xba\x89h\xc39A\x90\x99\x8fT" +
	"r}\x80\xdeS{_\xb8t\xf2\xfa\x85\x9b\x91\x0f\xe7" +
	"\xae\xa2\xec\xfa\xc8'r\x9f\x03\xf4\xee\xfc\x8c\xbb\xf6\xae" +
	"\x9f\x9ez\x1f\xe8\x12L\xdc\xe7!!\x8d\x04`\xc8\xcd" +
	"-\x15\x00\xe5\x1d\xb9\x83\x80\xde\xd9\xf9\x7f|\xfe\x8e\x17" +
	"\x07\xaf\xdf\xa4uv\xef\x7fQ^\xd2\xcb\xb5\xde\xdf\xcb" +
	"\xb5\x1eY\xf9\xc0\xcf\xe6]Y\xf4\xe1\x84\xc9^\xde\xfb" +
	"W\x94\x15\x8e\x1ez\xacw-\x82\x07\x1e\\\xf7*\xa3" +
	"\xae^\xd3\xbe\xaau2\xabf6\xeb\xccp\xe6\xad_" +
	"0o\\\x1a\x09\xefQ\x15\xcb\xb0\x16\x16\x1b\xa6Un" +
	"\x1aj\xa1\xaa\x10\xdd(\"\xd2\x14I\x01\xa4\x10@\x9a" +
	"\xfa5\x00\xdaM\x90\xce\x15\xd0\xb3\x94\x86\xa3;\xba\x09" +
	"\x19cX\xb3q\x1a`\x91 v\x81\xc0?\xdb5\xaa" +
	"4\x9c2\xab1\xd5\x81\x16\x8b\x8fLd\x91\x18\x91=" +
	"\xd1{\xfb\xf3\x87\xce\xdf\xff\xf0\xeeo\x02\xe0$,\xaf" +
	"\xb0*\xca\xb09bj\xcc\xb7\xdc\x8d\x02\x804s!" +
	"W&e\xf9\x7f\x824u!@\xde\xd6\xebV\x8d\xe5" +
	"U\xb3n)N^\xd3G\x97\xb1\xd16M\xad1-" +
	"\xb3fV\x9a#\xcc\xe9S4\xc5Q\xb8\xc1\xae\xc8\xd5" +
	"Oo\x04\xa0s\x09\xd2\xfb\x04\x94\x10{\x90\x0b\x17p" +
	"\xe1|\x82t\x95\x80\x9e\x13*\x80\xfc\x0a\xa5\xae\xd7\x9a" +
	"\xd8\x0d\x02vC\"0y\xa3\\U,v\xabd\xa4" +
	"?\xd2=\x0b\x96[\x0c\x15\x1aK\x1a\x8e>\xa6\xa8\xe8" +
	"\x14\xb1m5\xae\xa6\xb4\xe8!\xead\xf4T\x99\xba\xce" +
	"2u\xc3)\xb11\xd6`\x86\xca \xc8U\x14\xba\xe5" +
	"+\x01\xe82\x82\xb4(\xe0x\xe4F\xee\x05\xa0_\"" +
	"H\xd7\x08(\x09\xd8\xe3'\x96r`\x91 \xfd\x0a\xa7" +
	"S\xc3\\\xafk\xac\x01\x00\x98\x89[\x00 f\x00\xfb" +
	"\xea\xa6\xc6jQ\x84\x1bl\xbdn\xeb\xa6\xc1\xb1\xe3\xb2" +
	"\xf6\xb2\xbf\xcar\x974\xd4\xaa\xee05\xe3\xb8\x0d\x96" +
	"`\xdb\xa8\xcf\xb6\xde\x01\x9fm\xd2\x00\x80\xe7\x1a\xb6\xc5" +
	"T}\x0c\xd2:\xd325\xeb\xde\xf9\x99\x9a54\xbf" +
	"M\x93\xcb\"\x81\x1f\xaf\xfe(^\xefl\x03\xa0\xef\x12" +
	"\xa4\xef\xc5\xf1\xfa\x13\x0f\xcdE\x82\xf4r\"^\x7f[" +
	"\x08@\xdf#H\xff!\xa0D\x84\x1e\xde\xb9\xa4+\xbc" +
	"&/\x13,\xa7P@)Ez0\x05 #6\x00" +
	"JH\xb0\xdc\xcd\xc5\x1d\xa9\x1e\xec\xe0\xe3\x19\x1f\x01(" +
	"wqy\x0f\x97wv\xf4`'\x80,a\x09\xa0," +
	"r\xf9\x0c.Ow\xf6\xf0!!\xf7\xfa\xf8\x1c\x97\x7f" +
	"\x12\x05\xf4T\xd3p\x1a\x8a\xea`)\xca\x80O\xeb." +
	"@O\xd7\x98\xe1\xe8N\x93'E\x8cG\x0f \x8a\x80" +
	"y\xd54\xc6\xf4\x0a\x8aq\xcb\x0c\x0en\xd1F\xa2\x06" +
	"\x1d\xb6\x91\x86k8z\x9d-\x81>\xdbf\x8e\x8db" +
	"<8\x13zx\xd3\x02\xa2:(\xc6\x9bMx\xcc6" +
	"0\xd5\xe5f\xd0@\xd1\xcb\xff\xa4f\x96/\xf6\x9e\x19" +
	"?UCV\x031\xf8\x8f\xa3E\"<n\xafDV" +
	"\xdd\xa2bi.J\xf9\xf7\x07\x00\xe8\xf7\x08\xd2=\x89" +
	"\xee\xf2C\x9e\xf3\xdd\x04\xe9~\x01Q\x08R\xbe\x8f\xcb" +
	"^\"H\x0f%R\xfe*'\xcc!\x82\xf4\x0d\x9eq" +
	"\xf43.\xbd\xce{\xd3k\x04\xe9\x9bq\xbe\xa5\x13|" +
	"D\xfc\x9a =#`\xc6R\x9cjT.Q\xf7J" +
	"\x94\x90\xe1\xd6\x0bU\xdd\xb2!\x91\xd5q\x1c\x8e0\xc7" +
	"o\x93~v\xa3\x05/\x0c\x90\xc6\xd6\xeb*\xb3\x8b\x90" +
	"g\x8d\xd5\xa6\xc6\xa2\x9f+a\x91\x81_e\x98\x19\xdf" +
	"\xba\x82\xb2n\xb3\x82J!\x09l\x9b\x11\xc7n\x19M" +
	"/\x02P\x91 \x9d\xe1\xb7\xe6u\xccX^\x1fE\xa6" +
	"i\xbaQ\xb1\x8b\xe9\xa4\xeb\xedeSu\x1b\x0df8" +
	"\x85\x90\xf9\x9c\xf8\x19\xce\xfc\"\xfa\x1d]\xea\xc2\xb6\xfd" +
	"X\xca\xc5\xc3~\xb9\x10\xa7\xd9\xe2\xc7R\x00\xdaE\x90" +
	"\xf6\x08\xb8e4\x00N\xb2\xc7\x85\xe1\x1a6\x0bf\x86" +
	"\x17\x1f7$F\x86\x14\xce\xac\xc7\x09\xd2Z\x82\x82:" +
	"\x17V\x09R'\xd1v\x9e\x18\x05\xa0\x16A\xba)\xc1" +
	"\xc1&g\xd6\x06\x82\xf4\xe9\xa0w;\xa6j\xd6\x82\xde" +
	"\x1d\xadOa\x92\xc7\xac\x8a\xe2\x8ft\xff4zE\x84" +
	"\xa7\xba\xc9\x87~\xc1\x84\xb4k8\x11o\xc6\x14\xc3t" +
	"\x9d\x15\x0adT\xc7lD\xe2\xb6\x97\xa7JC\xa9\x17" +
	"Lc\x8c\x04\xee\xf7D\xeeo\xe6Nm\"H\x9fI" +
	"\xb8\xbf\x95\x0b\x9f&H\xbf\x1dW\xe0\x8e\x12\x00\xddN" +
	"\x90\xee\xe2\xde\xf7\x07\xde\xef<\x02@w\x11\xa4/\xf1" +
	"\x0a\xbc+\xa8\xc0\xbd\xe7\x00\xe8~\x82\xf4\xe7AH\xb8" +
	"\xed\xd5\x90V\xea,\xb1\x1a\xa8\xeb\x94\x0ak\x91\x8e*" +
	"\x8eZ-\xeb\x1b\x01\xe3\xc2\xb1]\xcb2\x1b\x8e\x8d\x05" +
	"\xcb]^\x1feZ\x9f\xcfdD\x10\x903\xcev\x14" +
	"CSj\xa6`\xb05!\xdb\x03\xb2c\x8ci\x8f\xe8" +
	"Q\xcfJ\x0c*hY\x8aJ\xf1R\xc4\xff\xc5[\xb5" +
	"\xb4`!\x08q/\xf7\x9blr\x15\xe4#@c\x8e" +
	"\xa2\xd7&\xbdo\x14\xc7\x17\x04\xbf`\xfc\xdct\x8c\x02" +
	"xU\xb7R\xd1\x8d\xca\x18\xa4\x15\x95\xb5\xc9\x90\x82Y" +
	"\xb7\xf4\x9a\xc2\xbd\xcep\x8a\xfa\xee\xfa\xaa\xa5\xa5\xfe\x1a" +
	"0e\x16\xc0\x96\x9a\xe5>h\xd4\x9a\xe9\x9a\xb5!\xd2" +
	"\xdf5\xd9\x98\xde\x13\x84\x81\xef\xd1\xa9\x19\x9e\x172o" +
	"\xf9,\x00\xba8\xd8,g\xe2\xff\xbc\xb0\xf4\x86\x07\xe2" +
	"Uj\xa6\xf0!\x17s\xfa\x8d\xcc\x8a\xb7\xa9t\xcdr" +
	"Q\x8c\x9f\x9dA\xb03\xaa\xab)(\x8e?\x9b\x03a" +
	"Z\xf5\xa1\xd1\x83\xbbe\xba\xb5\xd9U\x8a\x8d|P\xf5" +
	"\x89\xa0\x0d\x04A[\x09\x90\xa9\x9a\xb6\xe3\x97~\xc9\xe4" +
	"+\"Lz[\x1aN\x1bcf\xcb\xf8\xfcz\xa2\xfc" +
	"\xc6\x8bw//\xde=\x04\xe9\x01\xde\xbb\xc2\xea}e" +
	"c\\\x93H\x82\xe8\x1d\xe6-\xf6\x00A\xfaZb|" +
	"\x1e=\x16\x8e\xcfw\xf9\xf8\x14\x82\xf1\xf9\x0e\xe7\xfbY" +
	"\x82\xf4\xa2\xbf\xfb\x04\\A\xdd4\xfcv\x86\x99\xf8\xfd" +
	"\x1963\xc3\xad\xaf\xb2\xdc\xd5&\xa45f'f\xa8" +
	"\xa3\xd4V\xbbu\xc8\x97\x1d\xa5\x12\x1fl\x09\x9b\x04\x8a" +
	"\xf1{:\xcc\x89\xed?\xbf\x98\x86\xe3\x0f\xc0|\xa1\xaa" +
	"\xe8\xc9\x0d)\xfa;\xcf\x8d\x1b\xd20\xa0\x89b\xfc\x98" +
	"\x0f\xf4\xfd?\x00\x00\xff\xff+\xddE\xec"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bc98ba9c8ecc78c8,
		Nodes: []uint64{
			0x8a2b4a1188f3156d,
			0x8d60be198cd5837c,
			0x938551662aa7c851,
			0x95b5d7af5b73d213,
			0x96066f26b6b22046,
			0x9a7000083c582092,
			0x9f7927e8c4254eb7,
			0xb2d58c2000d6274d,
			0xc30c331f5220b165,
			0xc7a8c84cbae6ba0e,
			0xc818738947ac521b,
			0xca278b760e8a7ec6,
			0xd0e7ed3ef51f57f9,
			0xd2da7d280c347740,
			0xe13c796825aca58b,
			0xe7a32b525b91f7a0,
			0xf1b5dc23024302bd,
			0xf1daf8c2e796a17e,
			0xf2c5ab2157752c1e,
			0xf82da21791d930d0,
			0xfd3ce92fb33e4ab2,
		},
		Compressed: true,
	})
}
