# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import podresources_api as podresources__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated PodResources client depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PodResourcesListerStub:
    """Wire-compatible subset of kubelet's podresources.v1 API used by the Power
    Agent. Unknown fields in the upstream response are intentionally ignored.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/v1.PodResourcesLister/List",
            request_serializer=podresources__pb2.ListPodResourcesRequest.SerializeToString,
            response_deserializer=podresources__pb2.ListPodResourcesResponse.FromString,
            _registered_method=True,
        )


class PodResourcesListerServicer:
    """Wire-compatible subset of kubelet's podresources.v1 API used by the Power
    Agent. Unknown fields in the upstream response are intentionally ignored.
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PodResourcesListerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=podresources__pb2.ListPodResourcesRequest.FromString,
            response_serializer=podresources__pb2.ListPodResourcesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "v1.PodResourcesLister", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("v1.PodResourcesLister", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PodResourcesLister:
    """Wire-compatible subset of kubelet's podresources.v1 API used by the Power
    Agent. Unknown fields in the upstream response are intentionally ignored.
    """

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/v1.PodResourcesLister/List",
            podresources__pb2.ListPodResourcesRequest.SerializeToString,
            podresources__pb2.ListPodResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
