/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dynamo

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/ai-dynamo/dynamo/deploy/operator/api/v1beta1"
	commonconsts "github.com/ai-dynamo/dynamo/deploy/operator/internal/consts"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/runtimeversion"
	"k8s.io/utils/ptr"
)

const dgdWorkerHashPlaceholderValue = "worker-hash-placeholder"

// Preserve hashes for runtimes released before version hashing.
var minimumHashedRuntimeVersion = runtimeversion.Version{Major: 1, Minor: 5, Patch: 0}

// participatesInWorkerSpecHash reports whether a generated DCD contributes to the
// canonical worker-spec hash.
//
// The synthesized elastic-EP follower does not. It is derived from the leader rather
// than declared by the user, so hashing it would change the worker hash of every
// existing elastic-EP DGD the moment an operator carrying this feature rolls out --
// restarting a serving leader whose requested spec never changed. Any real change to
// the follower comes from the leader it is copied from, which is hashed.
func participatesInWorkerSpecHash(dcd *v1beta1.DynamoComponentDeployment) bool {
	if !IsWorkerComponent(string(dcd.Spec.ComponentType)) {
		return false
	}
	return dcd.GetAnnotations()[commonconsts.KubeAnnotationElasticEPFollower] != commonconsts.KubeLabelValueTrue
}

// ComputeDGDWorkersSpecHash computes the v2 worker hash from the worker DCDs
// generated by the same DGD-to-DCD path used by reconciliation. The active
// worker hash is replaced by a fixed placeholder before generation so the hash
// can be computed without depending on itself.
func ComputeDGDWorkersSpecHash(dgd *v1beta1.DynamoGraphDeployment) (string, error) {
	if dgd == nil {
		return "", fmt.Errorf("nil DynamoGraphDeployment")
	}

	dcds, err := GenerateDynamoComponentsDeployments(
		dgd,
		nil,
		nil,
		RollingUpdateContext{NewWorkerHash: dgdWorkerHashPlaceholderValue},
	)
	// Generation now synthesizes a follower unconditionally, so one is produced here too.
	// The hash is unaffected: participatesInWorkerSpecHash excludes followers, so the
	// synthesized DCD is discarded below. That exclusion is what keeps the worker hash --
	// and therefore every worker pod -- from moving when an administrator flips
	// features.ElasticEPRayPoC.
	if err != nil {
		return "", err
	}

	type workerTemplate struct {
		Labels         map[string]string                     `json:"labels,omitempty"`
		Annotations    map[string]string                     `json:"annotations,omitempty"`
		RuntimeVersion string                                `json:"runtimeVersion,omitempty"`
		Spec           v1beta1.DynamoComponentDeploymentSpec `json:"spec"`
	}

	workerDCDs := make(map[string]workerTemplate, len(dcds))
	for _, dcd := range dcds {
		if dcd != nil && participatesInWorkerSpecHash(dcd) {
			componentName := GetDCDComponentName(dcd)
			if componentName == "" {
				return "", fmt.Errorf("generated worker DCD %q has no component name label", dcd.Name)
			}
			if _, exists := workerDCDs[componentName]; exists {
				return "", fmt.Errorf("duplicate generated worker DCD component name %q", componentName)
			}
			// The follower count reaches the hash by two routes, and both must be stripped
			// or the strip is a no-op: workerHashSpec covers spec.podTemplate.annotations,
			// and GetDCDKubeAnnotations copies the pod-template annotations into this
			// separate Annotations field (v1beta1_helpers.go). See workerHashSpec for why
			// this value must not create a worker generation.
			annotations := GetDCDKubeAnnotations(dcd)
			delete(annotations, commonconsts.KubeAnnotationElasticEPFollowerReplicas)

			workerDCDs[componentName] = workerTemplate{
				Labels:         GetDCDKubeLabels(dcd),
				Annotations:    annotations,
				RuntimeVersion: resolvedRuntimeVersionForHash(&dcd.Spec.DynamoComponentDeploymentSharedSpec),
				Spec:           workerHashSpec(dcd),
			}
		}
	}

	data, err := json.Marshal(workerDCDs)
	if err != nil {
		return "", fmt.Errorf("marshal generated worker DCDs: %w", err)
	}

	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])[:8], nil
}

func workerHashSpec(dcd *v1beta1.DynamoComponentDeployment) v1beta1.DynamoComponentDeploymentSpec {
	spec := dcd.Spec.DeepCopy()

	// Replica count, availability envelope, and autoscaling ownership patch the
	// active DCD. They must not create a new worker generation.
	spec.Replicas = nil
	spec.MinAvailable = nil
	spec.ScalingAdapter = nil

	// Hash the resolved version separately so equivalent image-derived and
	// explicit versions produce the same worker hash.
	spec.RuntimeVersionOverride = ""

	// The synthesized-follower count is derived from --data-parallel-size, which is already
	// hashed as part of the container's args. Hashing the derived annotation too would make
	// the same declaration produce a new worker generation purely because this operator
	// records a number the previous one did not.
	//
	// That matters most where the annotation does nothing. The Grove pathway never
	// synthesizes a follower and never reads this value, but ComputeDGDWorkersSpecHash
	// computes the hash by RUNNING generation, which stamps it regardless of pathway, and
	// dgd_grove_workload_renderer.go stamps the resulting hash onto every worker pod. Without
	// this strip, upgrading the operator restarts a Grove user's GPU workers to record a
	// value their deployment cannot use -- measured: an unchanged Grove dp=2 component moved
	// b61319fa -> 9761526a.
	//
	// The leader still picks up the annotation: it lands in the DCD's pod template, so the
	// Deployment rolls its own pods in place. What this avoids is a new worker GENERATION --
	// a renamed DCD -- which additionally renames the follower and loses its replica count.
	if spec.PodTemplate != nil {
		delete(spec.PodTemplate.Annotations, commonconsts.KubeAnnotationElasticEPFollowerReplicas)
	}

	// Roles are a Kubernetes map-list keyed by name. Canonicalize the copied
	// slice so declaration order does not create a new worker generation. Role
	// replicas only assert cardinality already defined by the component shape,
	// so their optional presence must not create a generation either.
	if spec.Multinode != nil {
		for i := range spec.Roles {
			spec.Roles[i].Replicas = nil
		}
	}
	sort.Slice(spec.Roles, func(i, j int) bool {
		return spec.Roles[i].Name < spec.Roles[j].Name
	})

	// An explicit declaration of the established multinode roles is a
	// representation-only migration and must not create a worker generation.
	if ExplicitMultinodeRolesMatchImplicit(&spec.DynamoComponentDeploymentSharedSpec) {
		spec.Roles = nil
	}

	// forceScalingGroup false and omitted select the same rendering, so an
	// explicit false must not create a new worker generation.
	if spec.Experimental != nil && spec.Experimental.Grove != nil &&
		!ptr.Deref(spec.Experimental.Grove.ForceScalingGroup, false) {
		spec.Experimental.Grove.ForceScalingGroup = nil
	}

	// Empty wrappers and disabled checkpoint configurations are equivalent to omission.
	if spec.Experimental != nil {
		if spec.Experimental.Grove != nil && *spec.Experimental.Grove == (v1beta1.GroveSpec{}) {
			spec.Experimental.Grove = nil
		}
		if spec.Experimental.Checkpoint != nil && !spec.Experimental.Checkpoint.Enabled {
			spec.Experimental.Checkpoint = nil
		}
		if *spec.Experimental == (v1beta1.ExperimentalSpec{}) {
			spec.Experimental = nil
		}
	}

	// Omitted and backend-default cache paths render identically. This requires
	// GenerateDynamoComponentsDeployments to populate spec.BackendFramework
	// on the generated DCD before workerHashSpec is called.
	if spec.CompilationCache != nil {
		defaultPath := getDefaultCompilationCacheMountPoint(BackendFramework(spec.BackendFramework))
		if defaultPath != "" && spec.CompilationCache.MountPath == defaultPath {
			spec.CompilationCache.MountPath = ""
		}
	}

	return *spec
}

// resolvedRuntimeVersionForHash returns the canonical runtime version included
// in the v2 worker hash. The hash identifies a worker generation: changing it
// creates a new generation and triggers a managed rollout. The hash should
// change exactly when a downstream rendered workload PodSpec changes.
// Computing that directly would require refactoring this path to construct the
// full component set and render the final Deployment or Grove PodSpec.
//
// An alternative considered was resolving the runtime version, evaluating all
// runtime feature gates, and hashing those decisions. That would be more
// precise: upgrading from 1.5.0 to 1.6.0 would preserve the hash when both
// versions enable the same gates and render the same PodSpec. Hashing the
// canonical resolved version is simpler and also makes equivalent image-derived
// and explicit versions hash identically.
//
// Runtime versions should normally change together with the image, which already
// changes the hash. This value matters primarily when runtimeVersionOverride is
// corrected without changing the image. If that correction changes downstream
// version-gated rendering, the worker hash changes and triggers the required
// rollout.
//
// Versions before 1.5.0 are omitted. runtimeVersionOverride was introduced in
// 1.4.0, but runtime-version feature-gated rendering begins in 1.5.0. Hashing
// 1.4.x versions would change existing worker hashes, triggering a rollout even
// though their rendered PodSpecs remain unchanged.
func resolvedRuntimeVersionForHash(component *v1beta1.DynamoComponentDeploymentSharedSpec) string {
	if component == nil {
		return ""
	}

	image := ""
	if main := GetMainContainer(component); main != nil {
		image = main.Image
	}
	version, err := runtimeversion.Resolve(image, component.RuntimeVersionOverride)
	if err != nil || version.Compare(minimumHashedRuntimeVersion) < 0 {
		return ""
	}

	return version.String()
}
