apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/volcano-sh/volcano/v1.13.2/installer/volcano-development.yaml

images:
  - name: docker.io/volcanosh/vc-webhook-manager
    newName: harbor.weizhipin.com/cloud-native/volcanosh/vc-webhook-manager
    newTag: v1.13.2
  - name: docker.io/volcanosh/vc-controller-manager
    newName: harbor.weizhipin.com/cloud-native/volcanosh/vc-controller-manager
    newTag: v1.13.2
  - name: docker.io/volcanosh/vc-scheduler
    newName: harbor.weizhipin.com/cloud-native/volcanosh/vc-scheduler
    newTag: v1.13.2

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: volcano-scheduler
      namespace: volcano-system
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload-type: cpu
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: volcano-controllers
      namespace: volcano-system
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload-type: cpu
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: volcano-admission
      namespace: volcano-system
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload-type: cpu
  - target:
      group: batch
      version: v1
      kind: Job
      name: volcano-admission-init
      namespace: volcano-system
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload-type: cpu
