apiVersion: v1
kind: Service
metadata:
  name: compoundai-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: compoundai-ui
  sessionAffinity: None
  type: ClusterIP
