apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: compoundai-ingress
spec:
  gateways:
  - istio-system/ingress-alb
  hosts:
  - "{{ .Values.istio.host }}"
  http:
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: compoundai-server.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: compoundai-ui.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
