apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: sglang-backend-timeout
  namespace: dynamo-system
spec:
  default:
    timeoutSec: 300
  targetRef:
    group: ""
    kind: Service
    name: sglang-dsv31-aggregated-gaie-pool-ips-4e170b3d
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: sglang-disagg-backend-timeout
  namespace: dynamo-system
spec:
  default:
    timeoutSec: 300
  targetRef:
    group: ""
    kind: Service
    name: sglang-dsv31-disagg-gaie-pool-ips-25cadd13
