steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_EPP_IMAGE}'
      - '-f'
      - 'Dockerfile.epp-cloudbuild'
      - '--build-arg'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - '--build-arg'
      - 'BUILD_REF=${_BUILD_REF}'
      - '.'
images:
  - '${_EPP_IMAGE}'
substitutions:
  _EPP_IMAGE: 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/dynamo-epp:latest'
  _BUILD_REF: 'main'
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 200
timeout: 3600s
