tensor_parallel_size: 8
moe_expert_parallel_size: 8
enable_attention_dp: true
pipeline_parallel_size: 1
max_batch_size: 512
max_num_tokens: 512
max_seq_len: 2251
cuda_graph_config:
  enable_padding: true
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  - 768
  - 1024
  - 2048
  - 512
print_iter_log: true
kv_cache_config:
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.8
  dtype: fp8
moe_config:
  backend: CUTLASS
cache_transceiver_config:
  max_tokens_in_buffer: 8448
  backend: default
stream_interval: 20
