apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: multinode-failover
spec:
  containers:
  - name: etcd
    image: quay.io/coreos/etcd:v3.5.17
    command:
    - /usr/local/bin/etcd
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd.multinode-failover.svc.cluster.local:2379
    ports: []
  restartPolicy: Always
