apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debug-k8s-discovery-binding
  namespace: multinode-failover
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: debug-k8s-discovery-role
subjects:
- kind: ServiceAccount
  name: debug-k8s-discovery
  namespace: multinode-failover
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: debug-k8s-discovery-role
  namespace: multinode-failover
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - dynamoworkermetadatas
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
