apiVersion: v1
kind: Service
metadata:
  name: debug-headless
  namespace: multinode-failover
spec:
  clusterIP: None
  selector:
    app: debug-failover
  ports:
  - name: master-0
    port: 29500
    targetPort: 29500
  - name: master-1
    port: 29600
    targetPort: 29600
  publishNotReadyAddresses: true
