# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

kind: DaemonSet

env:
  - name: LOKI_URL
    value: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

plugins:
  - fluent-plugin-grafana-loki

fileConfigs:
  01_sources.conf: |-
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_type string
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
          keep_time_key false
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
          keep_time_key false
        </pattern>
      </parse>
    </source>
    <source>
      @type prometheus
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>
  02_filters.conf: |-
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
  03_outputs.conf: |-
    <match kubernetes.**>
      @type loki
      url "#{ENV['LOKI_URL']}"
      extra_labels {"cluster":"dynamo-production"}
      <label>
        namespace $.kubernetes.namespace_name
        pod $.kubernetes.pod_name
        container $.kubernetes.container_name
        app $.kubernetes.labels.app
      </label>
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
