// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Preserve native null semantics without duplicating the upstream request
//! declaration. Serde's remote derive still owns all field parsing/validation.
//! Only the top_logprobs scalar is inspected; message/media bodies are passed
//! directly to the derived parser, not materialized into a second JSON tree.

use serde::{
    Deserialize, Deserializer, Serialize, Serializer,
    de::{
        DeserializeSeed, Error, IntoDeserializer, MapAccess, Visitor, value::MapAccessDeserializer,
    },
};

use super::NvCreateChatCompletionRequest;

impl<'de> Deserialize<'de> for NvCreateChatCompletionRequest {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct RequestVisitor;

        impl<'de> Visitor<'de> for RequestVisitor {
            type Value = NvCreateChatCompletionRequest;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("a chat completion request object")
            }

            fn visit_map<M: MapAccess<'de>>(self, map: M) -> Result<Self::Value, M::Error> {
                let mut tracked = NullTrackingMap {
                    map,
                    current_is_top_logprobs: false,
                    explicit_null: false,
                };
                // Inherent deserialize is generated by #[serde(remote = "Self")].
                let mut request = NvCreateChatCompletionRequest::deserialize(
                    MapAccessDeserializer::new(&mut tracked),
                )?;
                request.top_logprobs_explicit_null = tracked.explicit_null;
                Ok(request)
            }
        }

        deserializer.deserialize_map(RequestVisitor)
    }
}

struct NullTrackingMap<M> {
    map: M,
    current_is_top_logprobs: bool,
    explicit_null: bool,
}

impl<'de, M: MapAccess<'de>> MapAccess<'de> for NullTrackingMap<M> {
    type Error = M::Error;

    fn next_key_seed<K: DeserializeSeed<'de>>(
        &mut self,
        seed: K,
    ) -> Result<Option<K::Value>, Self::Error> {
        let Some(key) = self.map.next_key::<String>()? else {
            return Ok(None);
        };
        self.current_is_top_logprobs = key == "top_logprobs";
        seed.deserialize(key.into_deserializer()).map(Some)
    }

    fn next_value_seed<V: DeserializeSeed<'de>>(
        &mut self,
        seed: V,
    ) -> Result<V::Value, Self::Error> {
        if self.current_is_top_logprobs {
            let value = self.map.next_value::<serde_json::Value>()?;
            self.explicit_null = value.is_null();
            seed.deserialize(value.into_deserializer())
                .map_err(Self::Error::custom)
        } else {
            self.map.next_value_seed(seed)
        }
    }
}

impl Serialize for NvCreateChatCompletionRequest {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        #[derive(Serialize)]
        struct ExplicitNull {
            top_logprobs: (),
        }

        #[derive(Serialize)]
        struct Wire<'a> {
            #[serde(flatten, with = "NvCreateChatCompletionRequest")]
            request: &'a NvCreateChatCompletionRequest,
            #[serde(flatten)]
            explicit_null: Option<ExplicitNull>,
        }

        Wire {
            request: self,
            explicit_null: self
                .has_null_top_logprobs()
                .then_some(ExplicitNull { top_logprobs: () }),
        }
        .serialize(serializer)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocols::{openai::OpenAIOutputOptionsProvider, unified::UnifiedRequest};
    use serde_json::json;

    #[test]
    fn nullable_top_logprobs_survives_json_and_unified_roundtrips() {
        for top in [
            None,
            Some(serde_json::Value::Null),
            Some(json!(0)),
            Some(json!(1)),
        ] {
            for selected in [false, true] {
                let mut body = json!({
                    "model": "null-control", "messages": [], "logprobs": true,
                    "min_tokens": 0, "metadata": {"top_logprobs": null},
                    "nvext": {"extra_fields": ["prompt_logprobs"]},
                    "logprob_token_ids": if selected {vec![0]} else {vec![]},
                });
                if let Some(value) = &top {
                    body["top_logprobs"] = value.clone();
                }
                let expected = if top.as_ref().is_some_and(serde_json::Value::is_null) && !selected
                {
                    None
                } else {
                    Some(
                        top.as_ref()
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                    )
                };
                let request: NvCreateChatCompletionRequest =
                    serde_json::from_str(&body.to_string()).unwrap();
                assert_eq!(request.get_logprobs(), expected);
                let serialized = serde_json::to_value(&request).unwrap();
                assert_eq!(serialized.get("top_logprobs"), top.as_ref());
                assert!(serialized.get("top_logprobs_explicit_null").is_none());
                assert_eq!(serialized["min_tokens"], 0);
                assert_eq!(serialized["nvext"], body["nvext"]);
                assert_eq!(serialized["metadata"], body["metadata"]);
                let unified = UnifiedRequest::from(request);
                assert_eq!(unified.get_logprobs(), expected);
                let restored = UnifiedRequest::from(
                    serde_json::from_value::<NvCreateChatCompletionRequest>(
                        serde_json::to_value(unified.inner).unwrap(),
                    )
                    .unwrap(),
                );
                assert_eq!(restored.get_logprobs(), expected);
                assert_eq!(
                    serde_json::to_value(restored.inner)
                        .unwrap()
                        .get("top_logprobs"),
                    top.as_ref()
                );
            }
        }
    }

    #[test]
    fn typed_count_overrides_retained_null_presence_without_duplicate_keys() {
        let mut request: NvCreateChatCompletionRequest = serde_json::from_value(json!({
            "model": "test", "messages": [], "logprobs": true, "top_logprobs": null
        }))
        .unwrap();
        request.inner.top_logprobs = Some(2);
        assert_eq!(request.get_logprobs(), Some(2));
        let json = serde_json::to_string(&request).unwrap();
        assert_eq!(json.matches("\"top_logprobs\"").count(), 1);
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&json).unwrap()["top_logprobs"],
            2
        );
    }

    #[test]
    fn malformed_counts_and_duplicate_keys_remain_errors() {
        for invalid in [
            json!(true),
            json!([]),
            json!({}),
            json!("0"),
            json!(-2),
            json!(256),
        ] {
            let body = json!({"model": "test", "messages": [], "top_logprobs": invalid});
            assert!(serde_json::from_value::<NvCreateChatCompletionRequest>(body).is_err());
        }
        assert!(
            serde_json::from_str::<NvCreateChatCompletionRequest>(
                r#"{"model":"test","messages":[],"top_logprobs":null,"top_logprobs":0}"#
            )
            .is_err()
        );
    }
}
