# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Shared helpers for the per-ecosystem NOTICES generators."""

from __future__ import annotations

import csv
import dataclasses
import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# SPDX-expression sentinel that means "we don't know what license this is".
# Policy validation treats UNKNOWN as a deny by default (configurable via
# licenses.toml [licenses].unknown).
UNKNOWN = "UNKNOWN"


@dataclasses.dataclass(frozen=True)
class Component:
    """One row in the per-ecosystem NOTICES output and *-deps.csv."""

    ecosystem: str  # "rust" | "go" | "python" | "dpkg" | "native"
    name: str
    version: str
    spdx: str  # SPDX expression, possibly compound; UNKNOWN if unresolved
    source_url: str | None = None  # registry URL, where applicable
    license_text: str | None = None  # full LICENSE file contents, where available


_NOTICES_HEADER = """\
NOTICES — {ecosystem} dependencies
==================================

This file is automatically generated. Do not edit it directly.

It enumerates every {ecosystem} package shipped in this image, with its
SPDX license expression. Where the upstream LICENSE text is available,
it appears under each section; otherwise the SPDX identifier is the
authoritative reference.

"""


def render_notices(ecosystem: str, components: list[Component]) -> str:
    """Render a NOTICES-<Ecosystem>.txt file body.

    Components are sorted by name (case-insensitive) then version. The same
    component appearing multiple times (different versions) gets one section
    per version.
    """
    sorted_comps = sorted(components, key=lambda c: (c.name.lower(), c.version))

    parts: list[str] = [_NOTICES_HEADER.format(ecosystem=ecosystem)]
    for c in sorted_comps:
        parts.append(f"## {c.name} {c.version}\n\n")
        parts.append(f"License: {c.spdx}\n")
        if c.source_url:
            parts.append(f"Source: {c.source_url}\n")
        if c.license_text:
            parts.append("\n```\n")
            parts.append(c.license_text.rstrip() + "\n")
            parts.append("```\n")
        parts.append("\n")
    return "".join(parts)


def write_notices(
    ecosystem: str, components: list[Component], output_dir: Path
) -> Path:
    """Write NOTICES-<Ecosystem>.txt under output_dir; return its path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    notices_path = output_dir / f"NOTICES-{ecosystem.capitalize()}.txt"
    notices_path.write_text(
        render_notices(ecosystem, components), encoding="utf-8"
    )
    return notices_path


def write_deps_csv(
    ecosystem: str, components: list[Component], output_dir: Path
) -> Path:
    """Write <ecosystem>-deps.csv for the policy validator. Stable byte-order.

    Columns: ecosystem,name,version,spdx,source_url
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = output_dir / f"{ecosystem.lower()}-deps.csv"
    sorted_comps = sorted(components, key=lambda c: (c.name.lower(), c.version))
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(["ecosystem", "name", "version", "spdx", "source_url"])
        for c in sorted_comps:
            writer.writerow(
                [c.ecosystem, c.name, c.version, c.spdx, c.source_url or ""]
            )
    return csv_path


def load_subtract_keys(sbom_path: Path) -> set[tuple[str, str]]:
    """Load a baseline CycloneDX SBOM and return its (name, version) set.

    Used by the licenses stage to subtract baseline components from
    generator output so NOTICES attributes only what's above the baseline.
    Components without name+version are skipped silently (syft sometimes
    emits operating-system entries with no version).
    """
    if not sbom_path.is_file():
        raise FileNotFoundError(sbom_path)
    doc = json.loads(sbom_path.read_text(encoding="utf-8"))
    keys: set[tuple[str, str]] = set()
    for c in doc.get("components", []) or []:
        name = c.get("name")
        version = c.get("version")
        if name and version is not None:
            keys.add((name, str(version)))
    logger.info(
        "Loaded %d (name, version) keys for subtraction from %s",
        len(keys),
        sbom_path.name,
    )
    return keys


def subtract_baseline(
    components: list[Component], baseline_keys: set[tuple[str, str]]
) -> list[Component]:
    """Drop components whose (name, version) appears in baseline_keys.

    Logs the count of dropped components so build logs make the
    subtraction visible — auditors and engineers can see exactly how
    many components NGC/baseline-owners are owning.
    """
    if not baseline_keys:
        return components
    kept: list[Component] = []
    dropped = 0
    for c in components:
        if (c.name, c.version) in baseline_keys:
            dropped += 1
            continue
        kept.append(c)
    logger.info(
        "Subtracted %d baseline components; %d remain for NOTICES",
        dropped,
        len(kept),
    )
    return kept


def dedupe_by_name_version(components: list[Component]) -> list[Component]:
    """Collapse `(name, version)` duplicates. Keep the entry with the most
    license info: prefer non-UNKNOWN spdx, then license_text presence, then
    source_url presence.
    """
    by_key: dict[tuple[str, str], Component] = {}
    for c in components:
        key = (c.name, c.version)
        existing = by_key.get(key)
        if existing is None:
            by_key[key] = c
            continue
        if existing.spdx == UNKNOWN and c.spdx != UNKNOWN:
            by_key[key] = c
        elif (
            existing.spdx == c.spdx
            and not existing.license_text
            and c.license_text
        ):
            by_key[key] = c
    return list(by_key.values())
