# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Shared helpers for the per-ecosystem NOTICES generators."""

from __future__ import annotations

import csv
import dataclasses
import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# SPDX-expression sentinel that means "we don't know what license this is".
# Policy validation treats UNKNOWN as a deny by default (configurable via
# licenses.toml [licenses].unknown).
UNKNOWN = "UNKNOWN"

# Vendored canonical SPDX license texts (one <ID>.txt per allowed identifier,
# sourced from spdx/license-list-data). Used as the license-text source for
# ecosystems whose components ship no bundled LICENSE file in the licenses
# stage (rust, go) — see spdx_license_text().
_SPDX_TEXT_DIR = Path(__file__).resolve().parent.parent / "spdx_licenses"
_SPDX_OPERATORS = frozenset({"AND", "OR", "WITH"})


def _spdx_ids(spdx_expr: str) -> list[str]:
    """Extract the ordered, de-duplicated license/exception IDs in an SPDX
    expression, dropping operators and parentheses.

    "Apache-2.0 WITH LLVM-exception" -> ["Apache-2.0", "LLVM-exception"]
    "MIT OR Apache-2.0"              -> ["MIT", "Apache-2.0"]
    """
    ids: list[str] = []
    for tok in re.split(r"[()\s]+", spdx_expr or ""):
        tok = tok.strip().rstrip("+")  # normalize "Apache-2.0+" -> "Apache-2.0"
        if not tok or tok.upper() in _SPDX_OPERATORS:
            continue
        if tok not in ids:
            ids.append(tok)
    return ids


def read_harvested_license(base_dir: Path | None, key: str) -> str | None:
    """Read + concatenate the upstream LICENSE files harvested for `key`.

    The builder stages (wheel_builder for rust, the go-builders for go) copy
    each dependency's real LICENSE/COPYING/NOTICE files into `base_dir/<key>/`,
    mirroring the source-cache layout (rust: "<name>-<version>"; go: the
    escaped module path "<path>@<version>"). Returns None when base_dir is
    unset or no readable license files exist for the key, so callers fall back
    to canonical SPDX text.
    """
    if base_dir is None:
        return None
    pkg_dir = base_dir / key
    if not pkg_dir.is_dir():
        return None
    texts: list[str] = []
    for f in sorted(pkg_dir.iterdir()):
        if not f.is_file():
            continue
        try:
            body = f.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            continue
        if body:
            texts.append(f"--- {f.name} ---\n\n{body}")
    return "\n\n".join(texts) if texts else None


def spdx_license_text(spdx_expr: str) -> str | None:
    """Return the canonical SPDX license text(s) for an SPDX expression, or None.

    Looks up each referenced license/exception ID in the vendored
    spdx_licenses/ store. Compound expressions (e.g. "MIT OR Apache-2.0")
    yield the concatenated texts of every referenced ID, each under a
    `--- <ID> ---` banner. IDs with no vendored text (UNKNOWN, LicenseRef-*,
    or anything outside the policy allow-list) are skipped; returns None when
    nothing resolves so callers fall back to SPDX-identifier-only attribution.
    """
    if not spdx_expr or spdx_expr == UNKNOWN:
        return None
    chunks: list[str] = []
    for lid in _spdx_ids(spdx_expr):
        path = _SPDX_TEXT_DIR / f"{lid}.txt"
        if not path.is_file():
            continue
        try:
            body = path.read_text(encoding="utf-8").rstrip()
        except OSError:
            continue
        chunks.append(f"--- {lid} ---\n\n{body}")
    if not chunks:
        return None
    return "\n\n".join(chunks)


@dataclasses.dataclass(frozen=True)
class Component:
    """One row in the per-ecosystem NOTICES output and *-deps.csv."""

    ecosystem: str  # "rust" | "go" | "python" | "dpkg" | "native"
    name: str
    version: str
    spdx: str  # SPDX expression, possibly compound; UNKNOWN if unresolved
    source_url: str | None = None  # registry URL, where applicable
    license_text: str | None = None  # full LICENSE text, where available
    # True when license_text is the canonical SPDX text (the dependency shipped
    # no license file of its own); render_notices prepends a disclaimer.
    license_text_is_canonical: bool = False


_NOTICES_HEADER = """\
NOTICES — {ecosystem} dependencies
==================================

This file is automatically generated. Do not edit it directly.

It enumerates every {ecosystem} package shipped in this artifact (container
image or wheel), with its SPDX license expression. Where license text is
available — the package's
bundled LICENSE file, or the canonical SPDX text for its identifier — it
appears verbatim under each section; otherwise the SPDX identifier is the
authoritative reference.

"""

# Disclaimer printed above the license body when the text is the canonical
# SPDX text rather than a file the dependency itself distributed.
_CANONICAL_TEXT_NOTE = (
    "No license file was distributed with this package in the image; the "
    "canonical SPDX license text for its declared identifier is reproduced "
    "below for reference. See the Source URL above for the package's "
    "copyright holders."
)


def render_notices(ecosystem: str, components: list[Component]) -> str:
    """Render a NOTICES-<Ecosystem>.txt file body.

    Components are sorted by name (case-insensitive) then version. The same
    component appearing multiple times (different versions) gets one section
    per version.
    """
    sorted_comps = sorted(components, key=lambda c: (c.name.lower(), c.version))

    parts: list[str] = [_NOTICES_HEADER.format(ecosystem=ecosystem)]
    for c in sorted_comps:
        parts.append(f"## {c.name} {c.version}\n\n")
        parts.append(f"License: {c.spdx}\n")
        if c.source_url:
            parts.append(f"Source: {c.source_url}\n")
        if c.license_text:
            if c.license_text_is_canonical:
                parts.append(f"\n{_CANONICAL_TEXT_NOTE}\n")
            parts.append("\n```\n")
            parts.append(c.license_text.rstrip() + "\n")
            parts.append("```\n")
        parts.append("\n")
    return "".join(parts)


def write_notices(
    ecosystem: str, components: list[Component], output_dir: Path
) -> Path:
    """Write NOTICES-<Ecosystem>.txt under output_dir; return its path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    notices_path = output_dir / f"NOTICES-{ecosystem.capitalize()}.txt"
    notices_path.write_text(render_notices(ecosystem, components), encoding="utf-8")
    return notices_path


def write_deps_csv(
    ecosystem: str, components: list[Component], output_dir: Path
) -> Path:
    """Write <ecosystem>-deps.csv for the policy validator. Stable byte-order.

    Columns: ecosystem,name,version,spdx,source_url
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = output_dir / f"{ecosystem.lower()}-deps.csv"
    sorted_comps = sorted(components, key=lambda c: (c.name.lower(), c.version))
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(["ecosystem", "name", "version", "spdx", "source_url"])
        for c in sorted_comps:
            writer.writerow(
                [c.ecosystem, c.name, c.version, c.spdx, c.source_url or ""]
            )
    return csv_path


def load_subtract_keys(sbom_path: Path) -> set[tuple[str, str]]:
    """Load a baseline CycloneDX SBOM and return its (name, version) set.

    Used by the licenses stage to subtract baseline components from
    generator output so NOTICES attributes only what's above the baseline.
    Components without name+version are skipped silently (syft sometimes
    emits operating-system entries with no version).
    """
    if not sbom_path.is_file():
        raise FileNotFoundError(sbom_path)
    doc = json.loads(sbom_path.read_text(encoding="utf-8"))
    keys: set[tuple[str, str]] = set()
    for c in doc.get("components", []) or []:
        name = c.get("name")
        version = c.get("version")
        if name and version is not None:
            keys.add((name, str(version)))
    logger.info(
        "Loaded %d (name, version) keys for subtraction from %s",
        len(keys),
        sbom_path.name,
    )
    return keys


def subtract_baseline(
    components: list[Component], baseline_keys: set[tuple[str, str]]
) -> list[Component]:
    """Drop components whose (name, version) appears in baseline_keys.

    Logs the count of dropped components so build logs make the
    subtraction visible — auditors and engineers can see exactly how
    many components NGC/baseline-owners are owning.
    """
    if not baseline_keys:
        return components
    kept: list[Component] = []
    dropped = 0
    for c in components:
        if (c.name, c.version) in baseline_keys:
            dropped += 1
            continue
        kept.append(c)
    logger.info(
        "Subtracted %d baseline components; %d remain for NOTICES",
        dropped,
        len(kept),
    )
    return kept


def dedupe_by_name_version(components: list[Component]) -> list[Component]:
    """Collapse `(name, version)` duplicates. Keep the entry with the most
    license info: prefer non-UNKNOWN spdx, then license_text presence, then
    source_url presence.
    """
    by_key: dict[tuple[str, str], Component] = {}
    for c in components:
        key = (c.name, c.version)
        existing = by_key.get(key)
        if existing is None:
            by_key[key] = c
            continue
        if existing.spdx == UNKNOWN and c.spdx != UNKNOWN:
            by_key[key] = c
        elif existing.spdx == c.spdx and not existing.license_text and c.license_text:
            by_key[key] = c
    return list(by_key.values())
