//go:build !clustertest

/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package controller

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	configv1alpha1 "github.com/ai-dynamo/dynamo/deploy/operator/api/config/v1alpha1"
	commoncontroller "github.com/ai-dynamo/dynamo/deploy/operator/internal/controller_common"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/features"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/podcache"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/testing/golden"
	grovemock "github.com/ai-dynamo/dynamo/deploy/operator/internal/testing/mocks/grove"
	lwsmock "github.com/ai-dynamo/dynamo/deploy/operator/internal/testing/mocks/lws"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/testing/operatorenv"
	"github.com/ai-dynamo/dynamo/deploy/operator/internal/testing/webhookconfig"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/utils/ptr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
	controllerconfig "sigs.k8s.io/controller-runtime/pkg/config"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

// manifestNamespacePrefix mirrors the namespace prefix generated by clusterenv
// so the shared golden contracts under testdata match in both environments.
const manifestNamespacePrefix = "clusterenv-"

const manifestEnvEventuallyTimeout = time.Minute

// TestDynamoComponentDeploymentManifestsEnvtest runs the DCD golden scenarios
// against envtest. It is the local, docker-free counterpart of the
// clustertest-only TestClusterDynamoComponentDeploymentManifests and asserts
// the same committed contracts, so authoring a scenario no longer requires
// Kind. CI still runs the clustertest variant against a real cluster.
func TestDynamoComponentDeploymentManifestsEnvtest(t *testing.T) {
	inputs, err := filepath.Glob(filepath.Join("testdata/dcd", "*", "input.yaml"))
	if err != nil {
		t.Fatalf("find DCD scenarios: %v", err)
	}
	if len(inputs) == 0 {
		t.Fatal("no DCD scenarios found")
	}

	env := newManifestEnv(t).RunT(t)
	goldenClient := goldenCompatibilityClient{Client: env.Client()}
	for _, input := range inputs {
		scenarioDir := filepath.Dir(input)
		t.Run(filepath.Base(scenarioDir), func(t *testing.T) {
			t.Log("Create an isolated namespace named like a cluster-test namespace")
			namespace := createManifestNamespace(t, env)

			t.Log("Apply the scenario input manifests through Kubernetes admission")
			golden.ApplyManifests(t, filepath.Join(scenarioDir, "input.yaml"), env.Client(), namespace)

			t.Log("Start the DynamoComponentDeployment controller")
			operatorConfig := manifestRestrictedConfig(namespace)
			runtimeConfig := &commoncontroller.RuntimeConfig{Gate: features.Gates{Grove: true, LWS: true}}
			startManifestManager(t, env, namespace, func(mgr ctrl.Manager) error {
				setupOptions := SetupOptions{Config: operatorConfig, RuntimeConfig: runtimeConfig}
				return SetupDynamoComponentDeployment(mgr, DynamoComponentDeploymentSetupOptions{SetupOptions: setupOptions})
			})

			t.Log("Wait for the complete generated manifest contract")
			golden.EventuallyMatchManifests(t, goldenClient, namespace, filepath.Join(scenarioDir, "output.yaml"))
		})
	}
}

// goldenCompatibilityClient reads through to envtest and normalizes the one
// serialization difference between the envtest API server pinned by
// ENVTEST_K8S_VERSION (1.30.0) and the Kind node image used by the cluster
// tests (v1.36.1): a 1.30 API server echoes `creationTimestamp: null` inside
// embedded ObjectMeta such as Deployment spec.template.metadata, while a 1.36
// one omits it. The committed contracts describe the current API server, so the
// local runner drops the explicit nulls rather than weakening the contracts.
// Remove this shim once ENVTEST_K8S_VERSION reaches an API server that omits
// them.
type goldenCompatibilityClient struct {
	client.Client
}

func (c goldenCompatibilityClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	if err := c.Client.List(ctx, list, opts...); err != nil {
		return err
	}
	unstructuredList, isUnstructured := list.(*unstructured.UnstructuredList)
	if !isUnstructured {
		return nil
	}
	for i := range unstructuredList.Items {
		dropNullCreationTimestamps(unstructuredList.Items[i].Object)
	}
	return nil
}

func dropNullCreationTimestamps(value any) {
	switch typed := value.(type) {
	case map[string]any:
		if timestamp, found := typed["creationTimestamp"]; found && timestamp == nil {
			delete(typed, "creationTimestamp")
		}
		for _, child := range typed {
			dropNullCreationTimestamps(child)
		}
	case []any:
		for _, child := range typed {
			dropNullCreationTimestamps(child)
		}
	}
}

// newManifestEnv builds an envtest environment that installs the same admission
// chain as the cluster-test environment: the Helm-rendered operator webhooks
// plus the dependency webhooks that default LeaderWorkerSet and PodCliqueSet.
func newManifestEnv(t *testing.T) *operatorenv.Env {
	t.Helper()

	return operatorenv.New(operatorenv.Options{
		Admission: operatorenv.AdmissionWebhooks{Mutating: true, Validating: true},
		// LeaderWorkerSet defaults spec.networkConfig and spec.rolloutStrategy in
		// its mutating webhook rather than in its CRD, so the golden contract only
		// reproduces when that webhook is installed.
		AdditionalAdmission: dependencyAdmissionConfigurations(),
		SetupWebhooks: func(mgr ctrl.Manager, opts operatorenv.WebhookSetupOptions) error {
			if err := setupProductionWebhooks(mgr, opts); err != nil {
				return err
			}
			if err := lwsmock.Setup(mgr); err != nil {
				return err
			}
			return grovemock.Setup(mgr)
		},
		RuntimeConfig:     &commoncontroller.RuntimeConfig{Gate: features.Gates{Grove: true, LWS: true}},
		CRDDirectoryPaths: manifestCRDDirectoryPaths(t),
		EventuallyTimeout: manifestEnvEventuallyTimeout,
	})
}

func dependencyAdmissionConfigurations() webhookconfig.Configurations {
	configurations := lwsmock.Configurations()
	grove := grovemock.Configurations()
	configurations.Mutating = append(configurations.Mutating, grove.Mutating...)
	configurations.Validating = append(configurations.Validating, grove.Validating...)
	return configurations
}

// manifestCRDDirectoryPaths returns the operator CRDs, the vendored dependency
// CRDs, and the LeaderWorkerSet CRDs resolved from the module cache. envtest
// ships no dependency CRDs, and the lws scenario renders a LeaderWorkerSet.
func manifestCRDDirectoryPaths(t *testing.T) []string {
	t.Helper()

	root := filepath.Join("..", "..")
	paths := []string{
		filepath.Join(root, "config", "crd", "bases"),
		filepath.Join(root, "internal", "controller", "testing", "prometheus"),
		filepath.Join(root, "internal", "controller", "testing", "volcano.sh"),
		filepath.Join(root, "internal", "controller", "testing", "run.ai"),
		filepath.Join(root, "internal", "controller", "testing", "inference.networking.k8s.io"),
		filepath.Join(root, "internal", "controller", "testing", "grove.io"),
	}
	paths = append(paths, filepath.Join(moduleDirectory(t, "sigs.k8s.io/lws"), "config", "crd", "bases"))
	return append(paths, writeVolcanoPodGroupCRD(t))
}

// volcanoPodGroupCRD defines the scheduling.volcano.sh/v1beta1 PodGroup type.
// The DynamoComponentDeployment controller owns PodGroups whenever the LWS gate
// is on, so its watches never start without this type and no manifest is ever
// rendered. The Kind cluster installs Volcano's published CRD from the network
// (setup-clustertest in the Makefile); a test must not depend on the network,
// and the operator only lists and deletes PodGroups, so a permissive schema is
// equivalent here.
const volcanoPodGroupCRD = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.volcano.sh
spec:
  group: scheduling.volcano.sh
  names:
    kind: PodGroup
    listKind: PodGroupList
    plural: podgroups
    singular: podgroup
    shortNames:
    - pg
    - podgroup-v1beta1
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
`

func writeVolcanoPodGroupCRD(t *testing.T) string {
	t.Helper()

	directory := t.TempDir()
	path := filepath.Join(directory, "scheduling.volcano.sh_podgroups.yaml")
	if err := os.WriteFile(path, []byte(volcanoPodGroupCRD), 0o600); err != nil {
		t.Fatalf("write Volcano PodGroup CRD: %v", err)
	}
	return directory
}

func moduleDirectory(t *testing.T, module string) string {
	t.Helper()

	output, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", module).Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			t.Fatalf("locate module %q: %v: %s", module, err, exitErr.Stderr)
		}
		t.Fatalf("locate module %q: %v", module, err)
	}
	directory := strings.TrimSpace(string(output))
	if directory == "" {
		t.Fatalf("module %q has no local directory; run go mod download", module)
	}
	return directory
}

func manifestRestrictedConfig(namespace string) *configv1alpha1.OperatorConfiguration {
	config := &configv1alpha1.OperatorConfiguration{}
	configv1alpha1.SetDefaultsOperatorConfiguration(config)
	config.Namespace.Restricted = namespace
	config.GPU.DiscoveryEnabled = ptr.To(false)
	return config
}

// createManifestNamespace creates a clusterenv-prefixed namespace. The prefix
// is part of the committed contracts, which assert the generated Dynamo
// namespace with $pattern:clusterenv-.*.
func createManifestNamespace(t *testing.T, env *operatorenv.TestEnv) string {
	t.Helper()

	namespace := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{GenerateName: manifestNamespacePrefix}}
	if err := env.Client().Create(t.Context(), namespace); err != nil {
		t.Fatalf("create scenario namespace: %v", err)
	}
	return namespace.Name
}

// startManifestManager starts a manager scoped to namespace. It mirrors
// operatorenv.TestEnv.StartManager, which is bound to the environment's own
// namespace rather than the scenario namespace.
func startManifestManager(t *testing.T, env *operatorenv.TestEnv, namespace string, setup func(ctrl.Manager) error) {
	t.Helper()

	skipNameValidation := true
	cacheOptions := cache.Options{DefaultNamespaces: map[string]cache.Config{namespace: {}}}
	if err := podcache.Configure(&cacheOptions); err != nil {
		t.Fatalf("configure Pod cache: %v", err)
	}
	mgr, err := ctrl.NewManager(env.RESTConfig(), ctrl.Options{
		Scheme:     env.Scheme(),
		Metrics:    metricsserver.Options{BindAddress: "0"},
		Cache:      cacheOptions,
		Controller: controllerconfig.Controller{SkipNameValidation: &skipNameValidation},
	})
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	if err := setup(mgr); err != nil {
		t.Fatalf("setup manager: %v", err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() {
		done <- mgr.Start(ctx)
	}()
	t.Cleanup(func() {
		cancel()
		if err := <-done; err != nil && !errors.Is(err, context.Canceled) {
			t.Errorf("manager stopped with error: %v", err)
		}
	})
	syncCtx, syncCancel := context.WithTimeout(context.Background(), manifestEnvEventuallyTimeout)
	defer syncCancel()
	if !mgr.GetCache().WaitForCacheSync(syncCtx) {
		t.Fatal("manager cache did not sync")
	}
}
