# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

dcgmExporter:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

operator:
  defaultRuntime: containerd
