# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

driver:
  kind: modern_ebpf

falcosidekick:
  enabled: true
  webui:
    enabled: false

collectors:
  kubernetes:
    enabled: true

falco:
  json_output: true
  priority: warning
