# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

driver:
  kind: modern_ebpf
  modernEbpf:
    cpusForEachBuffer: 16

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

falcosidekick:
  enabled: true
  webui:
    enabled: false

collectors:
  kubernetes:
    enabled: true

extra:
  initContainers:
    - name: tune-inotify
      image: busybox:1.37
      securityContext:
        privileged: true
      command:
        - /bin/sh
        - -c
      args:
        - |
          sysctl -w fs.inotify.max_user_instances=8192
          sysctl -w fs.inotify.max_queued_events=32768

falco:
  json_output: true
  priority: warning
