# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Shared helpers for Fern API doc generators."""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

SPDX_HEADER = """\
---
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
sidebar-title: {sidebar_title}
---
"""

AUTOGEN_WARNING = (
    "> **Warning**: This documentation is automatically generated from source code.\n"
    "> Do not edit this file directly.\n"
)


def escape_jsx_attr(text: str) -> str:
    """Escape text for use inside a double-quoted HTML/JSX attribute."""
    return (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def escape_mdx_prose(text: str) -> str:
    """Escape MDX-sensitive characters in prose text.

    Protects backtick code spans, wraps brace patterns in inline code,
    and escapes remaining braces and angle brackets.
    """
    spans: list[str] = []

    def _protect(m: re.Match) -> str:
        spans.append(m.group(0))
        return f"\x01{len(spans) - 1}\x01"

    # Protect existing code spans
    text = re.sub(r"`[^`]+`", _protect, text)
    # Wrap brace expressions in code spans
    text = re.sub(r"\{[^{}]*\}", lambda m: f"`{m.group(0)}`", text)
    # Protect newly created code spans
    text = re.sub(r"`[^`]+`", _protect, text)
    # Escape remaining braces and angle brackets
    text = text.replace("{", "\\{").replace("}", "\\}")
    text = text.replace("<", "&lt;")
    # Restore protected spans via re.sub callback (O(n) instead of O(n*m))
    text = re.sub(r"\x01(\d+)\x01", lambda m: spans[int(m.group(1))], text)
    return text


def slugify(text: str) -> str:
    """Convert text to a URL-safe anchor slug."""
    return text.lower().replace(" ", "-").replace(",", "")


def render_details(summary: str, body: str) -> str:
    """Render a <details>/<summary> block (GitHub + Fern compatible).

    Blank line after <summary> is required for GitHub to render markdown.
    """
    return (
        "<details>\n"
        f"<summary><strong>{summary}</strong></summary>\n"
        f"\n{body}\n\n"
        "</details>\n"
    )
