# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Shared helpers for Fern API doc generators."""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

SPDX_HEADER = """\
---
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
sidebar-title: {sidebar_title}
---
"""

AUTOGEN_WARNING = (
    "> **Warning**: This documentation is automatically generated from source code.\n"
    "> Do not edit this file directly.\n"
)


def escape_jsx_attr(text: str) -> str:
    """Escape text for use inside a double-quoted HTML/JSX attribute."""
    return (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


_CODE_SPAN_RE = re.compile(r"`[^`]+`")
_BRACE_EXPR_RE = re.compile(r"\{[^{}]*\}")
_PLACEHOLDER_RE = re.compile(r"\x01(\d+)\x01")


def escape_mdx_prose(text: str) -> str:
    """Escape MDX-sensitive characters in prose text.

    Protects backtick code spans, wraps brace patterns in inline code,
    and escapes remaining braces and angle brackets.
    """
    spans: list[str] = []

    def _protect(m: re.Match) -> str:
        spans.append(m.group(0))
        return f"\x01{len(spans) - 1}\x01"

    text = _CODE_SPAN_RE.sub(_protect, text)
    text = _BRACE_EXPR_RE.sub(lambda m: f"`{m.group(0)}`", text)
    text = _CODE_SPAN_RE.sub(_protect, text)
    text = text.replace("{", "\\{").replace("}", "\\}")
    text = text.replace("<", "&lt;")
    text = _PLACEHOLDER_RE.sub(lambda m: spans[int(m.group(1))], text)
    return text


def slugify(text: str) -> str:
    """Convert text to a URL-safe anchor slug."""
    return text.lower().replace(" ", "-").replace(",", "")


def render_card_group(cards: list[dict[str, str]], cols: int) -> str:
    """Render a Fern <CardGroup> with <Card> elements.

    Each card dict must have 'title', 'icon', 'description'.
    Optional 'href' adds a link. Values are escaped for JSX attributes.
    """
    parts = [f"<CardGroup cols={{{cols}}}>\n"]
    for card in cards:
        title = escape_jsx_attr(card["title"])
        icon = escape_jsx_attr(card["icon"])
        href = f' href="{escape_jsx_attr(card["href"])}"' if card.get("href") else ""
        parts.append(
            f'  <Card title="{title}" icon="{icon}"{href}>\n'
            f'    {card["description"]}\n'
            f"  </Card>\n"
        )
    parts.append("</CardGroup>\n")
    return "".join(parts)


def details_title(name: str, description: str) -> str:
    """Build an escaped title for a <details> summary."""
    if description:
        return escape_jsx_attr(f"{name} \u2014 {description}")
    return name


def render_details(summary: str, body: str) -> str:
    """Render a <details>/<summary> block (GitHub + Fern compatible).

    Blank line after <summary> is required for GitHub to render markdown.
    """
    return (
        "<details>\n"
        f"<summary><strong>{summary}</strong></summary>\n"
        f"\n{body}\n\n"
        "</details>\n"
    )
