#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Transform the Rust API reference Markdown into Fern MDX.

Reads docs/api/rust/README.md (generated by generate_rust_api.py)
and converts Markdown tables into Fern CardGroup components.

Usage (from repository root):
    python3 docs/scripts/fernify_rust_api.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _fern_helpers import REPO_ROOT, fernify_table_to_cards  # noqa: E402

sys.path.insert(0, str(REPO_ROOT / "fern"))
from convert_callouts import convert_admonitions  # noqa: E402

DEFAULT_INPUT = REPO_ROOT / "docs" / "api" / "rust" / "README.md"

CRATE_ICONS: dict[str, str] = {
    "dynamo-runtime": "regular microchip",
    "dynamo-llm": "regular brain",
    "dynamo-kv-router": "regular route",
    "dynamo-memory": "regular memory",
    "kvbm-logical": "regular cubes",
    "dynamo-config": "regular gear",
    "dynamo-parsers": "regular code",
    "dynamo-mocker": "regular vial",
    "dynamo-async-openai": "regular globe",
}


def fernify(text: str) -> str:
    """Apply all Fern transforms to the Rust API page."""
    text = fernify_table_to_cards(text, CRATE_ICONS)
    text = convert_admonitions(text)
    return text


def main() -> None:
    """Entry point: fernify the Rust API reference in-place."""
    input_path = DEFAULT_INPUT
    if not input_path.exists():
        sys.exit(f"Input file not found: {input_path}")

    print(f"Fernifying {input_path}...")
    content = fernify(input_path.read_text())
    input_path.write_text(content)
    print(f"  -> {input_path} ({content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
