# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-dsr1
spec:
  backendFramework: vllm
  pvcs:
    - name: model-cache
      create: false
  services:
    Epp:
      envFromSecret: hf-token-secret
      componentType: epp
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: docker.io/lambda108/epp-inference-extension-dynamo:fix-header
          imagePullPolicy: Always
          env:
            - name: DYN_KV_CACHE_BLOCK_SIZE
              value: "128"
            - name: DYN_MODEL_NAME
              value: "deepseek-ai/DeepSeek-R1"
      eppConfig:
        config:
          plugins:
            - type: disagg-profile-handler
            - name: prefill-filter
              type: label-filter
              parameters:
                label: "nvidia.com/dynamo-sub-component-type"
                validValues:
                  - "prefill"
                allowsNoLabel: false
            - name: decode-filter
              type: label-filter
              parameters:
                label: "nvidia.com/dynamo-sub-component-type"
                validValues:
                  - "decode"
                allowsNoLabel: false
            - name: picker
              type: max-score-picker
            - name: dyn-prefill
              type: dyn-prefill-scorer
            - name: dyn-decode
              type: dyn-decode-scorer
          schedulingProfiles:
          - name: prefill
            plugins:
            - pluginRef: prefill-filter
              weight: 0
            - pluginRef: dyn-prefill
              weight: 1
            - pluginRef: picker
              weight: 0
          - name: decode
            plugins:
            - pluginRef: decode-filter
              weight: 0
            - pluginRef: dyn-decode
              weight: 1
            - pluginRef: picker
              weight: 0
    decode:
      componentType: worker
      subComponentType: decode
      envFromSecret: hf-token-secret
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "8"
          custom:
            rdma/ib: "8"
      volumeMounts:
        - name: model-cache
          mountPoint: /model-cache
      sharedMemory:
        size: 80Gi
      extraPodSpec:
        mainContainer:
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 600
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.0
          workingDir: /workspace/dynamo
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "1"
            - name: VLLM_MOE_DP_CHUNK_SIZE
              value: "384"
            - name: VLLM_SKIP_P2P_CHECK
              value: "1"
            - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
              value: "1"
            - name: NVIDIA_GDRCOPY
              value: enabled
            - name: GLOO_SOCKET_IFNAME
              value: eth0
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model
            - /model-cache/deepseek-r1
            - --served-model-name
            - deepseek-ai/DeepSeek-R1
            - --all2all-backend
            - deepep_low_latency
            - --data-parallel-hybrid-lb
            - --tensor-parallel-size
            - "1"
            - --data-parallel-size
            - "16"
            - --enable-expert-parallel
            - --max-model-len
            - "16384"
            - --enable-dbo
            - --dbo-decode-token-threshold
            - "32"
            - --async-scheduling
            - --enable-eplb
            - --eplb-config
            - '{"window_size":"1000","step_interval":"3000","num_redundant_experts":"32","log_balancedness":"False"}'
            - --max-num-seqs
            - "512"
            - --compilation_config
            - '{"pass_config":{"fuse_norm_quant":true,"eliminate_noops":true},"cudagraph_mode":"FULL_DECODE_ONLY"}'
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
        containers:
          - name: frontend
            image: docker.io/lambda108/dynamo:fix-header
            imagePullPolicy: Always
            command:
              - python3
            args:
              - -m
              - dynamo.frontend
              - --router-mode
              - direct
            ports:
              - containerPort: 8000
                name: http
                protocol: TCP
            envFrom:
              - secretRef:
                  name: hf-token-secret
            env:
              - name: DYNAMO_PORT
                value: "8000"
              - name: DYN_HTTP_PORT
                value: "8000"
              - name: DYN_NAMESPACE
                value: a-epp-vllm-dsr1
              - name: DYN_COMPONENT
                value: frontend
              - name: DYN_DISCOVERY_BACKEND
                value: kubernetes
              - name: DYN_PARENT_DGD_K8S_NAME
                value: vllm-dsr1
              - name: DYN_PARENT_DGD_K8S_NAMESPACE
                value: a-epp
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_UID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
              - name: DYN_LOG
                value: "info,dynamo_llm::protocols::openai::nvext=debug,dynamo_llm::kv_router::push_router=debug"
            livenessProbe:
              httpGet:
                path: /live
                port: http
              initialDelaySeconds: 15
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
    prefill:
      componentType: worker
      subComponentType: prefill
      envFromSecret: hf-token-secret
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "8"
          custom:
            rdma/ib: "8"
      volumeMounts:
        - name: model-cache
          mountPoint: /model-cache
      sharedMemory:
        size: 80Gi
      extraPodSpec:
        mainContainer:
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 600
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.0
          workingDir: /workspace/dynamo
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "1"
            - name: VLLM_SKIP_P2P_CHECK
              value: "1"
            - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
              value: "1"
            - name: NVIDIA_GDRCOPY
              value: enabled
            - name: GLOO_SOCKET_IFNAME
              value: eth0
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model
            - /model-cache/deepseek-r1
            - --disaggregation-mode
            - prefill
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
            - --served-model-name
            - deepseek-ai/DeepSeek-R1
            - --all2all-backend
            - deepep_high_throughput
            - --data-parallel-hybrid-lb
            - --tensor-parallel-size
            - "1"
            - --data-parallel-size
            - "16"
            - --enable-expert-parallel
            - --max-model-len
            - "16384"
            - --enable-dbo
            - --dbo-decode-token-threshold
            - "32"
            - --async-scheduling
            - --enable-eplb
            - --eplb-config
            - '{"window_size":"1000","step_interval":"3000","num_redundant_experts":"32","log_balancedness":"False"}'
            - --max-num-seqs
            - "512"
        containers:
          - name: frontend
            image: docker.io/lambda108/dynamo:fix-header
            imagePullPolicy: Always
            command:
              - python3
            args:
              - -m
              - dynamo.frontend
              - --router-mode
              - direct
            ports:
              - containerPort: 8000
                name: http
                protocol: TCP
            envFrom:
              - secretRef:
                  name: hf-token-secret
            env:
              - name: DYNAMO_PORT
                value: "8000"
              - name: DYN_HTTP_PORT
                value: "8000"
              - name: DYN_NAMESPACE
                value: a-epp-vllm-dsr1
              - name: DYN_COMPONENT
                value: frontend
              - name: DYN_DISCOVERY_BACKEND
                value: kubernetes
              - name: DYN_PARENT_DGD_K8S_NAME
                value: vllm-dsr1
              - name: DYN_PARENT_DGD_K8S_NAMESPACE
                value: a-epp
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_UID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
              - name: DYN_LOG
                value: "info,dynamo_llm::protocols::openai::nvext=debug,dynamo_llm::kv_router::push_router=debug"
            livenessProbe:
              httpGet:
                path: /live
                port: http
              initialDelaySeconds: 15
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
