# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib

admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
