apiVersion: v1
kind: Secret
metadata:
  name: compoundai-deployment-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "compoundai-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_ENDPOINT: {{ .Values.compoundai.yatai.endpoint | quote }}
  YATAI_CLUSTER_NAME: {{ .Values.compoundai.yatai.clusterName | quote }}
  YATAI_SYSTEM_NAMESPACE: {{ default .Release.Namespace .Values.compoundai.yataiSystem.namespace }}
  YATAI_DEPLOYMENT_NAMESPACE: {{ .Release.Namespace }}
  YATAI_IMAGE_BUILDER_NAMESPACE: {{ .Release.Namespace }}

  YATAI_API_TOKEN: {{ include "compoundai-operator.yataiApiToken" . | quote }}

  INTERNAL_IMAGES_METRICS_TRANSFORMER: {{ .Values.compoundai.internalImages.metricsTransformer | quote }}
  INTERNAL_IMAGES_DEBUGGER: {{ .Values.compoundai.internalImages.debugger | quote }}
  INTERNAL_IMAGES_MONITOR_EXPORTER: {{ .Values.compoundai.internalImages.monitorExporter | quote }}
  INTERNAL_IMAGES_PROXY: {{ .Values.compoundai.internalImages.proxy | quote }}

  {{- if .Values.compoundai.disableAutomateBentoImageBuilder }}
  DISABLE_AUTOMATE_BENTO_IMAGE_BUILDER: "true"
  {{- end }}

  {{- if .Values.compoundai.enableRestrictedSecurityContext }}
  ENABLE_RESTRICTED_SECURITY_CONTEXT: "true"
  {{- end }}


  DOCKER_REGISTRY_SERVER: {{ .Values.compoundai.dockerRegistry.server | quote }}
  DOCKER_REGISTRY_IN_CLUSTER_SERVER: {{ .Values.compoundai.dockerRegistry.inClusterServer | quote }}
  DOCKER_REGISTRY_USERNAME: {{ .Values.compoundai.dockerRegistry.username | quote }}
  {{- if not .Values.compoundai.dockerRegistry.passwordExistingSecretName }}
  DOCKER_REGISTRY_PASSWORD: {{ default .Values.global.NGC_API_KEY .Values.compoundai.dockerRegistry.password | quote }}
  {{- end }}
  DOCKER_REGISTRY_SECURE: {{ .Values.compoundai.dockerRegistry.secure | quote }}
  DOCKER_REGISTRY_BENTO_REPOSITORY_NAME: {{ .Values.compoundai.dockerRegistry.bentoRepositoryName | quote }}

  INTERNAL_IMAGES_BENTO_DOWNLOADER: {{ .Values.compoundai.internalImages.bentoDownloader | quote }}
  INTERNAL_IMAGES_KANIKO: {{ .Values.compoundai.internalImages.kaniko | quote }}
  INTERNAL_IMAGES_BUILDKIT: {{ .Values.compoundai.internalImages.buildkit | quote }}
  INTERNAL_IMAGES_BUILDKIT_ROOTLESS: {{ .Values.compoundai.internalImages.buildkitRootless | quote }}

  BENTO_IMAGE_BUILD_ENGINE: {{ .Values.compoundai.bentoImageBuildEngine | quote }}

  DISABLE_YATAI_COMPONENT_REGISTRATION: {{ .Values.compoundai.disableYataiComponentRegistration | quote }}

  ADD_NAMESPACE_PREFIX_TO_IMAGE_NAME: {{ .Values.compoundai.addNamespacePrefixToImageName | quote }}

  ESTARGZ_ENABLED: {{ .Values.compoundai.estargz.enabled | quote }}

  KANIKO_CACHE_REPO: {{ .Values.compoundai.kaniko.cacheRepo | quote }}
  KANIKO_SNAPSHOT_MODE: {{ .Values.compoundai.kaniko.snapshotMode | quote }}