apiVersion: v1
kind: Secret
metadata:
  name: compoundai-deployment-shared-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "compoundai-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  BENTO_DEPLOYMENT_ALL_NAMESPACES: "false"
  BENTO_DEPLOYMENT_NAMESPACES: {{ default .Release.Namespace .Values.compoundai.yataiSystem.namespace }}
  YATAI_DEPLOYMENT_NAMESPACE: {{ default .Release.Namespace .Values.compoundai.yataiSystem.namespace }}