apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "compoundai-operator.fullname" . }}-compoundainim-viewer-role
  labels:
  {{- include "compoundai-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - nvidia.com
  resources:
  - compoundainims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - compoundainims/status
  verbs:
  - get