apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compoundai-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compoundai-operator
    app.kubernetes.io/part-of: compoundai-operator
  {{- include "compoundai-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}