apiVersion: v1
kind: Secret
metadata:
  name: yatai-regcred
  labels:
    {{- include "compoundai-operator.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "compoundai-operator.dockerconfig" . | b64enc }} 