# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: fastvideo-agg
spec:
  pvcs:
    - name: model-cache
      create: false
  services:
    Frontend:
      componentType: frontend
      replicas: 1
      envs:
        - name: DYN_DISCOVERY_BACKEND
          value: kubernetes
      extraPodSpec:
        mainContainer:
          image: my-registry/fastvideo-runtime:my-tag
          imagePullPolicy: IfNotPresent
          workingDir: /opt/app
          command:
            - python
            - -m
            - dynamo.frontend
          args:
            - --http-port
            - "8000"

    FastVideoWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      sharedMemory:
        size: 8Gi
      resources:
        limits:
          gpu: "1"
        requests:
          gpu: "1"
      volumeMounts:
        - name: model-cache
          mountPoint: /opt/models
      envs:
        - name: DYN_DISCOVERY_BACKEND
          value: kubernetes
        - name: LD_LIBRARY_PATH
          value: ""
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: expandable_segments:True
        - name: HF_HOME
          value: /opt/models
      extraPodSpec:
        mainContainer:
          image: my-registry/fastvideo-runtime:my-tag
          imagePullPolicy: IfNotPresent
          workingDir: /opt/app
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          command:
            - python
            - -m
            - dynamo.fastvideo
          args:
            - --model-path
            - Wan-AI/Wan2.1-T2V-1.3B-Diffusers
