# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate vLLM admission vocabulary from pinned native-server declarations.

This vocabulary identifies known fields, NOT supported fields. Admission uses it
only to prevent silent dropping. Backend/version capability checks remain separate.
No upstream modules are imported or executed. Run --check in version-bump CI.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scripts.protocol_compatibility.common.provenance import digest
from scripts.protocol_compatibility.extraction.python_source import snapshot

from ..common.paths import OUTPUT
from ..extraction.request_fields import REQUESTS, request_fields


def build_inventory(repo: Path, pins: dict[str, Any]) -> dict[str, Any]:
    if pins["format_version"] != 1 or pins["target"] != "vllm":
        raise ValueError("unsupported pin format or target")
    profiles = []
    for pin in pins["versions"]:
        upstream = snapshot(repo, pin["commit"], "vllm")
        profiles.append(
            {
                **pin,
                "source_inventory_sha256": digest(upstream),
                "endpoints": {
                    endpoint: request_fields(upstream, request)
                    for endpoint, request in REQUESTS.items()
                },
            }
        )
    return {
        "generated": "DO NOT EDIT: python -m scripts.protocol_compatibility generate-inventory",
        "format_version": 1,
        "target": "vllm",
        "repository": pins["repository"],
        "meaning": "Declaration inventory only; membership does not claim support or parity.",
        "profiles": profiles,
    }


def rust_vocabulary(inventory: dict[str, Any]) -> str:
    fields = sorted(
        {
            name
            for profile in inventory["profiles"]
            for endpoint in profile["endpoints"].values()
            for field in endpoint.values()
            for name in field["wire_names"]
        }
    )
    versions = ", ".join(profile["version"] for profile in inventory["profiles"])
    lines = [
        "// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
        "// SPDX-License-Identifier: Apache-2.0",
        "",
        "// DO NOT EDIT: generated by python -m scripts.protocol_compatibility generate-inventory.",
        f"// Inventory SHA256: {digest(inventory)}",
        "// Known native fields are not necessarily supported by Dynamo.",
        f'pub(super) const VLLM_VERSIONS: &str = "{versions}";',
        "pub(super) const VLLM_REQUEST_FIELDS: &[&str] = &[",
        *(f"    {json.dumps(field)}," for field in fields),
        "];",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream-repo", type=Path, required=True)
    parser.add_argument("--pins", type=Path, default=OUTPUT / "vllm_pins.json")
    parser.add_argument("--output-dir", type=Path, default=OUTPUT)
    parser.add_argument(
        "--inventory-output",
        type=Path,
        help="optionally write/check the detailed JSON at this path; not required in Git",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    inventory = build_inventory(args.upstream_repo, json.loads(args.pins.read_text()))
    outputs = {
        "vllm_fields.rs": rust_vocabulary(inventory),
    }
    if args.inventory_output:
        outputs[str(args.inventory_output.resolve())] = (
            json.dumps(inventory, indent=2, sort_keys=True) + "\n"
        )
    stale = []
    for name, contents in outputs.items():
        path = args.output_dir / name
        if args.check:
            if not path.exists() or path.read_text() != contents:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    if stale:
        parser.exit(1, "Stale generated inventory: " + ", ".join(stale) + "\n")
    return 0
