# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM local/dynamo-planner:lora-e2e

COPY --chown=1000:0 lib/llm/tests/data/sample-models/mock-llama-3.1-8b-instruct /opt/models/mock-llama
