# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic serialization for the Dynamo Python API docs.

Consumes the discovered :class:`~api_discovery.Module` /
:class:`~api_discovery.Symbol` / :class:`~api_discovery.Method` values and
turns them into the three generator outputs:

* the typed TypeScript data module the visual components read from;
* one whole-file MDX page per curated module, with an ``<llms-only>``
  Markdown fallback for agent exports; and
* the Python API landing page MDX that indexes every curated module.

No I/O happens here -- callers are responsible for writing the returned
text. Deterministic in, deterministic out: identical inputs must produce
byte-identical outputs so ``--check`` and diff review stay reliable.
"""

from __future__ import annotations

import json
from collections.abc import Iterable

from api_discovery import Method, Module, Symbol
from markdown_rendering import escape_mdx_table_cell

TS_GENERATED_MARKER = "GENERATED by docs/fern/scripts/gen_python_api.py -- do not edit."
MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_python_api.py -- do not edit. */}"
)


# ---------------------------------------------------------------------------
# TypeScript data module
# ---------------------------------------------------------------------------


def render_ts_data(modules: Iterable[Module]) -> str:
    """Render the typed TS data module both the React UI and mdx twin read."""
    header = (
        "/*\n"
        " * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA "
        "CORPORATION & AFFILIATES. All rights reserved.\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " *\n"
        f" * {TS_GENERATED_MARKER}\n"
        " *\n"
        " * The generator (docs/fern/scripts/gen_python_api.py) parses the\n"
        " * Dynamo Python source statically via griffe. Edit that script or\n"
        " * docs/fern/scripts/api_discovery.py, which owns the MODULES tuple,\n"
        " * then re-run it; hand-editing this file is not preserved.\n"
        " */\n"
    )
    return f"{header}\n{_ts_type_decls()}\n{_ts_modules_literal(list(modules))}"


_TS_METHOD_INTERFACE = (
    "export interface ApiMethod {\n"
    "  name: string;\n"
    "  signature: string;\n"
    "  summary: string;\n"
    "  sourcePath: string;\n"
    "  sourceLine: number;\n"
    "  sourceHref: string;\n"
    "}\n"
)

_TS_SYMBOL_INTERFACE = (
    "export interface ApiSymbol {\n"
    "  name: string;\n"
    "  kind: ApiSymbolKind;\n"
    "  qualname: string;\n"
    "  importPath: string;\n"
    "  summary: string;\n"
    "  signature: string;\n"
    "  sourcePath: string;\n"
    "  sourceLine: number;\n"
    "  sourceHref: string;\n"
    "  methods: ApiMethod[];\n"
    "}\n"
)

_TS_MODULE_INTERFACE = (
    "export interface ApiModule {\n"
    "  name: string;\n"
    "  slug: string;\n"
    "  summary: string;\n"
    "  sourcePath: string;\n"
    "  sourceHref: string;\n"
    "  symbols: ApiSymbol[];\n"
    "}\n"
)


def _ts_type_decls() -> str:
    """Type declarations shared by the visual UI and any downstream code."""
    kind_alias = 'export type ApiSymbolKind = "class" | "function";\n'
    return (
        f"{kind_alias}\n"
        f"{_TS_METHOD_INTERFACE}\n"
        f"{_TS_SYMBOL_INTERFACE}\n"
        f"{_TS_MODULE_INTERFACE}"
    )


def _ts_modules_literal(modules: list[Module]) -> str:
    """Render the ``export const API_MODULES`` literal deterministically."""
    entries = [_ts_module_entry(mod) for mod in modules]
    joined = ",\n".join(entries)
    return f"export const API_MODULES: ApiModule[] = [\n{joined}\n];\n"


def _ts_module_entry(module: Module) -> str:
    """Render one ``ApiModule`` object literal."""
    lines = [
        "  {",
        f"    name: {json.dumps(module.name)},",
        f"    slug: {json.dumps(module.slug)},",
        f"    summary: {json.dumps(module.summary)},",
        f"    sourcePath: {json.dumps(module.source_path)},",
        f"    sourceHref: {json.dumps(module.source_href)},",
        "    symbols: [",
    ]
    for symbol in module.symbols:
        lines.append(_ts_symbol_entry(symbol))
    lines.extend(["    ],", "  }"])
    return "\n".join(lines)


def _ts_symbol_entry(symbol: Symbol) -> str:
    """Render one ``ApiSymbol`` object literal."""
    lines = [
        "      {",
        f"        name: {json.dumps(symbol.name)},",
        f"        kind: {json.dumps(symbol.kind)},",
        f"        qualname: {json.dumps(symbol.qualname)},",
        f"        importPath: {json.dumps(symbol.import_path)},",
        f"        summary: {json.dumps(symbol.summary)},",
        f"        signature: {json.dumps(symbol.signature)},",
        f"        sourcePath: {json.dumps(symbol.source_path)},",
        f"        sourceLine: {symbol.source_line},",
        f"        sourceHref: {json.dumps(symbol.source_href)},",
        "        methods: [",
    ]
    for method in symbol.methods:
        lines.append(_ts_method_entry(method))
    lines.extend(["        ],", "      },"])
    return "\n".join(lines)


def _ts_method_entry(method: Method) -> str:
    """Render one ``ApiMethod`` object literal."""
    return (
        "          { "
        f"name: {json.dumps(method.name)}, "
        f"signature: {json.dumps(method.signature)}, "
        f"summary: {json.dumps(method.summary)}, "
        f"sourcePath: {json.dumps(method.source_path)}, "
        f"sourceLine: {method.source_line}, "
        f"sourceHref: {json.dumps(method.source_href)}"
        " },"
    )


# ---------------------------------------------------------------------------
# MDX rendering (whole-file writes)
# ---------------------------------------------------------------------------


def render_module_page(module: Module) -> str:
    """Full MDX text for one per-module page, including the llms-only twin."""
    frontmatter = (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        f"title: {module.name}\n"
        f"subtitle: {_escape_yaml(module.summary)}\n"
        "---\n"
    )
    body = (
        f"\n{MDX_GENERATED_MARKER}\n\n"
        'import { ReferenceStyles } from "@/components/ReferenceStyles";\n'
        'import { ApiSurfaceBrowser } from "@/components/ApiSurfaceBrowser";\n\n'
        "<ReferenceStyles />\n\n"
        f'<ApiSurfaceBrowser module="{module.name}" />\n\n'
        "<llms-only>\n\n"
        f"{_module_llms_markdown(module)}\n\n"
        "</llms-only>\n"
    )
    return frontmatter + body


def _module_llms_markdown(module: Module) -> str:
    """Agent-facing Markdown twin of one module page."""
    classes = [s for s in module.symbols if s.kind == "class"]
    functions = [s for s in module.symbols if s.kind == "function"]
    lines = [
        f"**{module.name}** ({len(classes)} classes, {len(functions)} functions)",
        "",
        module.summary,
        "",
        f"Source: [`{module.source_path}`]({module.source_href})",
    ]
    if classes:
        lines += ["", "### Classes", _symbol_table_md(classes)]
    if functions:
        lines += ["", "### Functions", _symbol_table_md(functions)]
    for symbol in module.symbols:
        lines += ["", *_symbol_details_md(symbol)]
    return "\n".join(lines)


def _symbol_details_md(symbol: Symbol) -> list[str]:
    """Agent-facing signature and method details for one symbol."""
    lines = [f"#### `{symbol.name}`", "", symbol.summary or "No summary available."]
    lines += ["", f"Import: `{_import_statement(symbol)}`"]
    if symbol.signature:
        lines += ["", "```python", symbol.signature, "```"]
    if symbol.methods:
        lines += ["", "##### Public Methods", ""]
        lines.extend(_method_detail_md(method) for method in symbol.methods)
    return lines


def _import_statement(symbol: Symbol) -> str:
    """Valid Python import statement, preserving a public alias name."""
    module_name, import_name = symbol.import_path.rsplit(".", 1)
    return f"from {module_name} import {import_name}"


def _method_detail_md(method: Method) -> str:
    """One public method line with signature, summary, and source."""
    summary = method.summary or "No summary available."
    source = f"[source]({method.source_href})"
    return f"- `{method.signature}` — {summary} ({source})"


def _symbol_table_md(symbols: list[Symbol]) -> str:
    """Compact Markdown table used inside every ``<llms-only>`` block."""
    rows = ["| Symbol | Summary | Source |", "| --- | --- | --- |"]
    for symbol in symbols:
        summary = _cell(symbol.summary)
        src = f"[`{symbol.source_path}#L{symbol.source_line}`]({symbol.source_href})"
        rows.append(f"| `{symbol.name}` | {summary} | {src} |")
    return "\n".join(rows)


def _cell(text: str) -> str:
    """Sanitize a cell value for a Markdown table."""
    return escape_mdx_table_cell(text)


def render_landing_page(modules: Iterable[Module]) -> str:
    """Full MDX text for the Python API landing page."""
    frontmatter = (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "title: Python API\n"
        "subtitle: Public Python surfaces on the Dynamo distributed runtime, "
        "statically discovered from the source tree.\n"
        "---\n"
    )
    body = (
        f"\n{MDX_GENERATED_MARKER}\n\n"
        'import { ReferenceStyles } from "@/components/ReferenceStyles";\n'
        'import { ApiPythonIndex } from "@/components/ApiPythonIndex";\n\n'
        "<ReferenceStyles />\n\n"
        "<ApiPythonIndex />\n\n"
        "<llms-only>\n\n"
        f"{_landing_llms_markdown(list(modules))}\n\n"
        "</llms-only>\n"
    )
    return frontmatter + body


def _landing_llms_markdown(modules: list[Module]) -> str:
    """Agent-facing Markdown twin of the Python API landing page."""
    total = sum(len(m.symbols) for m in modules)
    header = (
        f"Dynamo publishes {len(modules)} Python modules "
        f"({total} public class + function symbols) under ``dynamo.*``."
    )
    rows = [
        "| Module | Summary | Classes | Functions | Source |",
        "| --- | --- | --- | --- | --- |",
    ]
    for mod in modules:
        classes = sum(1 for s in mod.symbols if s.kind == "class")
        functions = sum(1 for s in mod.symbols if s.kind == "function")
        src = f"[`{mod.source_path}`]({mod.source_href})"
        rows.append(
            f"| `{mod.name}` | {_cell(mod.summary)} | {classes} | {functions} | {src} |"
        )
    return header + "\n\n" + "\n".join(rows)


def _escape_yaml(text: str) -> str:
    """Minimal YAML-safe scalar for the subtitle field."""
    return text.replace('"', '\\"')
