# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic serialization for the Dynamo Python API docs.

Consumes the discovered :class:`~api_discovery.Module` /
:class:`~api_discovery.Symbol` / :class:`~api_discovery.Method` values and
turns them into two generator outputs, both built from Fern's own components:

* one MDX page per curated module -- an anchored ``<Accordion>`` per symbol,
  with the import statement and signature in Python code fences; and
* the Python API landing page, a ``<CardGroup>`` indexing every module.

No I/O happens here -- callers are responsible for writing the returned
text. Deterministic in, deterministic out: identical inputs must produce
byte-identical outputs so ``--check`` and diff review stay reliable.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from api_discovery import Method, Module, Symbol
from markdown_rendering import escape_mdx_prose, mdx_attribute

MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_python_api.py -- do not edit. */}"
)


# ---------------------------------------------------------------------------
# MDX rendering (whole-file writes)
# ---------------------------------------------------------------------------


def symbol_anchor(symbol: Symbol) -> str:
    """Stable, page-unique DOM id for one symbol's deep link."""
    slug = re.sub(r"[^a-z0-9]+", "-", symbol.qualname.lower()).strip("-")
    return f"api-{slug}"


def import_statement(symbol: Symbol) -> str:
    """Valid Python import statement, preserving a public alias name."""
    module_name, import_name = symbol.import_path.rsplit(".", 1)
    return f"from {module_name} import {import_name}"


def render_module_page(module: Module) -> str:
    """Full MDX text for one per-module page."""
    parts = [_module_frontmatter(module).rstrip("\n"), "", MDX_GENERATED_MARKER, ""]
    parts.append(_module_intro(module))
    for symbol in module.symbols:
        parts.append("")
        parts.append("\n".join(_symbol_section(symbol)))
    return "\n".join(parts).rstrip() + "\n"


def _module_frontmatter(module: Module) -> str:
    """SPDX header plus title/subtitle for one module page."""
    return (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        f"title: {module.name}\n"
        f"subtitle: {_escape_yaml(module.summary)}\n"
        "---\n"
    )


def _module_intro(module: Module) -> str:
    """Symbol counts and a source link above the per-symbol accordions."""
    classes = sum(1 for s in module.symbols if s.kind == "class")
    functions = sum(1 for s in module.symbols if s.kind == "function")
    return (
        f"`{module.name}` publishes {classes} classes and {functions} functions. "
        f"Source: [`{module.source_path}`]({module.source_href})"
    )


def _symbol_section(symbol: Symbol) -> list[str]:
    """One anchored accordion carrying a symbol's signature and methods.

    The explicit id keeps deep links stable: Fern's own title-derived id
    collides for same-named symbols across submodules.
    """
    title = mdx_attribute(f"{symbol.name} ({symbol.kind})")
    return [
        f'<Accordion id="{symbol_anchor(symbol)}" title="{title}">',
        *_symbol_body(symbol),
        "</Accordion>",
    ]


def _symbol_body(symbol: Symbol) -> list[str]:
    """Summary, import fence, signature, source link, and public methods."""
    lines = [escape_mdx_prose(symbol.summary) or "No summary available.", ""]
    lines += ["```python", import_statement(symbol), "```"]
    if symbol.signature:
        lines += ["", "```python", symbol.signature, "```"]
    lines += [
        "",
        f"[`{symbol.source_path}#L{symbol.source_line}`]({symbol.source_href})",
    ]
    if symbol.methods:
        lines += ["", "**Public methods**", ""]
        lines.extend(_method_line(method) for method in symbol.methods)
    return lines


def _method_line(method: Method) -> str:
    """One public method bullet with signature, summary, and source."""
    summary = escape_mdx_prose(method.summary) or "No summary available."
    return f"- `{method.signature}` — {summary} ([source]({method.source_href}))"


def render_landing_page(modules: Iterable[Module]) -> str:
    """Full MDX text for the Python API landing page."""
    module_list = list(modules)
    frontmatter = (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "title: Python API\n"
        "subtitle: Public Python surfaces on the Dynamo distributed runtime, "
        "statically discovered from the source tree.\n"
        "---\n"
    )
    parts = [frontmatter.rstrip("\n"), "", MDX_GENERATED_MARKER, ""]
    parts.append(_landing_body(module_list))
    return "\n".join(parts).rstrip() + "\n"


def _landing_body(modules: list[Module]) -> str:
    """Lead paragraph plus one navigation card per discovered module."""
    total = sum(len(m.symbols) for m in modules)
    lines = [
        f"Dynamo publishes {len(modules)} Python modules with {total} public "
        "class and function symbols under `dynamo.*`.",
        "",
        "<CardGroup cols={2}>",
    ]
    for module in modules:
        lines.append(
            f'<Card title="{mdx_attribute(module.name)}" '
            f'href="python/{module.slug}">'
            f"{len(module.symbols)} symbols. "
            f"{escape_mdx_prose(module.summary)}</Card>"
        )
    lines.append("</CardGroup>")
    return "\n".join(lines)


def _escape_yaml(text: str) -> str:
    """Minimal YAML-safe scalar for the subtitle field."""
    return text.replace('"', '\\"')
