#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate <llms-only> markdown twins of the Reference-page component data.

The three Reference pages (reference/compatibility.mdx,
reference/release-artifacts.mdx, reference/model-early-access-builds.mdx)
render their data through custom React components, whose output may be absent
from Fern's agent-facing markdown exports (.md endpoints, llms.txt). This
script reads the single source of truth ``components/releases.data.ts`` and
emits equivalent markdown tables into each page between idempotent markers,
wrapped in <llms-only> so only agent exports see them.

Usage (from any cwd; paths resolve relative to this file):

    python3 gen_llms_tables.py            # write/refresh the blocks
    python3 gen_llms_tables.py --check    # exit 1 if a page is stale, no writes

Re-run at every release bump, after editing releases.data.ts.

The parser is deliberately conservative: releases.data.ts must stay a
disciplined literal (see PARSER CONTRACT below). Any construct the parser
does not understand aborts the run with a clear error -- partial output is
never emitted.

PARSER CONTRACT (keep releases.data.ts within these bounds):
  * Top-level declarations of the form ``[export] const NAME[: Type] = <literal>;``
  * Literal values: object/array literals, string literals ('...' or "..."),
    template literals whose only interpolations are ``${IDENT}`` where IDENT
    is a previously declared string const (e.g. ``${GH}``, ``${NGC_C}``),
    numbers, true/false/null, and bare identifier references to previously
    declared consts (e.g. ``coverage: MODEL_COVERAGE``).
  * Object keys: bare identifiers or quoted strings.
  * No computed values, spreads, function calls, arithmetic, or ternaries.
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_TS = SCRIPT_DIR.parent / "components" / "releases.data.ts"
REFERENCE_DIR = SCRIPT_DIR.parent / "reference"

MARKER_BEGIN = (
    "{/* llms-tables:begin — generated by scripts/gen_llms_tables.py, do not edit */}"
)
MARKER_END = "{/* llms-tables:end */}"

# Exports the generator depends on. Parsing aborts if any is missing.
REQUIRED_EXPORTS = [
    "RELEASES",
    "MAIN_TOT",
    "CURRENT_VERSION",
    "CURRENT_TAG",
    "CURRENT_WHEEL",
    "CUDA_HISTORY",
    "FEATURES",
    "ARTIFACTS",
    "MODEL_EA_BUILDS",
    "PLATFORM",
    "KNOWN_ARTIFACT_ISSUES",
    "CRATES_FIRST_PUBLISHED",
]


class TSParseError(Exception):
    """releases.data.ts contains a construct the conservative parser rejects."""


# ---------------------------------------------------------------------------
# TypeScript literal parsing (stdlib only, no TS runtime)
# ---------------------------------------------------------------------------


def strip_comments(src: str) -> str:
    """Remove // and /* */ comments, preserving string/template contents.

    A character walk (not regex) so that ``https://...`` inside strings and
    comment-like sequences inside template literals survive intact.
    """
    out: list[str] = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c in "\"'`":
            quote = c
            out.append(c)
            i += 1
            while i < n:
                ch = src[i]
                out.append(ch)
                if ch == "\\" and i + 1 < n:  # keep escaped char verbatim
                    out.append(src[i + 1])
                    i += 2
                    continue
                i += 1
                if ch == quote:
                    break
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "*":
            end = src.find("*/", i + 2)
            if end == -1:
                raise TSParseError("unterminated /* */ comment")
            # Preserve newlines so any future error positions stay meaningful.
            out.append("\n" * src.count("\n", i, end))
            i = end + 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


class LiteralParser:
    """Recursive-descent parser for disciplined TS object/array literals."""

    def __init__(self, src: str, env: dict):
        self.src = src
        self.i = 0
        self.env = env  # previously parsed consts, for ${IDENT} / bare refs

    def error(self, msg: str) -> TSParseError:
        line = self.src.count("\n", 0, self.i) + 1
        context = self.src[self.i : self.i + 40].replace("\n", "\\n")
        return TSParseError(f"{msg} (near line {line}: {context!r})")

    def ws(self) -> None:
        while self.i < len(self.src) and self.src[self.i] in " \t\r\n":
            self.i += 1

    def peek(self) -> str:
        return self.src[self.i] if self.i < len(self.src) else ""

    def expect(self, ch: str) -> None:
        if self.peek() != ch:
            raise self.error(f"expected {ch!r}")
        self.i += 1

    def parse_value(self):
        self.ws()
        c = self.peek()
        if c == "{":
            return self.parse_object()
        if c == "[":
            return self.parse_array()
        if c in "\"'":
            return self.parse_string(c)
        if c == "`":
            return self.parse_template()
        if c.isdigit() or c == "-":
            return self.parse_number()
        if c.isalpha() or c == "_":
            return self.parse_word()
        raise self.error("unexpected token")

    def parse_object(self) -> dict:
        self.expect("{")
        obj: dict = {}
        while True:
            self.ws()
            if self.peek() == "}":
                self.i += 1
                return obj
            key = self.parse_key()
            self.ws()
            self.expect(":")
            obj[key] = self.parse_value()
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "}":
                raise self.error("expected ',' or '}' in object")

    def parse_key(self) -> str:
        c = self.peek()
        if c in "\"'":
            return self.parse_string(c)
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        if not m:
            raise self.error("expected object key")
        self.i += m.end()
        return m.group(0)

    def parse_array(self) -> list:
        self.expect("[")
        arr: list = []
        while True:
            self.ws()
            if self.peek() == "]":
                self.i += 1
                return arr
            arr.append(self.parse_value())
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "]":
                raise self.error("expected ',' or ']' in array")

    def parse_string(self, quote: str) -> str:
        self.expect(quote)
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated string")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            self.i += 1
            if c == quote:
                return "".join(out)
            out.append(c)

    def parse_template(self) -> str:
        """Template literal; only ``${IDENT}`` interpolations of known
        string consts are allowed (the ``${GH}`` / ``${NGC_C}`` prefixes)."""
        self.expect("`")
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated template literal")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            if c == "`":
                self.i += 1
                return "".join(out)
            if c == "$" and self.src[self.i : self.i + 2] == "${":
                m = re.match(r"\$\{([A-Za-z_$][\w$]*)\}", self.src[self.i :])
                if not m:
                    raise self.error("only ${IDENT} interpolation is supported")
                name = m.group(1)
                if name not in self.env or not isinstance(self.env[name], str):
                    raise self.error(
                        f"${{{name}}}: not a previously declared string const"
                    )
                out.append(self.env[name])
                self.i += m.end()
                continue
            out.append(c)
            self.i += 1

    def unescape(self) -> str:
        esc = self.src[self.i + 1] if self.i + 1 < len(self.src) else ""
        self.i += 2
        return {"n": "\n", "t": "\t", "r": "\r"}.get(esc, esc)

    def parse_number(self):
        m = re.match(r"-?\d+(?:\.\d+)?", self.src[self.i :])
        if not m:
            raise self.error("bad number")
        self.i += m.end()
        text = m.group(0)
        return float(text) if "." in text else int(text)

    def parse_word(self):
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        word = m.group(0)
        self.i += m.end()
        if word == "true":
            return True
        if word == "false":
            return False
        if word in ("null", "undefined"):
            return None
        # Bare identifier reference to a previously declared const
        # (e.g. ``coverage: MODEL_COVERAGE``). Deep-copied so shared
        # references never alias each other in the parsed data.
        if word in self.env:
            return copy.deepcopy(self.env[word])
        raise self.error(f"unknown identifier {word!r}")


DECL_RE = re.compile(
    r"^\s*(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*(?::[^=;]+?)?=",
    re.MULTILINE,
)


def parse_data_module(path: Path) -> dict:
    """Parse every top-level const in releases.data.ts into a dict."""
    try:
        src = strip_comments(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise TSParseError(f"cannot read {path}: {exc}") from exc

    env: dict = {}
    for m in DECL_RE.finditer(src):
        name = m.group(1)
        parser = LiteralParser(src, env)
        parser.i = m.end()
        try:
            env[name] = parser.parse_value()
        except TSParseError as exc:
            raise TSParseError(f"while parsing const {name}: {exc}") from exc
        parser.ws()
        if parser.peek() == ";":
            parser.i += 1

    missing = [n for n in REQUIRED_EXPORTS if n not in env]
    if missing:
        raise TSParseError(f"missing required exports: {', '.join(missing)}")
    return env


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def cell(value) -> str:
    """Sanitize a value for a markdown table cell."""
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def md_table(headers: list[str], rows: list[list]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


def nixl_cell(pins: dict) -> str:
    parts = [pins.get(k) or "-" for k in ("nixlSglang", "nixlTrtllm", "nixlVllm")]
    return " / ".join(parts) if any(p != "-" for p in parts) else "-"


FEATURE_STATUS_LABEL = {
    "yes": "Supported",
    "caveat": "Supported with caveat",
    "wip": "Experimental",
    "no": "Not supported",
}


def feature_cell(fc: dict) -> str:
    status = fc.get("status")
    if status not in FEATURE_STATUS_LABEL:
        raise TSParseError(f"unknown feature status {status!r}")
    label = FEATURE_STATUS_LABEL[status]
    note = fc.get("note")
    return f"{label} ({note})" if note else label


def render_compatibility(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    # Backend pins: main (ToT) first, then every tracked release, newest first.
    pin_rows: list[list] = []
    tot = data["MAIN_TOT"]
    pin_rows.append(
        [
            "main (ToT)",
            "development head",
            tot.get("sglang"),
            tot.get("trtllm"),
            tot.get("vllm"),
            nixl_cell(tot),
        ]
    )
    for rel in data["RELEASES"]:
        pins = rel.get("pins") or {}
        pin_rows.append(
            [
                rel["version"],
                rel.get("kind"),
                pins.get("sglang"),
                pins.get("trtllm"),
                pins.get("vllm"),
                nixl_cell(pins),
            ]
        )
    parts.append("**Backend engine pins per Dynamo release**")
    parts.append(
        md_table(
            [
                "Dynamo",
                "Type",
                "SGLang",
                "TensorRT-LLM",
                "vLLM",
                "NIXL (SGL / TRT / vLLM)",
            ],
            pin_rows,
        )
    )

    parts.append("**CUDA toolkit and minimum driver per Dynamo release**")
    cuda_rows = [
        [r["version"], r["backend"], r["toolkit"], r["minDriver"], r.get("note")]
        for r in data["CUDA_HISTORY"]
    ]
    parts.append(
        md_table(["Dynamo", "Backend", "CUDA Toolkit", "Min Driver", "Note"], cuda_rows)
    )
    cuda_notes = data.get("CUDA_NOTES") or []
    if cuda_notes:
        parts.append("\n".join(f"- {note}" for note in cuda_notes))

    parts.append(f"**Feature support by backend ({data['CURRENT_VERSION']})**")
    feature_rows = [
        [
            f["name"],
            feature_cell(f["sglang"]),
            feature_cell(f["trtllm"]),
            feature_cell(f["vllm"]),
        ]
        for f in data["FEATURES"]
    ]
    parts.append(md_table(["Feature", "SGLang", "TensorRT-LLM", "vLLM"], feature_rows))

    # Platform support (GPUs / OS / arch) — rendered by CompatibilityHero.
    plat = data["PLATFORM"]
    parts.append("**Platform support**")
    plat_lines = [f"- GPU architectures: {', '.join(plat['gpus'])}"]
    for os_row in plat["os"]:
        plat_lines.append(
            f"- OS: {os_row['name']} {os_row['version']} ({os_row['arch']}) — {os_row['status']}"
        )
    for csp in plat.get("csp", []):
        plat_lines.append(
            f"- CSP: {csp['provider']} — {csp['os']} ({csp['arch']}) — {csp['status']}"
        )
    plat_lines.append(f"- CPU architectures: {', '.join(plat['arch'])}")
    if plat.get("wheelsNote"):
        plat_lines.append(f"- Wheels: {plat['wheelsNote']}")
    parts.append("\n".join(plat_lines))

    return "\n\n".join(parts)


def render_release_artifacts(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    parts.append(f"**Artifact inventory ({data['CURRENT_VERSION']})**")
    art_rows: list[list] = []
    for art in data["ARTIFACTS"]:
        name = art["name"]
        if art.get("badge"):
            name = f"{name} ({art['badge']})"
        tags = "; ".join(f"`{t['clipboard']}`" for t in art.get("tags", []))
        art_rows.append(
            [art["category"], name, art["description"], art.get("meta"), tags]
        )
    parts.append(
        md_table(
            ["Category", "Name", "Description", "Meta", "Tags / install"], art_rows
        )
    )

    parts.append("**Known artifact issues**")
    issue_rows = [
        [i["version"], i["artifact"], i["issue"], i["status"]]
        for i in data["KNOWN_ARTIFACT_ISSUES"]
    ]
    parts.append(md_table(["Release", "Artifact", "Issue", "Status"], issue_rows))

    parts.append("**Crates: first published version on crates.io**")
    crate_rows = [
        [c["crate"], c["version"], c["date"]] for c in data["CRATES_FIRST_PUBLISHED"]
    ]
    parts.append(md_table(["Crate", "First version", "Date"], crate_rows))

    return "\n\n".join(parts)


def render_model_ea_builds(data: dict) -> str:
    parts: list[str] = []
    parts.append("**Model early-access builds**")
    rows: list[list] = []
    for b in data["MODEL_EA_BUILDS"]:
        cov = b["coverage"]
        cov_cell = " / ".join(
            "yes" if cov.get(k) else "no"
            for k in ("images", "wheels", "helm", "crates")
        )
        rows.append(
            [
                b["model"],
                f"`{b['tag']}`",
                b["releaseLine"],
                ", ".join(b["runtimes"]),
                b["shipped"],
                b["gaLabel"],
                b["statusLine"],
                cov_cell,
            ]
        )
    parts.append(
        md_table(
            [
                "Model",
                "Tag",
                "Release line",
                "Runtimes",
                "Shipped",
                "GA path",
                "Status",
                "Coverage (images / wheels / helm / crates)",
            ],
            rows,
        )
    )
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------

PAGES = {
    "compatibility.mdx": render_compatibility,
    "release-artifacts.mdx": render_release_artifacts,
    "model-early-access-builds.mdx": render_model_ea_builds,
}

# Matches an existing generated span. Tolerant of edits to the note after
# "llms-tables:begin" so a hand-tweaked marker comment is still replaced.
BLOCK_RE = re.compile(
    r"\{/\*\s*llms-tables:begin[^*]*\*/\}.*?\{/\*\s*llms-tables:end\s*\*/\}",
    re.DOTALL,
)


def build_block(body: str) -> str:
    return f"{MARKER_BEGIN}\n<llms-only>\n\n{body}\n\n</llms-only>\n{MARKER_END}"


def apply_block(page_text: str, block: str) -> str:
    if BLOCK_RE.search(page_text):
        return BLOCK_RE.sub(lambda _m: block, page_text, count=1)
    # No markers yet: append at end of file, before the trailing newline.
    return page_text.rstrip("\n") + "\n\n" + block + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if regeneration would change any page; write nothing",
    )
    args = ap.parse_args(argv)

    try:
        data = parse_data_module(DATA_TS)
    except TSParseError as exc:
        print(f"error: failed to parse {DATA_TS}: {exc}", file=sys.stderr)
        return 2

    # Render everything up front so a failure on any page emits nothing.
    try:
        rendered: dict[str, str] = {}
        for page_name, renderer in PAGES.items():
            page_path = REFERENCE_DIR / page_name
            if not page_path.is_file():
                print(f"error: page not found: {page_path}", file=sys.stderr)
                return 2
            old = page_path.read_text(encoding="utf-8")
            rendered[page_name] = apply_block(old, build_block(renderer(data)))
    except (TSParseError, KeyError) as exc:
        print(f"error: rendering failed: {exc!r}", file=sys.stderr)
        return 2

    stale = []
    for page_name, new_text in rendered.items():
        page_path = REFERENCE_DIR / page_name
        old_text = page_path.read_text(encoding="utf-8")
        if new_text == old_text:
            print(f"{page_name}: unchanged")
            continue
        stale.append(page_name)
        if args.check:
            print(f"{page_name}: STALE (regeneration would change it)")
        else:
            page_path.write_text(new_text, encoding="utf-8")
            print(f"{page_name}: wrote {len(new_text.encode('utf-8'))} bytes")

    if args.check and stale:
        print(
            f"check failed: {len(stale)} page(s) stale — run gen_llms_tables.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
