# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic MDX rendering for the Dynamo Kubernetes API reference.

Consumes the discovered :class:`~kubernetes_api_discovery.KubernetesReference`
model and produces one MDX page built from Fern's own components:
``<CardGroup>`` / ``<Card>`` for each package's resource-type entry points,
``<AccordionGroup>`` / ``<Accordion>`` per documented type, ``<ParamField>``
per schema field, and ``<Badge>`` per enum value. This matches the pattern the
backend config references already use, so the schema is searchable while
collapsed and Fern derives the Markdown and llms.txt twins itself.

No I/O happens in this module -- callers own the writes. Identical inputs
must produce byte-identical outputs so ``--check`` and diff review stay
reliable.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from kubernetes_api_discovery import (
    KubernetesEnumValue,
    KubernetesField,
    KubernetesPackage,
    KubernetesReference,
    KubernetesType,
    OperatorDefaults,
)
from markdown_rendering import escape_mdx_prose as _prose
from markdown_rendering import mdx_attribute as _attr

MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_kubernetes_api.py -- do not edit. */}"
)
LOCAL_FRAGMENT_LINK_RE = re.compile(r"\[(?P<label>[^\]]+)\]\(#(?P<anchor>[^)]+)\)")
SOURCE_HREF_MD = (
    "https://github.com/ai-dynamo/dynamo/blob/main/docs/fern/kubernetes/"
    "api-reference.md"
)

_FRONTMATTER = (
    "---\n"
    "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
    "& AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "title: API Reference\n"
    "subtitle: Full Kubernetes CRD + operator-config API reference, generated "
    "from the operator Go types.\n"
    "---\n"
)

_WARNING = (
    "> [!WARNING]\n"
    "> **Auto-generated from source.** This page is regenerated from the "
    "Dynamo operator CRDs by "
    "[`docs/fern/scripts/gen_kubernetes_api.py`](https://github.com/ai-dynamo/"
    "dynamo/blob/main/docs/fern/scripts/gen_kubernetes_api.py) and covers "
    "**every** type across all three API packages: the deprecated "
    "`nvidia.com/v1alpha1` surface, the supported `nvidia.com/v1beta1` surface, "
    "and the operator's own `operator.config.dynamo.nvidia.com/v1alpha1` "
    "configuration. The trimmed [DGD](dgd-reference.mdx), "
    "[DGDR](dgdr-reference.mdx), and [DCD](dcd-reference.mdx) references cover "
    "only user-facing `v1beta1` fields. To edit the surface, change the Go "
    "types under `deploy/operator/api/` and let CI regenerate this page.\n"
)


def render_mdx(reference: KubernetesReference) -> str:
    """Full MDX text for the Kubernetes API reference page."""
    parts = [
        _FRONTMATTER.rstrip("\n"),
        "",
        MDX_GENERATED_MARKER,
        "",
        _WARNING.rstrip("\n"),
        "",
        _package_index(reference),
    ]
    for package in reference.packages:
        parts.append("")
        parts.append(_package_section(package))
    parts.append("")
    parts.append(_operator_defaults(reference.operator_defaults))
    parts.append("")
    parts.append(
        f"Raw generated Markdown source: [`api-reference.md`]({SOURCE_HREF_MD})"
    )
    return "\n".join(parts).rstrip() + "\n"


def _package_index(reference: KubernetesReference) -> str:
    """Lead paragraph plus a jump card per API package."""
    total_types = sum(len(pkg.types) for pkg in reference.packages)
    lines = [
        f"Dynamo publishes {len(reference.packages)} Kubernetes API packages "
        f"with {total_types} typed CRD and config sections.",
        "",
        "<CardGroup cols={3}>",
    ]
    for pkg in reference.packages:
        lines.append(
            f'<Card title="{_attr(pkg.name)}" href="#{pkg.anchor}">'
            f"{len(pkg.types)} types</Card>"
        )
    lines.append("</CardGroup>")
    return "\n".join(lines)


def _package_section(package: KubernetesPackage) -> str:
    """One package heading, its resource-type cards, and every typed section."""
    valid_anchors = {type_.anchor for type_ in package.types}
    lines = [f'<a id="{package.anchor}"></a>', "", f"## {package.name}"]
    if package.description:
        lines += ["", _prose(package.description)]
    if package.resource_types:
        lines += ["", "**Resource Types**", "", "<CardGroup cols={3}>"]
        for ref in package.resource_types:
            lines.append(f'<Card title="{_attr(ref.name)}" href="#{ref.anchor}" />')
        lines.append("</CardGroup>")
    for type_ in package.types:
        lines += ["", *_type_section(type_, valid_anchors)]
    return "\n".join(lines)


def _type_section(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """One anchored accordion carrying a type's full schema.

    The anchor sits immediately before the accordion, not inside it: field
    tables across packages deep-link to ``#anchor``, and an anchor nested in
    collapsed content is not a reliable scroll target.
    """
    lines = [
        f'<a id="{type_.anchor}"></a>',
        f'<Accordion title="{_attr(type_.display_name)}">',
    ]
    lines.extend(_type_body(type_, valid_anchors))
    lines.append("</Accordion>")
    return lines


def _type_body(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """Description, metadata lines, fields, and enum values for one type."""
    lines: list[str] = []
    if type_.description:
        lines += [_prose(type_.description), ""]
    lines.extend(_type_metadata(type_, valid_anchors))
    for field in type_.fields:
        lines += ["", *_param_field(field, valid_anchors)]
    if type_.enum_values:
        lines += ["", *_enum_values(type_.enum_values)]
    return lines


def _type_metadata(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """Kind, underlying type, validation, and back-references for one type."""
    lines = [f"**Kind:** `{type_.kind}`"]
    if type_.underlying_type:
        lines.append(f"**Underlying type:** `{_plain(type_.underlying_type)}`")
    if type_.validation:
        lines.append(f"**Validation:** {_prose(type_.validation)}")
    refs = [ref for ref in type_.appears_in if ref.anchor in valid_anchors]
    if refs:
        joined = ", ".join(f"[{ref.name}](#{ref.anchor})" for ref in refs)
        lines.append(f"**Appears in:** {joined}")
    return ["", *lines] if lines else lines


def _param_field(field: KubernetesField, valid_anchors: set[str]) -> list[str]:
    """One ``<ParamField>`` for a schema field.

    ``type`` carries the plain type name because MDX attributes cannot hold
    Markdown; when the source type linked to another documented type, the
    link is re-emitted in the body so navigation survives.
    """
    attrs = [f'path="{_attr(field.name)}"', f'type="{_attr(_plain(field.type))}"']
    if field.default:
        attrs.append(f'default="{_attr(field.default)}"')
    if field.required:
        attrs.append("required={true}")
    lines = [f"<ParamField {' '.join(attrs)}>"]
    if field.description:
        lines.append(_prose(field.description))
    lines.extend(_field_footnotes(field, valid_anchors))
    lines.append("</ParamField>")
    return lines


def _field_footnotes(field: KubernetesField, valid_anchors: set[str]) -> list[str]:
    """Resolved type links and validation notes for one field."""
    lines: list[str] = []
    links = [
        f"[{match.group('label')}](#{match.group('anchor')})"
        for match in LOCAL_FRAGMENT_LINK_RE.finditer(field.type)
        if match.group("anchor") in valid_anchors
    ]
    if links:
        lines.append(f"See {', '.join(links)}.")
    if field.validation:
        lines.append(f"**Validation:** {_prose(field.validation)}")
    return lines


def _enum_values(values: Iterable[KubernetesEnumValue]) -> list[str]:
    """Allowed-value badges plus their descriptions."""
    lines = ["**Allowed values**", ""]
    for value in values:
        badge = f'<Badge intent="note" minimal>{_prose(value.name)}</Badge>'
        description = _prose(value.description)
        lines.append(f"- {badge} {description}" if description else f"- {badge}")
    return lines


def _operator_defaults(defaults: OperatorDefaults) -> str:
    """Render the operator-defaults trailer with H2 to H3 heading demotion.

    The upstream Markdown treats the trailer as an H1 with H2 subsections.
    The page embeds it as an H2 with H3 subsections so the whole document
    nests consistently under the title Fern renders from the navigation.
    """
    parts = ["## Operator Default Values Injection", "", defaults.intro_markdown]
    for sub in defaults.subsections:
        parts.append("")
        parts.append(f"### {sub.title}")
        parts.append("")
        parts.append(_demote_headings(sub.body_markdown))
    return "\n".join(parts).rstrip() + "\n"


def _demote_headings(markdown: str) -> str:
    """Prepend one ``#`` to every ATX heading line in ``markdown``."""
    return "\n".join(
        "#" + line if _is_atx_heading(line) else line for line in markdown.splitlines()
    )


def _is_atx_heading(line: str) -> bool:
    """True when ``line`` is an ATX Markdown heading (``#``..``######``)."""
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return False
    prefix = stripped[: len(stripped) - len(stripped.lstrip("#"))]
    if len(prefix) < 1 or len(prefix) > 6:
        return False
    rest = stripped[len(prefix) :]
    return rest.startswith(" ") or rest == ""


def _plain(text: str) -> str:
    """Replace Markdown links with their label text."""
    return LOCAL_FRAGMENT_LINK_RE.sub(lambda match: match.group("label"), text).strip()


__all__ = [
    "MDX_GENERATED_MARKER",
    "render_mdx",
]
