# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic serialization for the Dynamo Kubernetes API reference.

Consumes the discovered :class:`~kubernetes_api_discovery.KubernetesReference`
model and produces:

* the typed TypeScript data module snapshotted beside the versioned page; and
* the thin MDX shell that mounts ``<ReferenceStyles />`` and
  ``<ApiKubernetesReference />``, embeds the twelve operator-default
  subsections as demoted Markdown headings, and carries a full
  ``<llms-only>`` Markdown twin so agent exports still see the 165-type
  surface after the compact React component is stripped.

No I/O happens in this module -- callers own the writes. Identical inputs
must produce byte-identical outputs so ``--check`` and diff review stay
reliable.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Iterable
from typing import Any

from kubernetes_api_discovery import (
    KubernetesEnumValue,
    KubernetesField,
    KubernetesPackage,
    KubernetesReference,
    KubernetesType,
    KubernetesTypeRef,
    OperatorDefaults,
    OperatorDefaultsSubsection,
)
from markdown_rendering import escape_mdx_table_cell

TS_GENERATED_MARKER = (
    "GENERATED by docs/fern/scripts/gen_kubernetes_api.py -- do not edit."
)
MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_kubernetes_api.py -- do not edit. */}"
)
LOCAL_FRAGMENT_LINK_RE = re.compile(r"\[(?P<label>[^\]]+)\]\(#(?P<anchor>[^)]+)\)")
SOURCE_HREF_MD = (
    "https://github.com/ai-dynamo/dynamo/blob/main/docs/fern/kubernetes/"
    "api-reference.md"
)


# ---------------------------------------------------------------------------
# TypeScript data module
# ---------------------------------------------------------------------------


def render_ts_data(reference: KubernetesReference) -> str:
    """Render the typed TS data module the React component consumes."""
    header = (
        "/*\n"
        " * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA "
        "CORPORATION & AFFILIATES. All rights reserved.\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " *\n"
        f" * {TS_GENERATED_MARKER}\n"
        " *\n"
        " * The generator parses the upstream crd-ref-docs Markdown at\n"
        " * docs/fern/kubernetes/api-reference.md into a typed model. Edit\n"
        " * docs/fern/scripts/kubernetes_api_discovery.py or the upstream\n"
        " * Markdown source, then re-run gen_kubernetes_api.py; hand-editing\n"
        " * this file is not preserved.\n"
        " */\n"
    )
    body = (
        "\nimport type { KubernetesReference } from "
        '"@/components/KubernetesApiTypes";\n\n'
        f"{_ts_reference_literal(reference)}"
    )
    return header + body


def _ts_reference_literal(reference: KubernetesReference) -> str:
    """Render the ``export const KUBERNETES_REFERENCE`` object literal."""
    lines = [
        "export const KUBERNETES_REFERENCE: KubernetesReference = {",
        f"  sourceHref: {json.dumps(SOURCE_HREF_MD)},",
        "  packages: [",
    ]
    for package in reference.packages:
        lines.extend(_ts_package_lines(package))
    lines.append("  ],")
    lines.extend(_ts_operator_defaults_lines(reference.operator_defaults))
    lines.append("};\n")
    return "\n".join(lines)


def _ts_package_lines(package: KubernetesPackage) -> list[str]:
    """Render one ``KubernetesPackage`` object literal."""
    header = [
        "    {",
        f"      name: {json.dumps(package.name)},",
        f"      anchor: {json.dumps(package.anchor)},",
        f"      description: {json.dumps(package.description)},",
        "      resourceTypes: [",
    ]
    for ref in package.resource_types:
        header.append(_ts_typeref_inline(ref))
    header.append("      ],")
    header.append("      types: [")
    for type_ in package.types:
        header.extend(_ts_type_lines(type_))
    header.append("      ],")
    header.append("    },")
    return header


def _ts_typeref_inline(ref: KubernetesTypeRef) -> str:
    """Render one ``KubernetesTypeRef`` on a single line."""
    return (
        f"        {{ name: {json.dumps(ref.name)}, anchor: {json.dumps(ref.anchor)} }},"
    )


def _ts_type_lines(type_: KubernetesType) -> list[str]:
    """Render one ``KubernetesType`` object literal."""
    lines = _ts_type_header_lines(type_)
    lines.extend(_ts_array_block("appearsIn", type_.appears_in, _ts_typeref_deep))
    lines.extend(_ts_array_block("fields", type_.fields, _ts_field_line))
    lines.extend(_ts_array_block("enumValues", type_.enum_values, _ts_enum_value_line))
    lines.append("        },")
    return lines


def _ts_type_header_lines(type_: KubernetesType) -> list[str]:
    """Scalar prefix of a ``KubernetesType`` literal (before the arrays)."""
    return [
        "        {",
        f"          name: {json.dumps(type_.name)},",
        f"          displayName: {json.dumps(type_.display_name)},",
        f"          anchor: {json.dumps(type_.anchor)},",
        f"          kind: {json.dumps(type_.kind)},",
        f"          description: {json.dumps(type_.description)},",
        f"          underlyingType: {json.dumps(type_.underlying_type)},",
        f"          validation: {json.dumps(type_.validation)},",
    ]


def _ts_array_block(
    key: str, items: tuple[Any, ...], render: Callable[[Any], str]
) -> list[str]:
    """Render one ``key: [ <render(item)>... ],`` block on the type literal."""
    body = [f"          {key}: ["]
    for item in items:
        body.append(render(item))
    body.append("          ],")
    return body


def _ts_typeref_deep(ref: KubernetesTypeRef) -> str:
    """Render one ``KubernetesTypeRef`` inside a nested type array."""
    return (
        f"            {{ name: {json.dumps(ref.name)}, "
        f"anchor: {json.dumps(ref.anchor)} }},"
    )


def _ts_field_line(field: KubernetesField) -> str:
    """Render one ``KubernetesField`` object literal on a single line."""
    return (
        "            { "
        f"name: {json.dumps(field.name)}, "
        f"type: {json.dumps(field.type)}, "
        f"default: {json.dumps(field.default)}, "
        f"required: {json.dumps(field.required)}, "
        f"description: {json.dumps(field.description)}, "
        f"validation: {json.dumps(field.validation)}"
        " },"
    )


def _ts_enum_value_line(value: KubernetesEnumValue) -> str:
    """Render one ``KubernetesEnumValue`` object literal on a single line."""
    return (
        "            { "
        f"name: {json.dumps(value.name)}, "
        f"description: {json.dumps(value.description)}"
        " },"
    )


def _ts_operator_defaults_lines(defaults: OperatorDefaults) -> list[str]:
    """Render the ``operatorDefaults`` object literal (intro + subsections)."""
    lines = [
        "  operatorDefaults: {",
        f"    introMarkdown: {json.dumps(defaults.intro_markdown)},",
        "    subsections: [",
    ]
    for sub in defaults.subsections:
        lines.append(
            "      { "
            f"title: {json.dumps(sub.title)}, "
            f"anchor: {json.dumps(sub.anchor)}, "
            f"bodyMarkdown: {json.dumps(sub.body_markdown)}"
            " },"
        )
    lines.append("    ],")
    lines.append("  },")
    return lines


# ---------------------------------------------------------------------------
# MDX shell rendering
# ---------------------------------------------------------------------------


_FRONTMATTER = (
    "---\n"
    "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
    "& AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "title: API Reference\n"
    "subtitle: Full Kubernetes CRD + operator-config API reference, generated "
    "from source and rendered with the compact Fern components.\n"
    "---\n"
)

_WARNING = (
    "> [!WARNING]\n"
    "> **Auto-generated from source.** This page is regenerated from the "
    "Dynamo operator CRDs by "
    "[`docs/fern/scripts/gen_kubernetes_api.py`](https://github.com/ai-dynamo/"
    "dynamo/blob/main/docs/fern/scripts/gen_kubernetes_api.py) and covers "
    "**every** type across all three API packages: the deprecated "
    "`nvidia.com/v1alpha1` surface, the supported `nvidia.com/v1beta1` surface, "
    "and the operator's own `operator.config.dynamo.nvidia.com/v1alpha1` "
    "configuration. The trimmed [DGD](dgd-reference.mdx), "
    "[DGDR](dgdr-reference.mdx), and [DCD](dcd-reference.mdx) references cover "
    "only user-facing `v1beta1` fields. To edit the surface, change the Go "
    "types under `deploy/operator/api/` and let CI regenerate this page.\n"
)


def render_mdx(reference: KubernetesReference) -> str:
    """Full MDX text for the compact-index Kubernetes API reference page."""
    parts = _mdx_head_parts() + _mdx_body_parts(reference)
    return "\n".join(parts)


def _mdx_head_parts() -> list[str]:
    """Frontmatter, generator marker, imports, styles, and preamble Warning."""
    return [
        _FRONTMATTER.rstrip("\n"),
        "",
        MDX_GENERATED_MARKER,
        "",
        'import { ReferenceStyles } from "@/components/ReferenceStyles";',
        'import { ApiKubernetesReference } from "@/components/ApiKubernetesReference";',
        'import { KUBERNETES_REFERENCE } from "./api-reference.data";',
        "",
        "<ReferenceStyles />",
        "",
        _WARNING.rstrip("\n"),
        "",
    ]


def _mdx_body_parts(reference: KubernetesReference) -> list[str]:
    """Compact React component, operator-defaults trailer, llms-only fallback."""
    return [
        "<ApiKubernetesReference reference={KUBERNETES_REFERENCE} />",
        "",
        _mdx_operator_defaults(reference.operator_defaults),
        "",
        "<llms-only>",
        "",
        _llms_only_markdown(reference),
        "",
        "</llms-only>",
        "",
    ]


def _mdx_operator_defaults(defaults: OperatorDefaults) -> str:
    """Render the operator-defaults trailer with H2→H3 heading demotion.

    The upstream Markdown treats the trailer as an H1 with H2 subsections
    (Pod Specification Defaults, Security Context, ...). The compact page
    embeds it as an H2 with twelve H3 subsections so the whole document
    (packages, types, operator defaults, agent fallback) still nests
    consistently under the page title Fern renders from the navigation.
    """
    parts = ["## Operator Default Values Injection", "", defaults.intro_markdown]
    for sub in defaults.subsections:
        parts.append("")
        parts.append(f"### {sub.title}")
        parts.append("")
        parts.append(_demote_headings(sub.body_markdown))
    return "\n".join(parts).rstrip() + "\n"


def _demote_headings(markdown: str) -> str:
    """Prepend one ``#`` to every ATX heading line in ``markdown``."""
    out: list[str] = []
    for line in markdown.splitlines():
        if _is_atx_heading(line):
            out.append("#" + line)
        else:
            out.append(line)
    return "\n".join(out)


def _is_atx_heading(line: str) -> bool:
    """True when ``line`` is an ATX Markdown heading (``#``..``######``)."""
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return False
    prefix = stripped[: len(stripped) - len(stripped.lstrip("#"))]
    if len(prefix) < 1 or len(prefix) > 6:
        return False
    rest = stripped[len(prefix) :]
    return rest.startswith(" ") or rest == ""


# ---------------------------------------------------------------------------
# llms-only Markdown fallback
# ---------------------------------------------------------------------------


def _llms_only_markdown(reference: KubernetesReference) -> str:
    """Full Markdown twin of the compact page for agent-mode exports."""
    total_types = sum(len(pkg.types) for pkg in reference.packages)
    header = (
        f"Dynamo publishes {len(reference.packages)} Kubernetes API packages "
        f"with {total_types} typed CRD / config sections."
    )
    parts: list[str] = [header, ""]
    parts.extend(_llms_packages_summary(reference))
    for pkg in reference.packages:
        parts.append("")
        parts.extend(_llms_package_section(pkg))
    parts.append("")
    parts.append(
        f"Full raw Markdown (agent-friendly source): [`api-reference.md`]"
        f"({SOURCE_HREF_MD})"
    )
    return "\n".join(parts).rstrip() + "\n"


def _llms_packages_summary(reference: KubernetesReference) -> list[str]:
    """Compact table listing packages, type counts, and jump anchors."""
    rows = ["| Package | Types | Jump |", "| --- | --- | --- |"]
    for pkg in reference.packages:
        rows.append(
            f"| `{pkg.name}` | {len(pkg.types)} | [#{pkg.anchor}](#{pkg.anchor}) |"
        )
    return rows


def _llms_package_section(pkg: KubernetesPackage) -> list[str]:
    """Markdown block for one package (Resource Types + typed rows)."""
    valid_anchors = {type_.anchor for type_ in pkg.types}
    lines = [f'### {pkg.name} <a id="{pkg.anchor}"></a>']
    if pkg.description:
        lines += ["", pkg.description]
    if pkg.resource_types:
        lines += ["", "**Resource Types:**"]
        for ref in pkg.resource_types:
            lines.append(f"- [{ref.name}](#{ref.anchor})")
    lines.append("")
    lines.append("| Type | Kind | Summary |")
    lines.append("| --- | --- | --- |")
    for t in pkg.types:
        lines.append(_llms_type_row(t))
    for type_ in pkg.types:
        lines += ["", *_llms_type_section(type_, valid_anchors)]
    return lines


def _llms_type_row(type_: KubernetesType) -> str:
    """One row of the per-package Markdown type table."""
    summary = _first_line(type_.description)
    return (
        f"| [`{type_.display_name}`](#{type_.anchor}) | "
        f"{type_.kind} | {_md_cell(summary)} |"
    )


def _llms_type_section(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """Complete Markdown schema for one Kubernetes type."""
    lines = [f'#### {type_.display_name} <a id="{type_.anchor}"></a>']
    lines += ["", f"**Kind:** {type_.kind}"]
    if type_.description:
        lines += ["", type_.description]
    if type_.underlying_type:
        lines += ["", f"**Underlying type:** `{type_.underlying_type}`"]
    if type_.validation:
        lines += ["", f"**Validation:** {type_.validation}"]
    if type_.appears_in:
        refs = ", ".join(f"[{ref.name}](#{ref.anchor})" for ref in type_.appears_in)
        lines += ["", f"**Appears in:** {refs}"]
    if type_.fields:
        lines += ["", *_llms_field_table(type_.fields, valid_anchors)]
    if type_.enum_values:
        lines += ["", "**Enum values:**", *_llms_enum_list(type_.enum_values)]
    return lines


def _llms_field_table(
    fields: Iterable[KubernetesField], valid_anchors: set[str]
) -> list[str]:
    """Complete Markdown table for a type's fields."""
    lines = [
        "| Field | Type | Required | Default | Description | Validation |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for field in fields:
        field_type = _resolved_field_type(field.type, valid_anchors)
        lines.append(
            f"| `{field.name}` | {_md_cell(field_type)} | "
            f"{'yes' if field.required else 'no'} | {_md_cell(field.default)} | "
            f"{_md_cell(field.description)} | {_md_cell(field.validation)} |"
        )
    return lines


def _resolved_field_type(field_type: str, valid_anchors: set[str]) -> str:
    """Preserve valid local type links and unwrap unresolved ones."""
    return LOCAL_FRAGMENT_LINK_RE.sub(
        lambda match: (
            match.group(0)
            if match.group("anchor") in valid_anchors
            else match.group("label")
        ),
        field_type,
    )


def _llms_enum_list(values: Iterable[KubernetesEnumValue]) -> list[str]:
    """Markdown bullets for every enum value and its description."""
    return [f"- `{value.name}`: {value.description or '-'}" for value in values]


def _first_line(text: str) -> str:
    """First non-empty line of ``text`` (or an empty string)."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _md_cell(text: str) -> str:
    """Sanitize a cell value for a Markdown table."""
    return escape_mdx_table_cell(text)


def _iter_all_types(
    reference: KubernetesReference,
) -> Iterable[KubernetesType]:
    """Convenience iterator over every type in the reference."""
    for pkg in reference.packages:
        yield from pkg.types


def _subsection_titles(subsections: Iterable[OperatorDefaultsSubsection]) -> list[str]:
    """Return the titles of every operator-defaults subsection in order."""
    return [sub.title for sub in subsections]


__all__ = [
    "MDX_GENERATED_MARKER",
    "TS_GENERATED_MARKER",
    "render_mdx",
    "render_ts_data",
]
