{{- if (and .Values.demo.enabled .Values.demo.gitea.adminPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitea.gitea.admin.existingSecret }}
type: Opaque
data:
  username: {{ "nvidia" | b64enc | quote }}
  password: {{ .Values.demo.gitea.adminPassword | b64enc | quote }}
{{- end }}