# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volcano
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: dynamo-production
  sources:
    - repoURL: https://volcano-sh.github.io/helm-charts
      chart: volcano
      targetRevision: 1.14.1
      helm:
        releaseName: volcano
        valueFiles:
          - $values/deploy/production/addons/volcano/values.yaml
    - repoURL: https://github.com/ai-blaise/k8s-playground.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: volcano-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
