existingImagePullSecret: nvcrimagepullsecret

# Global values used across charts
global:
  NGC_API_KEY: ${NGC_TOKEN}

compoundai-operator:
  enabled: true
  namespaceRestriction:
    enabled: true
    targetNamespace: ""
  controllerManager:
    manager:
      image:
        repository: gitlab-master.nvidia.com:5005/aire/microservices/compoundai/compoundai-operator
        tag: ${CI_COMMIT_SHA}
      args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect=false
        - --natsAddr=nats://my-nats:4222
        - --etcdAddr=etcd:2379

  compoundai:
    yatai:
    # todo: only use dns name
      endpoint: http://compoundai-server
      clusterName: default
    
    yataiSystem:
    # can we just infer this, or change scheme to use default until overridden
      namespace: ""

    internalImages:
      bentoDownloader: quay.io/bentoml/bento-downloader:0.0.5
      kaniko: quay.io/bentoml/kaniko:debug
      buildkit: quay.io/bentoml/buildkit:master
      buildkitRootless: quay.io/bentoml/buildkit:master-rootless
      metricsTransformer: quay.io/bentoml/yatai-bento-metrics-transformer:0.0.4
      debugger: quay.io/bentoml/bento-debugger:0.0.8
      monitorExporter: quay.io/bentoml/bentoml-monitor-exporter:0.0.3
      proxy: quay.io/bentoml/bentoml-proxy:0.0.1

    disableAutomateBentoImageBuilder: false
    enableRestrictedSecurityContext: false
    disableYataiComponentRegistration: false

    dockerRegistry:
      server: 'nvcr.io/nvidian/nim-llm-dev'
      inClusterServer: ''
      username: '$oauthtoken'
      # Password will use global.NGC_API_KEY by default
      password: ""
      passwordExistingSecretName: ''
      passwordExistingSecretKey: ''
      secure: true
      bentoRepositoryName: yatai-bentos

    bentoImageBuildEngine: kaniko
    addNamespacePrefixToImageName: false

    estargz:
      enabled: false

    kaniko:
      cacheRepo: ''
      snapshotMode: ''

nemo-datastore:
  enabled: true
  serviceNameOverride: "datastore"
  postgresqlapi:
    enabled: true
  primary:
    persistence:
      storageClass: ""
      accessModes:
        - ReadWriteOnce
  postgresqlgitea:
    enabled: true
    primary:
      persistence:
        storageClass: ""
        accessModes:
          - ReadWriteOnce
  image:
    repository: gitlab-master.nvidia.com:5005/aire/microservices/data-store/nemo-datastore-service
    tag: e8116f87bda01f2c219c7978e35ce20778c186a8
  imagePullSecrets:
    - name: nvcrimagepullsecret
    - name: gitlab-imagepull
  minio:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
    apiIngress:
      enabled: false
      ingressClassName: nginx
      hostname: minio.example.com
      pathType: Prefix
  demo:
    enabled: true
    gitea:
      createSecret: true
      adminPassword: giteadmin
  appConfig:
    DATASTORE_EXTERNAL_URL: https://cai-datastore.dev.aire.nvidia.com
  gitea:
    image:
      repository: nvcr.io/nvidian/nemo-llm/nemo-datastore-gitea
      rootless: true
      tag: v1.21.7-53405b0cc6a5df87ee2bd6cb977e7d4809094848
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      additionalConfigSources:
        - secret:
            secretName: gitea-server-secret
        - configMap:
            name: gitea-config
    persistence:
      storageClass: ""
      claimName: gitea-shared-storage
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    serviceAccount:
      create: true
      imagePullSecrets:
        - name: nvcrimagepullsecret
      name: gitea

compoundai-server:
  enabled: true
  istio:
    host: 
      ${NAMESPACE}.dev.aire.nvidia.com
  compoundai:
    # need to be set to deployment-management
    env:
      nds_host: datastore
  image:
    repository: gitlab-master.nvidia.com:5005/aire/microservices/compoundai/compound-api-server
    tag: ${CI_COMMIT_SHA}
  imagePullSecrets:
    - name: nvcrimagepullsecret
    - name: gitlab-imagepull
