# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Deploy Cleanup

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Host namespace to clean up'
        type: string
        required: true
      vcluster_name:
        description: 'vCluster name to delete'
        type: string
        required: true

jobs:
  cleanup:
    name: Cleanup AKS resources
    runs-on: prod-default-small-v2
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
    - name: Teardown vCluster
      if: inputs.namespace != ''
      uses: ./.github/actions/teardown-dynamo-operator
      with:
        kubeconfig_base64: ${{ secrets.AZURE_AKS_CI_KUBECONFIG_B64 }}
        vcluster_name: ${{ inputs.vcluster_name }}
        vcluster_namespace: ${{ inputs.namespace }}
