name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  conventional-commits:
    name: Validate PR title and add label
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1  # v1.5.2
        with:
          task_types: '["feat", "fix", "docs", "test", "ci", "refactor", "perf", "chore", "revert", "style", "build"]'
          add_label: 'true'