# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Shared Deploy Test

on:
  workflow_call:
    inputs:
      framework:
        description: 'Framework to test (vllm, sglang, trtllm)'
        type: string
        required: true
    #   profiles:
    #     description: 'JSON array of deployment profiles to test'
    #     type: string
    #     required: true
    #   image_suffix:
    #     description: 'Image suffix (e.g. vllm-runtime-cuda12-amd64)'
    #     type: string
    #     required: true
    #   namespace:
    #     description: 'Host namespace where the vCluster lives'
    #     type: string
    #     required: true
    #   vcluster_name:
    #     description: 'Name of the vCluster'
    #     type: string
    #     required: true
    #   operator_tag:
    #     description: 'Operator image tag'
    #     type: string
    #     required: true

jobs:
  deploy-test:
    runs-on: stg-deploy-tester-v1
    timeout-minutes: 25
    permissions:
      contents: read
    name: test
    steps:
      - name: test k
        shell: bash
        run: |
          set +e
          kubectl get pods